wikimedia-gadgets/twinkle

modules/twinklexfd.js
Newlines are significant and may break the functioning of the template
=> TfD: don't enter a newline after the TfD template

modules/twinklewarn.js
On "Rollback failed" pages, the selector $vandalTalkLink doesn't match any elements, causing an error when we do `href.indexOf("?")` on line 30. See issue #267.
=> Check for $vandalTalkLink existence

modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinklewarn.js
Twinkle block module. Blocks, reblocks, issues block templates, but unblocking not yet supported.
The data for block templates was moved from the warn module to the block module, but the warn module is used to actually issue the warning, and also previewing the templates. Also cleaned up some of the code in the warn module, most of it solely for block module integration.
The templates are now grouped together, grouped by popularity / type and sorted alphabetically. Also updated warn module with the durationless blocking templates, and although they are not uw- prefixed or conform to the user warnings wikiproject, they are essential for the blocking module.
=> Block module for administrators

modules/twinkleblock.js, modules/twinkleconfig.js
This is in response to feedback given at [WP:AN](https://en.wikipedia.org/wiki/Wikipedia:Administrators%27_noticeboard#New_Twinkle_block_module.21). Changes include:
* Don't autofill the article field with the value of the `vanarticle` URL parameter, as this may be less relevant for a block than when issuing a normal warning
* Do not show fields for duration, article, etc. for templates such as `{{anonblock}}` that do not conform to standards outlined by WikiProject User Warnings (as these params will likely not work)
* When issuing only a template, Leave the duration field blank and not supplied with expiry of an existing block
* When issuing only a template, add option to add `notalk=yes` to template
* When blocking and templating, add option to exclude the duration from the template …
=> Block modue bug fixes/requests from feedback, update config

modules/twinkleprotect.js
Next to persistent vandalism/sockpuppetry, these are the two most common semi-protection reasons, frustratingly missing from Twinkle. Surely other admins have gotten tired of having to either manually type in this rationale or use the native interface, where these options are available.
=> protect: add preset for unsourced content and disruptive editing

modules/twinkleblock.js
* Make generic block the default preset when module is first loaded
* Moved disruptive editing to the list of common block reasons
* Add support for page parameter to edit warring block template
* Fixed typo
Sorry they're not separate commits, I keep forgetting!
=> More updates to block module based on feedback

modules/twinkleprotect.js
Remove code that is no longer needed now that RFPP has switched to the new format.
=> Remove old RFPP code

modules/twinkleprotect.js, morebits.css
Fairly sizable update to the protect module that could use another set of eyes.
When protecting a page, admins must first check the protection log to make an informed decision on the duration. Just as with the block module, I've made it report if there were prior protection periods, and link to the protection log if there were. Here we also have to do a separate API call to fetch the pending changes log.
Next, I've included the log notice and current protection notice to be visible for all users, not just admins. We often get requests for semi-protection when the page is semi-protected, and the log info is useful for them to decide what duration to request and to explain their rationale. We also want to use meaningful colours to grab the user's attention. For instance, here again, if a …
=> Reporting if page has been protected before! And minor morebits.css change

modules/twinklewarn.js
Rationales for removal:
{{uw-2redirect}} - pretty sure a bot fixes these
{{uw-articlesig}} - button to add signature was removed from the edit toolbar when editing in mainspace
{{uw-csd}} - better you actually say why the speedy criteria they chose was not applicable
{{uw-directcat}} - surely is a rare occurrance. When it happens, just fix it
{{uw-fuir}} - I believe a bot does this, or those AWB people do. Surely doesn't happen enough to warrant inclusion here
{{uw-imageuse}} - Just going to go ahead and remove this. We have a verbose explanation shown via edit filter when they try to do this. Better we just write a personal note then send them to walls of outdated text
{{uw-incompleteAFD}} - Cyberbot issues more descriptive warnings
{{uw-nonfree}} - this is a warning, not a notice, and …
=> warn: pruning single-issue notices

morebits.js
I think this will do it. There might be a better way, I'm not familiar with how Morebits.js works
=> MoreBits.js: always assert the user is logged in when making a POST

modules/twinklespeedy.js, twinkle.js
This is **incomplete**. Still needs testing, and there's at least one bug I haven't been able to fix
* Allow admins to delete under multiple rationale
* Allow admins to use the subgroups to enter in values such as the URL for G12 deletions
* Use the corresponding template to generate a deletion summary
* Move custom rationale to top with it's own section, and supply the rationale generated by the CSD template already on the page, if it exists
=> Admins delete under multiple rationale, use template-generated delete reasons

modules/twinklespeedy.js
Currently `parseWikitext()` would bork on `.js`/`.css` pages for that `parse`'d give out something like `<pre>{{db-spam}}</pre>` instead of expanding the template.
=> speedy: Fix delete reason fetching on non-wikitext pages

modules/friendlytag.js
=> Expert-subject -> expert needed

modules/twinklewarn.js
A discussion on [WT:TWINKLE](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#.22Violating.22_the_three_revert_rule) has resulted in a consensus that the edit summary left by Twinkle shouldn't imply the user has broken the 3RR. The warning itself {{[uw-3rr](https://en.wikipedia.org/wiki/Template:Uw-3rr)}} doesn't say the user has broken 3RR, so neither should the edit summary.
=> Adjust {{uw-3rr}} description

modules/friendlywelcome.js
Change TWA invite syntax to "{{WP:TWA/InviteTW|signature=~~~~}}" - using the Twinkle-specific TWA invite template. This template is the same as TWA/Invite but adds a header
Template: https://en.wikipedia.org/wiki/Wikipedia:TWA/InviteTW
=> Change {{TWA invite}} template

modules/twinkleprod.js
Remove superfluous "move to Commons" tags when PRODing files. Deletion-tagged files cannot be moved to Commons
=> prod: Remove superfluous "move to Commons" tags

modules/friendlytag.js, modules/friendlytalkback.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinklewarn.js, modules/twinklexfd.js
See https://phabricator.wikimedia.org/T189067
Soon any and every link to a userpage will ping that user. Some of the colons added with this commit probably aren't necessary but I think this is still okay, just as a matter of good practice.
=> Suppress edit summary pings by prefixing links with a colon (T189067)

modules/twinklewarn.js
"spam links" → "inappropriate external links"
Requested at [Wikipedia talk:Twinkle#Edit summary for uw-spam1](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=796122026#Edit_summary_for_uw-spam1)
=> Update {{uw-spam1}} label and edit summary

modules/twinkleconfig.js
[[WP:UW]] leads nowhere, this should lead to the actual content described at [[WP:UWUL]]
=> Fix link re: blanking indef'd user talkpages

modules/twinkleblock.js
I've semi-frequently gone to use the 'Creating inappropriate pages' option, but been surprised that uw-npblock is really just referring to patent nonsense.  This makes the dropdown explicit about that fact.
=> twinkleunblock - Make dropdown text for nonsense block explicit

README.md
- Holdover reference to the former python script (deleted in 1898e31)
- Broken section link added in 3783550
=> readme - minor python -> perl correction

modules/twinkleprotect.js
- Place tag underneath the #REDIRECT header (don't break the redirect, remove need for `<noinclude>`)
- Detect {{Rcat shell (and sundry redirects) and do nothing if present
Closes #408
=> protect - A few fixes for tagging redirect pages

modules/twinklespeedy.js
As requested on [WT:TW](https://en.wikipedia.org/w/index.php?oldid=857841491#Db-disambig), this corrects the db-disambig tooltip to say that it applies to a page that dabs one page, not two or fewer.
Original text was introduced in f92641ebf02c60a8d635fa1e80edb93dca43389b, which was [correct at the time](https://en.wikipedia.org/w/index.php?title=Template:Db-disambig&oldid=353013319).
=> speedy: Correct language for G6 db-disambig

morebits.js
Fixes #231. @atlight Could I get a second pair of eyes on that regex? I'm pretty sure it's correct but I might have made a simple mistake.
=> morebits: Ignore file/category embeds when removing links

modules/twinklespeedy.js
Two different behaviors fixed:
- A few edge cases exist where twinkle won't notify the original creator, but it would still erroneously say you had notified the user in your log.
- Avoid using the title of a page nominated for G10.  The name of G10 noms was removed from the notification edit summary in e296afc roughly six years ago but it was still present in the edit summary for the log.  That's been fixed.  This also removes the title from displaying in the log itself, hiding it behind a piped wikilink.
=> speedy: A few tweaks to CSD logging

modules/twinkleprotect.js
Prevent issues if page name has = in it
[[[Special:Permalink/865529421#RPP function bug]]](https://en.wikipedia.org/wiki/Special:Permalink/865529421#RPP_function_bug)
=> protect: Use numbered parameter in pagelinks

modules/twinkleprotect.js
Pending Changes level 2 was officially turned off in Jan 2017 after the conclusion of a series of RFCs
(See https://en.wikipedia.org/wiki/Wikipedia:Pending_changes#Timeline but most prominently
https://en.wikipedia.org/wiki/Wikipedia:Pending_changes/Request_for_Comment_2016#Summary_of_previous_discussions and
https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(proposals)/Archive_137#Make_PC2_no_longer_available_to_admins).
The code has remained here since its introduction in e97c9b05 but is now just cluttering the dropdown with a grayed-out "do not use."
I've kept the weights for PC1 the same.
While I don't believe there has been a broad discussion about explicitly referring to PC1 as just PC, it has been endorsed several times:
- The final discussion turning PC2 off
- Template:Pp-pc2 …
=> twinkleprotect: Remove references to PC2, use PC instead of PC1

modules/twinklearv.js
Closes #372
Removes the autofile suggestion, which while convenient, was likely unhelpful in the long run.
=> ARV: Don't report without either a sockmaster or one sockpuppet

twinkle.js
=> twinkle: Tweak default CSD pref to not mark as patrolled

modules/friendlytag.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklexfd.js
Going through a probably sure-shot TfD. I agree with the fact that it's basically a remnant of Article Wizard and has no potential usecases. https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2018_October_30#Template:New_unreviewed_article
=> tag: remove support for deprecated template {{new unreviewed article}}

modules/twinklexfd.js
If a redirect being nominated for RfD redirects to a section, add on that section to the rfd2 nomination template.
I'm no whiz with XML, so this just copies how the target itself is found.  Closes #409
=> twinklexfd - Add section to RfD nomination

modules/twinklewarn.js
Fixes #404
The function to change the input label for certain warnings (change_subcategory) is only called when changing items in the submenu, so since uw-aiv is the first item, it won't show unless you change submenu items rather than the main category menu.  This is obviously less-than-ideal, but still an improvement over the current situation.
=> twinklewarn - Treat userlink properly for uw-aiv

modules/twinklefluff.js
Fix rollback link on contribs page
Previous discussion: https://github.com/azatoth/twinkle/commit/9b61d36a364cd1a9fce2e72b0b7ed13aa291fc00#comments
Starting around Nov 10, there were multiple reports of failed rollbacks from the contribs page at WT:TW: [here](https://en.wikipedia.org/w/index.php?oldid=872508505#Problem_when_clicking_on_%22vandalism%22_link_while_examining_user_contributions) and [here](https://en.wikipedia.org/w/index.php?oldid=872508505#Rollback_malfunction)
[T205581](https://phabricator.wikimedia.org/T205581) introduced a number of css changes to allow for full skinnability.  [One of these changes](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/461237) put the diff and hist links into their own span, thus hiding the a elements as children of that span rather than …
=> Fix rollback link on contribs page

modules/friendlytag.js
Closes #444.  While processing new tags on a redirect page, check the page for
already-existing redirect categories.  If they exist, whether within or
without an Rcat shell, fold them and the new tags into an Rcat shell.
There is some double-processing, as the already-existing method to check for
duplication remains, but the intent of this is not to affect 'tags' so as not
to affect the edit summary.  Moreover, the old tags remain unsorted, mainly to
avoid creating a broader-scope-than-necessary variable, but is probably a good
idea anyway, to avoid the perception that those tags were added by the user.
Rcat regex courtesy of [[User:Kephir/gadgets/sagittarius.js]] and #433
=> friendlytag: Group old and new redirect tags within Rcat shell

modules/friendlytag.js
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Redirect_tagging_request
Thought it was weird the redirect interface is one of the few not sorted by alphabetical order.
=> tag: Add {{R from incorrect name}} and sort redirects in alphabetical order

modules/twinklespeedy.js
handle the case of csd being G10 only if request isn't coming from DI module, since params.normalizeds is undefined if so; this also reduces the net number of condition checks.
=> speedy: bug fix

modules/twinkleconfig.js, modules/twinklespeedy.js
Added newly-introduced CSD R4 per [discussion](https://en.wikipedia.org/wiki/Special:PermanentLink/872246394#Redirects_in_the_File:_namespace_G6_%E2%86%92_R4). Merged db-blankdraft to db-g13 per [discussion](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Criteria_for_speedy_deletion&oldid=872669362#Proposal_to_merge_db-blankdraft_into_G13)
Closes #466.
=> speedy: add R4, merge db-blankdraft to G13

modules/twinkleprod.js
If page is being nominated for BLPPROD, a check is done to see if article has [[Category:Living people]]. If not, user is warned about it and they can choose to either continue or abort the action.  If they choose to continue, [[Category:Living people]] is added to the article along with the prod tag. 
This feature makes TW smarter and helps prevent bios of deceased people (and non-bios) from being mistakenly tagged for blp-prod.
=> prod: add alert if BLPPROD is applied but article is not in Category:Living people

modules/friendlytag.js
These have the least number of transclusions and per the talk page, there's really no need to include them.
=> tag: Remove {{dead end}} and {{metricate}}

modules/friendlytag.js
Would be helpful in situations where the issue is too extensive to explain in a {{cleanup}} tag.
=> Add 'Template:Cleanup rewrite' to tagging module.

modules/friendlytag.js
1.  Added |reason= and |talk= fields to {{[Expert needed](https://en.wikipedia.org/wiki/Template:Expert_needed)}} as requested at [Wikipedia:Twinkle/to_do](https://en.wikipedia.org/wiki/Wikipedia:Twinkle/to_do) . Either of these two fields is compulsory per documentation. (Though this isn't enforced here) 
2. Per Issue #353, edit summary is buggy when a custom tag with parameter is added. Also handled this issue for the case that the tag isn't in template namespace.
=> tag: |reason= and |talk= fields for {{Expert needed}}, edit summary fix for custom tags with parameter

modules/twinklefluff.js
Follow-up to https://github.com/azatoth/twinkle/pull/439#issuecomment-436102516
Relies upon the id in `MediaWiki:Sp-contributions-footer-anon-range` to discover if we're viewing a range's contributions.  This is required because while using wgRelevantUserName (#439) avoids the previous iteration's console error, it isn't (reliably) refined for IP range, and doesn't exist when viewing their contributions (see https://phabricator.wikimedia.org/T206954).
Incidentally, this doesn't break for ranges outside the CIDR limit (/16 on enWiki) because mediawiki incorrectly shows `MediaWiki:Sp-contributions-footer-anon` in that case. Depending on how (or if) https://phabricator.wikimedia.org/T211910 is resolved, this may or may not need updating.
=> fluff: show rollback/vandalism links for IP ranges

morebits.js
Added some documentation (jsdocs) for several of morebits classes. Since jsdocs are shown by code editors in tooltips, this would greatly help the next generation of script writers. 
I converted existing documentation comments to jsdoc-comments for wiki.page, wiki.api, wiki.preview, string, array, regexp classes while adding my own $0.02 here and there. For wikitext.page, it is written from scratch. 
In the 3rd commit, I rearranged the order of several functions in wiki.page, hence the diff for that class may look quite messy.
=> Morebits: add documentation

modules/twinklexfd.js
This is hotly requested by TfD regulars, even if it is non-standard for other XfDs
=> xfd: Notify creator of second template of tfm nomination

modules/twinklespeedy.js
Requested at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=878315943#Function_request).  Given the data I posted there, this would get used much at all, but as far as U2 noms go it'd be about 1/3 of them, so that seems worth allowing.
U1 was enabled in 61c2f4a33
=> speedy: Enable U2 on redirects

morebits.js
I've reviewed all the commits in #481 and #496. There was one function that got removed accidentally. Apologies for the inconvenience caused to all, and to @Amorymeltzer for their wasted time.
Closes #506.
=> morebits: add back accidentally removed function 

modules/friendlytag.js, modules/twinkleconfig.js, twinkle.js
Added custom tags support for files per request at [Wikipedia_talk:Twinkle#Custom_tags_for_non-article_namespace](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Custom_tags_for_non-article_namespace). Then realised that now only redirects are being left out, so added it to that too.
=>  tag: add custom tags for files and redirects as well

modules/twinklespeedy.js
Closes #348
Mirrors the message below for found XfD tags.  There are certainly cases where multiple tags
may be warranted (G11 and G12 are quite commonly paired, for example) but where only one was
placed initialy.  Ideally, this would be rewritten to fold any new tags in with the old and
group them all under db-multiple.
=> csd: Ask if the user wants to double-tag a page

modules/friendlytag.js
Closes #250. 
~~I have no idea how to link the help pointer to [[Wikipedia:Template messages/Redirect language codes]],~~ as quickForm input labels don't allow links (or any kind of HTML) in them. This is due to use of `node.appendChild( document.createTextNode( data.label ) );` kinda code in morebits.js; it would have been better if morebits had simply used `node.innerHTML = data.label`. UPDATE: Done now, $.parseHTML was the answer.
~~As an aside, I made `var makeCheckbox = function(tag, description)` from Twinkle.tag.updateSortOrder (where it was used only for articles) global, as Twinkle.tag.makeCheckbox, as this function could potentially be used elsewhere. This would've made the diff look messy. Sorry for that :(~~ Reverted, in hindsight, it was never necessary. It's easier to make a …
=> tag: add more parameters

modules/friendlytag.js
Closes #221.
Since all multiple issues tags within sections have |section= parameter, the issue can be resolved simply by adding a negative lookahead for |section= to the regex that checks for {{multiple issues}} template.
=> tag: avoid putting tags into {{multiple issues|section=y|  }} boxes; remove miOldStyleTest + more related fixes

modules/twinklewarn.js
[Deleted at TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2017_September_21#Template:Uw-subst) 18 months ago.
[Reported at WT:TW](https://en.wikipedia.org/w/index.php?oldid=883976908#Deleted_Template:Uw-subst_in_warning_screen?)
=> warn: Remove uw-subst

modules/twinklespeedy.js
Match policy at WP:CSD, requested at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=883223538#G1_in_userspace)
=> speedy: Exclude G1 and G2 from userspace

modules/twinklewarn.js
Basically, in 26 May 2016, the devs turned on in-place rollback (i.e. no post-rollback diff) and confirmation (if opened in a new window) with [phab:T88044](https://phabricator.wikimedia.org/T88044).  This broke a bunch of important stuff (see [phab:T136375](https://phabricator.wikimedia.org/T136375)) and [made a lot of people very angry](https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(technical)/Archive_147#Rollback_function_has_been_changed).  @atlight hacked together a quick fix for Twinkle in f53706a while the devs worked it out.  Widely regarded as a bad move, the change to rollback was [quickly rolled back](https://gerrit.wikimedia.org/r/c/mediawiki/core/+/291249).  The change in Twinkle, however, has remained ever since, but hasn't been necessary.
=> warn: Remove outdated hack from f53706a

morebits.js
Could also be extendedconfirmed or template; don't think PC would throw an error.
The split here was added in b504af2d to make the protection response nicer, stating that:
>The API gives some pithy error stating which particular right the user lacks
I'm not sure what that previous message was, but the current response from `getErrorText()` is:
>This page has been protected to prevent editing or other actions.
That seems friendly enough but doesn't give the missing right and certainly isn't pithy, so I suppsoe it's worth maintaining the split.
=> morebits: Protection error needn't be full protection

modules/twinklewarn.js
These (uw-redirect, uw-ics, uw-af) were removed in 96e6ac36 and have been left in the comments for nearly six years
Closes #425
=> warn: Remove commented-out warnings removed in 2013

modules/twinkleconfig.js, modules/twinklewarn.js, twinkle.js
Closes #162
Still loads the page in edit mode, but optionally opens the warning menu.  Defaults to previous behavior (although perhaps there's an argument that it shouldn't).  I think this is likely to be popular!
One thing to consider is whether the config option should be in the warn or rollback on WP:TW/PREF.
The first commit is actually to `twinkleconfig` and moves an xfd-relevant item (`markXfdPagesAsPatrolled`) to the proper section (introduced in 6651b059).
I should note that I've put this live on test.wiki
=> warn: Add option to allow automatic opening of menu after revert

modules/friendlywelcome.js, modules/twinkleblock.js, modules/twinklewarn.js, modules/twinklexfd.js
`Morebits.wiki.preview`, specifically `beginRender`, takes an optional second parameter, defaulting to the current page, which is used to determine the content model of the output from the parse API query.  We've largely ignored that parameter, meaning that if you attempt to generate a preview while on a non-wikitext page (JS, CSS, JSON, etc.), `beginRender` defaults to the model of that page.  This fixes that by explicitly providing a wikitext page (`xfd` already did).
I chose `WP:TW` because it is:
- Already fully protected
- Within the project scope (i.e. "ours")
- Heavily used so unlikely to be changed
If merged, I'll leave an inline comment in the shortcut alerting any sysops not to change the content model, although I imagine that will never happen.
=> block/warn/welcome/xfd: Make sure the preview renderer uses wikitext

modules/twinklewarn.js
Closes #491.  Leaves the curlies on for custom messages to make it clear they are, in fact, templates.
I also changed the dropdown menus so that the warning level numbers come first.  That is, `General note (1)` is now `1: General note`, and so on.  This makes the entire menu easy to access via keyboard, negating the need of the cursor for most actions.  As noted in https://github.com/azatoth/twinkle/issues/491#issuecomment-465255614 I'm not wild about the look, although maybe that's just 'cause they're different.
These should be squashed if both chosen.
=> warn: Remove curly braces from display, allow for easy menu access via keyboard

modules/twinklexfd.js
Lack of a newline (#254) can cause issues if the template is a table or uses other wikitext formatting (e.g. indentation).  As [discussed at TW:TW](en.wikipedia.org/w/index.php?oldid=886765882#Twinkle_TFDs_breaking_tables), this should (mostly?) only be relevant if the standard or sidebar options are appropriate; the two inline templates should clearly never have a newline.  Closes #359.
=> xfd: Add a newline after standard and sidebar TfD/M stylings

modules/twinklewarn.js
Favor autowelcoming (via the `friendlywelcome` parameter) over autowarning (added in #509); both use vanarticle
=> warn: Don't autowarn when autowelcoming

twinkle.js
Per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=868832371&diffmode=source#Twinkle_dropdown_in_Vector, added a `<input type="checkbox" class="vectorMenuCheckBox" aria-labelledby="p-twinkle-label">` to the relevant div element. And added `id="p-twinkle-label"` to the "TW" heading text. 
This provides TW button with the same special effects of the More button. 
I have been unable to test this by any of the usual methods. Pasting code to console or loading it from userspace js page lead to a bizarre "Twinkle.arv() is not a function" error. Looks like the only way to test would be to apply these changes to https://test.wikipedia.org/wiki/MediaWiki:Gadget-Twinkle.js .
=> twinkle: improve TW menu button in vector skin

modules/twinklexfd.js
Closes #168 and #311.  Pretty much all of this was done by @Scimonster in #311 as part of GCI2015 (see also #307); I just handled the intervening conflicts (in particular #430)
I ditched the "waiting" messages in favor of the "loading" from the preview box and incorporated getDiscussionWikitext into RfD's todayslist.
=> xfd: Finish adding preview (support RfD, CfD, and CfD/s)

twinkle.js
Closes #513. Does not affect user set preferences, just the default.
Fix for #529
=> twinkle.js: Change default talkback heading to "New message from" + username

modules/twinklefluff.js
1st commit: Remove some duplicate code
- The same four lines, three of which used spanTag, were repeated frequently
- Newer revisions either are the latest or not
- No idea what .firstrevisionheader did but I can't find it anywhere on-wiki, so removed
2nd commit: Avoid using Morebits.queryString to parse the url for 'oldid'
The url on diffs and old revisions is fickle, and may not necessarily display exactly what you think or expect based solely on the value of oldid.
- wgRevisionId added in MW 1.22 circa (2013)
- wgDiffOldId and wgDiffNewId added in MW 1.30 (2017)
=> fluff: Remove duplicated code and avoid using Morebits.queryString

README.md, sync.pl
1st commit: Fix sync.pl
- Roughly match previous behavior, although some dependencies have changed.
- Doesn't respect previous .mwbotrc preferences, but then again they haven't worked in years and won't work here
2nd commit: Autogenerate edit summaries, add some safety/error handling, other improvements
- Grab a commit hash from the edit summary of the most recent revsion of the on-wiki page, - and do our best to concatenate the log from there
- Require a clean working environment for all actions, not just --pull (matches implied intent in docs)
- Require confirmation of edit parameters before initiating
- Ensure files and pages being pulled/pushed/deployed exist
- Skip files without any changes
- Use File::Slurper over File::Slurp (See …
=> Fix and improve sync.pl

modules/twinkleimage.js, modules/twinklexfd.js
Closes #378
As noted there, the check added in 8b65bb1 meant that twinkleimage would no longer load on history pages (similar to ad5af2f).  I've loaded these changes into test.wiki, and this seems to no longer be an issue, presumably as the structure and loading of Twinkle has changed dramatically since then.
These changes are imperfect, however.  In order to allow loading on history pages, the conditions must be relaxed, such that it is possible for twinkle image and xfd to load on a local nonredirect page with no file on it.  One possible workaround could be a (morebits?) test for a file rather than trying to detect 'mw-imagepage-section-filehistory', but per [quarry:query/32775](https://quarry.wmflabs.org/query/32775) these seem rather rare (2-3 a month) so the benefit likely exceeds …
=> xfd and image: Remove check that prevented loading on history pages

modules/twinklespeedy.js
`{{db-nowcommons}}` is a redirect to `{{now commons}}`, which is not a speedy tag, and is already covered in the tag module.  Similar to #536.
=> speedy: use db-commons instead of db-nowcommons for F8

modules/twinklespeedy.js
Previously, if you checked then unchecked any mode-changing box (multiple criteria or tag/delete toggle), the prefilled rationale from the existing tag would be gone
=> speedy: Retain prefilled rationale after mode change

modules/twinklespeedy.js
This solves a long-standing issue for `radioClick` fans.  Toggling between deletion and tagging modes, or turning OFF "delete/tag with multiple" would increase the number of "Submit" buttons on any subgroup with two or more inputs (currently G6 move and G12).
Per https://github.com/azatoth/twinkle/pull/300#issuecomment-159598393 this is only affected a handful of users... but I was one of them!
=> csd: Don't multiply submit buttons for multi-input subgroups (radioClick)

modules/twinkleblock.js, modules/twinklewarn.js
No code changed, just the display text.  `warn` has used 'article' since the initial gh import, and `block` used that same language; still, people warn or block based on all pages, not just articles, so we might as well be exact.
=> block/warn: Use 'page' instead of 'article' in label/tooltip

modules/twinkledeprod.js
PROD is only valid in mainspace and filespace, and BOOKPROD is valid for bookspace and userspace books, so we should only query for pages in those namespaces.
`deprod` initially only activated on categories named like "Category:Proposed_deletion_as_of_DATE", but since 315c06b it has been available in any category with "proposed deletion" in the name.  That might be something to revisit, but regardless, that allowed invocation on [[:Category:Expired proposed deletions]]; this will prevent [[:Category:Expired proposed deletions of unsourced BLPs]] from showing up in the `deprod` list in that case.  Could also avoid some erroneous deletions by an unwatchful eye.
=> deprod: Only get pages in appropriate namespaces (0|2|6|108)

modules/friendlytag.js
- simplified `Twinkle.tag.callback.evaluate`, reducing the lines of code as well as making to easier to maintain. Now if you add subgroups to some tags, you no longer have to update anything in this function.
- file tags: convert tag-specific prompt dialogs to subgroups for better user experience
=> tag: further improvements

modules/friendlytag.js
1st commit: Avoid most redirects
- {{cleanup-reorganize}} -> {{cleanup reorganize}}
- {{fansite}} -> {{fanpov}}
- {{overcoverage}} -> {{over-coverage}}
- {{plot}} -> {{long plot}}
- {{undue}} -> {{undue weight}}
Left {{linkrot}}, {{news release}}, and {{tense}} for ease of access, as those may be more memorable/unique than {{Cleanup bare URLs}}, {{Cleanup-PR}}, and {{Cleanup tense}}, although those should probably be done as well.
This sort of thing should probably be done more regularly; it will make things like the second commit and #178 easier in the future.
2nd commit: Add {{no plot}} and {{like resume}}
- {{no plot}}: ~2.8k mainspace transclusions, matches {{long plot}} and {{all plot}
- {{like resume}}: ~2k mainspace transclusions, different from {{autobiography}}, closes #178
=> tag: Avoid most redirects, use templates directly

modules/friendlytag.js
Uses regex from the speedy module, partial fix for #237.  AfD is NOT supported because it doesn't lead with a template, but rather with a <!-- comment.
This regex was already enormous and unwieldy, and is now even worse.  It'd be good to clean it up, but even modern js isn't fully pcre, so there's no /x to help us out.
=> friendlytag: Put tags under csd and prod nominations (not afd yet)

modules/friendlytag.js, modules/twinklespeedy.js
{{db-histmerge}} was [renamed](https://en.wikipedia.org/w/index.php?title=Template:History_merge&diff=420055188&oldid=401464558) and [removed](https://en.wikipedia.org/w/index.php?title=Wikipedia%3ACriteria_for_speedy_deletion&diff=prev&oldid=420062064) from the the CSD criteria in March, 2011, following [brief discussion](https://en.wikipedia.org/wiki/Wikipedia_talk:Criteria_for_speedy_deletion/Archive_42#Remove_db-histmerge_from_CSD).  Of interest, the initial import of Twinkle into GitHub happened merely a week earlier.
Both have remained thus for nearly eight years, so we've technically been wrong for quite some time.  `{{history merge}}` is a bit of a weird beast, with a warning associated with it (`{{w-c&pmove}}`) like a speedy; that template is available in `twinklewarn`, and I …
=> speedy/tag: Move histmerge from speedy to tag

modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinklexfd.js
See individual commit messages for the specifics, but basically this just hammers `wgPageContentModel` to avoid the lua error message and be helpful.  Closes #478 
**Protect**:
- Disable tagging of modules
**CSD**:
- Places the CSD tag on the /doc subpage (i.e., what is done at WP:TFD)
**XFD**:
- Place the XFD tag on the /doc subpage
- General fixes and tweaks to handle modules, in particular language changes
Regarding the changes to `twinklexfd`:
- As written, the display style will show only `module` for modules.  Another option is to always list all the options (module, standard, tiny inline, etc.) but disable module for templates and disable the others for modules.  The first seems more reasonable to me? 
Another option is to just always list 'em all, default to the correct one, and …
=> xfd/protect/speedy: Improve handling in Module space

modules/twinklespeedy.js
Solves #554 by separating speedy deletion criterion R2 and R4 into separate fileRedirect and mainspaceRedirect, and then adding those only when the page is a redirect in the file namespace or in mainspace
=> csd: Only show R2 and R4 criterion when applicable

modules/twinklespeedy.js
- Support additional named parameters in A5 (location) and T2 (rationale)
- Add additional entry for F9 (rationale)
- F9: Require either the rationale or the url to be provided in order to carry through
- Remove unused date parameter for F8
- Be explicit with remaining named parameters in preparation for #441, specifically https://github.com/azatoth/twinkle/pull/441#issuecomment-439909083
=> speedy: Add additional named parameters

modules/twinklespeedy.js
Closes #136
Improves/expands the CSD log with the various parameters that a user
may enter upon nomination (e.g., custom G7 rationale, multiple G12 urls, etc.).
Basically just abuses params.templateParams[0] (which is itself an array),
with most of the complexity/duplication coming from the fact that DI has
an entirely different data structure, G12 can have multiple options unlike
most of the others, and the custom db option is of course different as well.
Ignores:
- G13 ts
- G10 blanked
- Check boxes from DI (non_free, derivative)
=> speedy: Add user-specified CSD parameters to the CSD log

modules/twinkleconfig.js, modules/twinklexfd.js, twinkle.js
Requested at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=885374731#Notifying_redirect_targets)
Enabled by default and creates new preference, xfdWatchRelated, that works the same as xfdWatchUser
=> xfd: New feature: Notify redirect target of RfD discussion

modules/twinkleunlink.js
- remove unnecessary API call to check for extendconfirmed right
- avoid hardcoding maximum api limits
=> unlink: remove unnecessary api call, and hardcoded api limits

modules/twinkleprod.js
Basically just copied from #494, with the irrelevant bits taken out.  These have changed a fair amount in the past decade or so, and this line hasn't been updated since the initial GitHub import.
=> prod: Update regex for non-prod deletion templates

modules/twinkleprod.js
Closes #538.  Limit to pages in the category to avoid having a mostly useless (and possibly confusing) `prod` tab on typical user pages.
<s>Opened as draft pending outcome at [WT:BOOKPROF](https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion_(books)#Should_Twinkle_enable_prod_in_userspace%3F).</s>  With no input a week later, I'm opening this up as it seems the best compromise, contrived though it may be.
=> prod: Enable BOOKPROD on userspace books in appropriate category

modules/twinkleprod.js, modules/twinklespeedy.js
Closes #577. If notification to page creator couldn't be sent (eg. when the
user talk page is protected), then don't say "notified ___" in log entry
=> speedy/prod: don't log notification if that failed

morebits.js
- String.prototype.trim is now supported on all target browsers
- String.prototype.trimLeft is not used in Twinkle or other Morebits-based scripts
- String.prototype.trimRight was used only once which I removed as we can just use trim there
trimLeft and trimRight are unsupported only in IE 11.
=> morebits: Remove string trimming shims

modules/twinklespeedy.js
Per the discussion in #574, added a `showInNamespaces` property to CSD criteria list objects to simplify the code that causes some criteria to be shown only on applicable namespaces.
=> speedy: add `showInNamespaces` and `hideInNamespaces` properties to csd criteria lists

modules/twinklespeedy.js
If a File: that exists at that name on Commons is deleted, the user log entry will remain blue, as if it were not deleted.  This adds a link to the page log for investigation, for both speedy and di, styled as "File:Amory.jpg (log):"
Closes #214
=> speedy: Add link to log when logging files

modules/twinklewarn.js
Put the signature in getWarningWikitext since both preview and the actual edit will want it.  Asked for at WT:TW https://en.wikipedia.org/wiki/Special:Permalink/893444378#Double_signature
See 96e6ac36 for the rise of the current implementation, but the real divide is from 86a052c3
=> warn: Show signature in preview as well

modules/twinkleprotect.js
Similar to #451, it would be better if we didn't offer inappropriate options.  The error from the API request is clear enough, but it resets the form.
We *could* turn it off entirely a la #551, but I think it'd be better to do this for 6-12 months before removing it entirely to smooth the transition and get the additional nudge.
In the distant future, it would be nice for this not to be hardcoded, but $wgFlaggedRevsNamespaces isn't exposed to javascript; that's [[[phab:T218479]]](https://phabricator.wikimedia.org/T218479)
=> protect: Disable pending changes dropdown on ineligible namespaces

modules/twinkleprotect.js
Mainly to help make testing at test.wiki a little smoother, but theoretically this should also help (down the road) support for other wikis
=> protect: Don't fail if flaggedrevs/pending changes aren't enabled

modules/twinkleblock.js
Various synonyms for infinite weren't always considered in the blocking api, see https://phabricator.wikimedia.org/T68646.  This was fixed in https://gerrit.wikimedia.org/r/c/mediawiki/core/+/140276 so that infinite, indeinite, infinity, and never are treated the same.  Also allowed for infinity and infinite in the regex matching.
=> block: Remove old fix for indef expirys that is no longer necessary, refactor some regex

modules/twinkleprod.js
Recent changes to [[Template:Old prod]] (<https://en.wikipedia.org/w/index.php?title=Template:Old_prod&diff=877241714&oldid=875601620>) by User:SD0001 (aka @siddharthvp) added a parameter that allowed for {{old prod}} to be added before contestation, without being added to the category until a timer has elapsed.  As such, Twinkle can feel free to safely add the template upon nomination, thus ensuring the page, if not deleted, will actually be tagged with the old prod template.  This would be a huge improvement, as contested prods are rarely tagged.  In theory the talk page won't be updated with the appropriate category until edited/purged, but that's still a clear gain over the current situation.
This doesn't endorse an already-existing {{old prod}} if the user is endorsing a {{prod}}, …
=> prod: Add {{old prod}} to talkpage on nomination

modules/twinklewarn.js
This dates back to 2008 (<https://en.wikipedia.org/w/index.php?diff=247182138&oldid=245908598&title=User:AzaToth/twinklewarn.js>).  There used to be a group 8 with block templates for sysops, hence the `Morebits.userIsInGroup` switch, but after #260 it was removed and this persisted, meaning that we don't need any special handling for sysops or nonsysops here.  That is, `defaultGroup > 7` would handle any remaining unmodified options (there are some).  <s>That being said, if even *that* isn't present, I don't get any errors in Chrome, FireFox, or Safari, so it doesn't seem necessary.  Perhaps it throws/threw an error in IE?</s>  Similarly, `undefined` or -1 groups were possible due to how the config was structured back then: in your skin.js rather than a separate file.
Perhaps old …
=> warn: remove old fix for out-of-range defaultGroup

modules/twinklebatchprotect.js, modules/twinkleprotect.js
1. (auto)confirmed is needed to move any page, even in your own userspace
2. After WP:ACPERM, (auto)confirmed is needed to create an article in mainspace
3. Removed AC move protection option from batchdelete
=> protect: Remove autoconfirmed from dropdowns when inappropriate

modules/friendlywelcome.js
Builds off #439, see also 225b2cd2
I think this is worth doing, with benefits outweighing any minor downsides (a la warning), but on the other hand it'd be an extra tab on some pages folks aren't used to and is certainly a less popular tab than `warn`.
=> welcome: Enable on every user-related page

modules/twinkleconfig.js
Add <nowiki> at the start of users' twinkleoptions.js, and </nowiki> at the end, to ensure that templates listed in them aren't parsed. Currently, [this tracking category](https://en.wikipedia.org/wiki/Category:Pages_with_templates_in_the_wrong_namespace) lists https://en.wikipedia.org/wiki/User:BilCat/twinkleoptions.js and https://en.wikipedia.org/wiki/User:Senator2029/twinkleoptions.js as in the wrong namespace, likely because they have templates in the source. The nowiki tags are written in 2 parts to avoid them being parsed at  [the gadget page itself](https://en.wikipedia.org/wiki/MediaWiki:Gadget-twinkleconfig.js)
=> Config: Add <nowiki> tags to user config pages

modules/twinklexfd.js
Fixes #617.  Introduced by me in #521: basically, `xfdcat` is used by cfd/cfds and tfd to switch the type of nomination (cfd versus cfr, tfd versus tfm) but for AfD it does something entirely different: sort the discussion into one of the various AfD categories (biography, media, etc.).  While the former is used via `venue`, we still need to call it for afd.
=> xfd: Fix broken AfD category sorting

modules/twinkleconfig.js
Update comment about default unlink namespaces ([ 0, 100 ] -> [ 0, 10, 100, 118 ]) per actual defaults in twinkle.js
=> Config: Update inline comment

modules/twinkleprod.js
Caused by a capturing group introduced in b7f79ed
=> prod: Don't insert a stray comma when endorsing prod

modules/twinklespeedy.js
1st commit: Ignore blank f9 rationale or url in log (bugfix)
- Fix logic from #546 that would allow url or rationale as an empty string when logging in #441
2nd commit: link additional parameters in the CSD log if possible (enhancement)
- wikilink: G4 `xfd`; G6 `page`, `fullvotepage`, `sourcepage`; A2 `source`; A10 `article`; F5 `replacement`
- user: G5 `user`
- file: F1 `filename`
- template: T3 `template`
- external: G12 `url`, `url2`, `url3` (only if beginning with http)
- commons: F8 `filename`
- WP:CSD section: P1 `criterion`
Style the link using curly braces `{}` instead of square brackets `[]`.  Also adds a tooltip to the G6 xfd input.
=> speedy: Further improve extra parameters in CSD log

modules/twinklespeedy.js
Deletion discussions can be closed as delete by non-admins (specifically in the case of TfD, where they can be closed as delete but need to be orphaned first) - change "An admin has closed a deletion discussion..." to "A deletion discussion was closed..."
=> Speedy: Tweak db-xfd tooltip to be sysop-agnostic

modules/twinklexfd.js
- Link to discussion in user notification edit summary
- Align use of listing/nominating with discussion/deletion
- Note whether TfD npm is a merge or delete, a la CfDS
- Adjust window header and tooltip to not just refer to deletion
Closes #571
=> xfd: Adjust edit summaries for parallelism and to be more helpful

modules/twinkleimage.js
Since the DI tab is only available on files, and only includes speedy deletion criteria applicable to files, the link should point to the specific section of the speedy deletion policy.
=> Image: Link "speedy deletion policy" directly to #Files

modules/friendlytag.js
1st commit: Continues on #541, closes #237.  Makes regex far more readable per @siddharthvp.  Put tags under AfD notices and actually work for PROD now, as #541 didn't really account for the multi-line input from subst-ing.
2nd commit: Puts tags under `{{salt}}` and `{{endorsed prod}}`
=> tag: Cleanup regex, put tags under AfD notices, fix prod regex, put under salt and endorsed prod

modules/friendlytag.js
Closes #624.  {{R from alternative name}} has a div element, and the processing schema introduced in #487 dies on it
=> tag: fix bug when processing items with type=div

modules/twinklebatchundelete.js, morebits.js
tl;dr — Add `undeletePage` to `Morebits.wiki.page`, use it in `twinklebatchundelete` (helps with #613), bump `maxRetries` (helps with #613), restructure talkpage undeletion (from #601), and add red color for fully create protected pages.
- 1st commit: morebits: Add undeletePage to morebits.wiki.page
Basically just copy the stuff for deletePage, less following redirects.  deletePage was added in 4b92869 along with move, but unlike protect (68132e5) delete and undelete are one-way streets.  Uses a dumb kludge to get around the lack of a proper token until we can rewrite the token handling stuff in `morebits` (#615).
- 2nd commit: batchundelete: convert to use Morebits.wiki.page.undeletePage
Added in prior commit (47c9cf9).  Some testing suggests this helps a bit with #613, but regardless, …
=> batchundelete: Improvements to morebits.wiki.page, short- and long-term alleviation of #613, color like batchdelete

modules/twinklexfd.js
Allow listing of the discussion on deletion sorting pages while creating an AFD. Closes #143. While there may be no need for Twinkle to provide a standalone delsort tool, it would be probably helpful to have one within xfd module, allowing afd nominators to sort their afds while creating it. 
This makes use of the `jquery.chosen` module/library, which I have loaded using `mw.loader.using`. Do we have to add it to the list of dependencies or do something funny like that? I'd think not. @MusikAnimal ? 
This is inspired from Enterprisey's [delsort tool](https://en.wikipedia.org/wiki/User:Enterprisey/delsort), from where the the list of delsort pages has been copied from.
=> xfd: add delsort to afd

modules/twinklexfd.js
Added in #459.  Haven't seen any reports of issues, but if we're trying to maintain support for IE 11...
=> xfd: Use indexOf instead of startsWith, the latter isn't supported in IE 11

modules/twinklefluff.js
Fixes #627.  If a user has "Do not show page content below diffs" selected in Special:Preferences, `wgRevisionId` will be set to 0 on diffs, meaning no links would be shown on diffs.  Comparing `wgRevisionId` to `wgDiffNewId` from #563 appears to be a holdover from some (local) attempts to handle merge conflicts between #511 and #407, when I initially had this structured differently, but that should now handled in the init, so this was excessive.
=> fluff: Remove overly parsimonious check for diffs, blocked links if diff content hidden

modules/twinklearv.js
Rather than showing the option, and then asking the user if they want to report themselves, and then closing (not actually letting users report themselves), the option should be hidden entirely.
=> ARV: Remove completely from user's own pages

modules/twinklefluff.js
Possibly a result from the fix in #467, but either way, this would create rollback/vandal links for every page marked with `mw-uctop`, even if it had only a single revision and thus couldn't be reverted.  The rollback links would fail (using & instead of ?) but wouldn't have been properly constructed anyway.  Check for the existence of a `href` here should remove those links.
=> fluff: don't create rollback links for single-revision pages on contribs

modules/twinklewarn.js
Setting it up this way means there is even more of a difference between the scaled levels (level2, level4im, etc.) and singlenotice/singlewarning/custom,
but doing so should make it very straightforward to remove or add templates (pursuant to any discussion in #533).
The only change to the enduser is that this will now generate a submenu category for every grouping, even if there are no templates in that group at that level.  At the moment, this is only the `4im` level for the "Removal of deletion tags" category.  I'm not sure this is a bad thing.
One header was mistmatched ('other editors' versus 'other users'), resolves that.
----
Draft for reviewing and feedback as I think this will be helpful, but I'm not sure!
- I whipped up some perl …
=> warn: Reorganize messages object, should make it more clear to maintain

modules/twinklespeedy.js
No need to write out the full url and place multiple calls to get the server and log url when a parser function does the trick.
=> Speedy: Use fullurl when linking to file logs on CSD log

modules/friendlytag.js
Add {{AfDM}} to the regex. {{AfDM}} is used by Twinkle's XFD module instead of
{{Article for deletion/dated}} when it's a 2nd/3rd/nth nomination.
=> tag: place new tags under {{AfDM}}, make \n optional in prod

modules/twinklewarn.js
Allows user to click to an editor involved in a diff and provide a warning with the article title filled-in, without having to revert the diff themself (e.g., already-reverted vandalism that went unwarned).  This has been requested a few times, and is fairly trivial.  The link is bolded, just like the user talk link on the mw rollback done page.  Clicking this talkpage link will NOT trigger the autowarn feature (#509) even if enabled (the list of && statements in the main `if` is getting quite long).
As noted in #562, `wgDiffNewId` appears to be sufficient for determining if we're on a diff, but having `wgDiffOldId` makes things clearer.
Supersedes #589
=> warn: Add vanarticle parameter to user talk links on diffs

modules/twinklebatchdelete.js, morebits.js
Trying to solve #305. Though I can't be sure whether this works without having the sysop bit.
This handles the subpages just as the redirects are being handled (they are deleted without being listed, so individual pages can't be de-selected). We may need to think about whether sysops ought to be deleting subpages without knowing anything about which are the subpages or how many of them are there (until they see the "Deleting ___" status messages). If deemed necessary, this can be tweaked to list out all the subpages along with the main pages (so that they are known to the user beforehand, and can be de-selected).
=> batchdelete: allow deletion of subpages

modules/twinklefluff.js
Closes #605.  Basically, we need a way to check for ability to edit the covers both explicit (protection) and implicit (namespace and content model) restrictions.
Since we're on the page in question, `diff` and `oldid` (#562) can be handled together with mostly-accurate results by simply checking `wgIsProbablyEditable`.  It won't handle cascading protection or TitleBlacklist restrictions, but neither does MediaWiki when choosing to display either "edit this page" or "view source"; being more accurate than the software would require an API check a la contributions (see following section as well as https://gerrit.wikimedia.org/r/c/mediawiki/core/+/65009).
`contributions` is the more <s>complex</s> interesting implementation, since we've got to check each and every page.  Querying for `edit` …
=> fluff: Only add links if the user has necessary perms to edit the page

modules/twinkleconfig.js, modules/twinklespeedy.js, twinkle.js
Closes #520 and #505.  Removes the old "open talk page" sysop option and folds the non-sysop tagging system into a unified `noteToCreator` notification system for both tagfing and deleting.  Uses the existing system for tagging to determine whether or not to notify, rather than the bespoke option for `openUserTalk` from #300; that is, it will notify only if the corresponding box is checked AND (at least one of) the CSD in question is checked in the user preferences.
The box is checked by default, unless it finds `$('#delete-reason')` on the page, indicating some sort of XfD or CSD or the like; in the latter scenario, if the box is subsequently checked, there is an additional prompt (this might be a good candidate for removal down the line, but I think it's important to include now, …
=> speedy: New option for sysops: notify creator upon deletion

modules/friendlytag.js
This is gonna be popular! Now that finding tags has become so easy (closes #621), we can add more tags to Twinkle without fear of cluttering the interface. 
Tested on IE 11. Everything works. (Though it works a bit slow on IE.)
A question to be pondered on:  When there are no search results, should the work area be empty (as is now the case), or should it show all tags?
=> tag: add quick filtering functionality

.gitignore, modules/twinklewarn.js
Add jquery.chosen on select box to make templates (and their descriptions) searchable.
Partially revert #517, bringing back the `{{uw-` prefix, as chosen's search works properly despite the presence of that prefix.
Closes #631.
Have used `mw.loader.using('jquery.chosen')` here, until `jquery.chosen` gets added to the gadget definition. 
We should probably revisit the descriptions of templates to make them include relevant keywords that attract search hits.
=> warn: use jquery.chosen on select box

modules/twinklexfd.js
Basically just copy the regex from `friendlytag.js` after #642 and #579.  This was sorely out of date, last updated in 2011: https://github.com/azatoth/twinkle/commit/c97229cda5be87957f5f2c05afff3e78f56baea5#diff-9abab93ad76ea1bab110fe90748fb6eaR455.  Certainly an unlikely occurence.
Co-authored-by: Amory Meltzer <Amorymeltzer@gmail.com>
Co-authored-by: Siddharth VP <siddharthvp@gmail.com>
=> xfd: Update regex for removing already-present AfD tags

modules/friendlytag.js
[Redirected](https://en.wikipedia.org/w/index.php?oldid=899944699#Unused_type_parameter_by_Template:Cleanup-SVG) after [merge from TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2019_April_3#Template:Cleanup-SVG)
=> tag: rm Cleanup SVG, merged with/redirected to Cleanup image

modules/friendlytag.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklexfd.js, morebits-test.js, morebits.js
1st commit: morebits: Shift lookupCreator to lookupCreation, also include timestamp
It's a free lookup and the time of creation can be useful.  Includes a notice about deprecation of `lookupCreator`, but still let's it be used.  Should probably notify any users with scripts depending on this.
2nd commit: prod: Wait three days before issuing BLPPROD alert if not in BLP cat
There was some annoyance with the alert given that BLPPORD taggings may frequently happen as part of NPP, where the category wouldn't be added.  See https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_40#BLPPROD_Issue_-_Pseudo-Improvement
Since we've added a callback to get the time of creation before tagging, we can restructure the user notification to remove that callback, essentially staying net-neutral
---- …
=> Shift morebits lookupCreator to lookupCreation, also include timestamp; use in prod to limit BLP category alert

modules/twinkleconfig.js, modules/twinklewarn.js, twinkle.js
Per discussion at [[Wikipedia_talk:Twinkle#User_warning_dialog_dropdown_selector]]
The reason some folks don't like this is because chosen makes the select menu much less denser, requiring more scrolling to get to the templates, and this also seems to give undue focus to `{{uw-` part of the templates.
=> warn: make jquery.chosen based menu optional, via-opt-out

modules/twinklewarn.js
Closes #659.  Changing selection from a `jquery.chosen` menu doesn't trigger `change_subcategory` since the event was attached to the original select.  We still need the extra `Twinkle.warn.callback.change_subcategory(e)` call from #432 to update display on simply `change_category` as well as the original, initial event in `sub_group` for users who opt-out of the new `jquery.chosen` display (#661)
=> warn: fix display of specialized input prompts

modules/twinklefluff.js
Revert hiding of links for uneditable pages on contribs (partially revert #632). 
`intestactions` is limited to 50 unique pages for most users, so this would short-circuit otherwise.  See discussion in #632.
2nd commit alerts and returns rather than attempt auto() if the page is not editable.
cc @siddharthvp and @pppery
=> Fluff partial 632 revert

modules/twinklewarn.js
Increases the density of the select menu. Use padding of 1px on search results for clarity.
@Amorymeltzer Don't know what was happening earlier, but this seems to be working fine now with `mw.util.addCSS`. Tested on multiple browsers. The jquery css solution won't work because the `li` elements are not added into DOM until the select is clicked the first time, so the jquery selection is of 0 length. 
If this is working for you too, can you deploy this live immediately, so that people can try it out (and probably change their opinion about the new interface😎) ?
=> warn: remove padding from chosen's li elements

modules/twinklewarn.js, modules/twinklexfd.js
Removes the need to set a max-height to it. Also enables more templates to be viewed without having to scroll.
Code credits: https://github.com/harvesthq/chosen/issues/1390#issuecomment-21397245
Would have added this to #662 hadn't it been merged by now.
=> warn/xfd: force chosen select menu to display over the dialog; padding fix in xfd

modules/twinklewarn.js
To match the height of the native select menu. 
Just this one more. Exact same number of templates will now be displayed as the earlier select menu did. This aims at making the transition to the new menu as smooth as possible. Now the reasons why anyone would dislike the new menu are almost null.
=> warn: increase height of chosen select

modules/twinklewarn.js, modules/twinklexfd.js
- Fix typo (mising `max-`) from #664
- Extend the dialog to encompass the full preview box (https://github.com/azatoth/twinkle/issues/665#issuecomment-499905637)
- Hide the resize handles to prevent visual incongruities (https://github.com/azatoth/twinkle/issues/665#issuecomment-500230270)
- Don't overlay chosen menu in xfd
@siddharthvp I think this covers the fixes we've (you've) come up with lately, and leaves us at a presentable, stable situation.
=> warn/xfd: a few fixes for chosen css

modules/twinkleprotect.js
Can't be protected or unprotected (neither can gadget / gadget description pages, but those are blocked by the title blacklist) - doesn't need to be shown.
=> Protect: Hide on mediawiki pages

modules/twinklebatchprotect.js
Form changed May 2018 in https://phabricator.wikimedia.org/T117726 as part of 1.32.0-wmf.5.  Inserting `.firstChild` would also have worked.
=> batchprotect: Fix bug from OOUI-ification of Special:PrefixIndex

morebits.js
`replace` doesn't touch the original string, so this line has done nothing for years: https://github.com/azatoth/twinkle/blob/71267fd4f1a0057c01ddc9ec5eb8ea40cf2a75be/morebits.js#L1937
As an example, using the form on Special:PrefixIndex creates urls like `https://test.wikipedia.org/wiki/Special:PrefixIndex?prefix=Articles+for+deletion%2F&namespace=4`, on which `twinklebatchdelete` would open empty, seeing no pages starting with *Articles+for+deletion*
=> morebits: replace + in Morebits.queryString (fix longstanding bug)

modules/twinklewarn.js
The comma in the `HH:MM, DD Month YYYY` regex leads to this being parsed as an invalid date.  This has been unchanged since its inception in 2007, did this ever work?  This was masking a bug with the user-aborted warnings.
I'm tried running down how timestamps and signatures are created in mediawiki, I've read far too much of the ECMAScript language specifications, and I've spent a lot of time in various languages, but I still feel like I'm missing something obvious.
=> warn: Fix decade-old bug in regex parsing sig timestamps

modules/twinklespeedy.js
- G8 for redirects tightened to only apply to target non-existent targets <https://en.wikipedia.org/w/index.php?oldid=902425211#Tightening_G8_with_respect_to_redirects>
- G14 expanded to include "Foo (disambiguation)" redirects targeting pages that aren't disambiguation-ish <https://en.wikipedia.org/w/index.php?oldid=902639054#Deletion_of_redundant_(disambiguation)_redirects>
=> speedy: Update descriptions of G8 and G14

modules/friendlytag.js
Now that the interface supports search, clutter is no longer a reason for removing templates.
Adding back {{dead end}} was requested [here](https://en.wikipedia.org/wiki/Wt:Twinkle/Archive_41#{{Dead_end}}_has_disappeared). Also adding {{sources exist}}, requested [here](https://en.wikipedia.org/wiki/Wt:Twinkle/Archive_39#Can_we_please_add_the_{{Sources_exist}}_Tag?)
=> tag: re-add {{dead end}}, add {{sources exist}} per requests

modules/friendlytag.js
This makes the tags get placed below the hatnotes on pages where {{short description}} is present at the top.
Bug was reported at [TW talk page](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Bug:_Failure_to_place_maintenance_tags_below_hatnotes_when_there's_also_a_short_description_template).
=> tag: add {{short description}} to hatnotes regex

modules/twinklewarn.js
As [suggested on wiki](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=909964659&oldid=909865323), tweak warning edit summary for using multiple IPs to edit
=> Tweak warning edit summary

morebits.js
Regex s flag appears to be resulting in an exception in IE 11 and legacy browsers. I have used [\s\S]*? instead of it so that newlines get matched. Eslint doesn't like this syntax for whatever reason, though this usage seems to be fine and is suggested online. 
While at some point (after making the commit) it came to my attention that the regex s flag is not supported in IE 11 and the like, I did not realise that it would cause an exception - I thought that these browsers would just ignore the flag. I was working in Ubuntu and so did not have IE handily available to test on.
=> morebits: enable multiline unbinder

modules/twinklespeedy.js
G14 also applies to redirects per discussion at https://en.wikipedia.org/wiki/Wikipedia_talk:Criteria_for_speedy_deletion/Archive_74#Modified_proposal (and see https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#G14_speedy_deletion_criterion_(add_for_redirects?) )
=> Show G14 on redirects

modules/twinklespeedy.js
Per request at [TW talk page](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Request_to_include_discussion_page_in_automatic_G4_notice).
Also improved the conditional statement for checking that the page given is in project namespace.
=> speedy: include xfd page name as parameter in db-repost-notice

modules/twinklespeedy.js
- Added to Twinkle with hideWhenMultiple March 2011: https://github.com/azatoth/twinkle/commit/f56b4a54c9a31bdf56c72e461486b8ce9bce50cf
- Supported in notice template as of June 2012 rewrite: https://en.wikipedia.org/w/index.php?title=Template:Db-notice-multiple&diff=496436903&oldid=418576312
- Supported in Template:Db-multiple/item as of June 2018 rewrite: https://en.wikipedia.org/w/index.php?title=Template:Db-multiple/item&diff=845605071&oldid=845604422
- Named criteria support as of March 2019: https://en.wikipedia.org/w/index.php?title=Template:Db-multiple&diff=prev&oldid=887125742
=> speedy: Allow P1 when multiple

modules/friendlytag.js
Closes #690.  [TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2019_April_5#Template:Globalize) closed with consensus to do away with all the various region-specific subpages, massively simplifying things.  Specific entries are handled by Template:Globalize/name, so it should be sufficient for us to just offer an input box and let the template(s) sort it out.
----
See also https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Holding_cell#Meta
=> tag: Update globalize template following TfD

morebits.js
- remove `Date.monthNames` and `Date.monthNamesAbbrev` in favour of mw.config objects `wgMonthNames` and `wgMonthNamesShort`, which work across wikis and languages. A difference is that they are indexed from 0-11 while the config objects are indexed 1-12. These are unused except from `Date.prototype.getUTCMonthName`/ `Date.prototype.getUTCMonthNameAbrev`. 
- remove `Date.prototype.getMonthName` and `Date.prototype.getMonthNameAbbrev` as they are completely unused - not used in Twinkle or any other Morebits-based gadget/script. See searches [1](https://en.wikipedia.org/w/index.php?search=insource%3A%2FgetMonthNameAbbrev%2F&title=Special%3ASearch&profile=advanced&fulltext=1&advancedSearch-current=%7B%7D&ns0=1&ns1=1&ns2=1&ns3=1&ns4=1&ns5=1&ns6=1&ns7=1&ns8=1&ns9=1&ns10=1&ns11=1&ns12=1&ns13=1&n …
=> morebits: internationalize Date, and remove unused functions

modules/twinklebatchprotect.js
Match behavior in `batchdelete` and `batchundelete`, the latter as of a1474279
=> batchprotect: Add red color and confirmations for fully protected pages

README.md, modules/friendlytag.js, modules/twinklewarn.js, morebits.js
See [T218339](https://phabricator.wikimedia.org/T218339); `mw.RegExp` has been deprecated and will be removed in MW-1.35, as the `escape` function was the only item in it (itself from a prior module).  The same function (different name) has since 2015 been already present in `mw.util`.
----
Tidied up from #708, cc @siddharthvp
=> Convert mw.RegExp.escape to mw.util.escapeRegExp as the former is being deprecated

morebits.js
We need to migrate our token usage properly (#615, noted in #616) but one simple step is moving from `mw.user.tokens.get('editToken')` to `mw.user.tokens.get('csrfToken')`.  Using `csrfToken` in favor of `editToken` was done back in 2015/2016 with the move away from `action=tokens` to `meta=tokens`.  Both `editToken` and `csrfToken` have been provided in the `mw.user.tokens` object for quite some time, and the former is finally being deprecated (see [T233442](https://phabricator.wikimedia.org/T233442)).  The presence of the `edittoken` attribute in xml responses is unchanged.
=> morebits: Use csrfToken in mw.user.tokens

modules/friendlytag.js
As reported at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=918480329#Merge_tags), Twinkle has been leaving `{{merge}}` on the other page when tagging with `{{merge to}}` or `{{merge from}}` (rather than `{{merge from}}` or `{{merge to}}`, respectively).
Stems from #485, where somewhere along the way the addition in [L1274](https://github.com/azatoth/twinkle/pull/485/commits/95eac797ab3b22d8bd63ecadc8fba8db226051ee#diff-03744d176dfd1e8a2178545886a87644R1606) at 95eac79 was removed but `params.mergeTag` remained.
I've added the line back when validating the various merge tags, since we're already evaluating them all.
\*cries in `.includes()`\*
=> tag: Fix regression leaving generic {{merge}} instead of {{merge to}} or {{merge from}}

modules/friendlytag.js
- Prevent enter key from submitting form
- Disable browser input suggestions
The latter is annoying. The suggestions sometimes obscure search results. This setting is there by default in chosen's search inputs.
=> tag: quick filter: minor changes

modules/friendlytag.js
[Requested at WT:TW](https://en.wikipedia.org/wiki/Special:Permalink/918911925#Merge_tags).  No reason not to match the edit summary, where we already did this, so let's just use the same language for everybody.
=> tag: Indicate direction of merge in talk page notification header

modules/friendlytag.js
Discussed/requested at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=919009709#Feature_request:_exclude_Current_event_from_multiple_issues), seems reasonable.  `{{Current}}` was added in #416.
Doesn't address the related discussion on whether to undo #416 (see also [discussion at TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2017_April_20#Template:Recentism) on usage).
=> tag: Don't place {{current}} in MI

README.md, morebits-test.js, morebits.js
See https://phabricator.wikimedia.org/T219604#5374960 and subsequent patches (e.g. https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/543736/)
Rearranging deck chairs before #414/https://phabricator.wikimedia.org/T49145
----
Assuming the train goes out on the 24th as planned, I'll merge this then.  Won't break anything not do so, just another console warning (*cough #384 cough*)
=> jquery.ui.dialog (and others) being moved within jquery.ui

morebits.js
Apply classes, styles and id on the input/textarea rather than the container div, as this is more desirable in most situations. 
For input fields, fix the ancient bug that caused the container and the input field to get the same id; and enable support for custom id.
For textarea, nest a `<label>` within the h5, as requested in source TODO. This causes no visible changes AFAICT, other than that clicking on the label now will put cursor in the textarea.
=> morebits: quickform input and textarea improvements

morebits.js
Restores custom message removed in #707.  Custom messages as specified in MediaWiki:Spamprotectiontext and MediaWiki:Spamprotectionmatch get inserted into the response, which can lead to absurdly lengthy wikitext messages in Twinkle (see https://github.com/azatoth/twinkle/pull/707#issuecomment-539120184).
=> morebits: Use custom message for spamblacklist

modules/twinkleprod.js
First commit: fix bug reported on [Twinkle talk](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Article_PRODed_twice). 
2nd commit: remove redirected/deleted templates from the list. Also, the old drv templates were missing the "Template:" prefix, due to which they weren't working.
=> prod: old prod/xfd detection bug fix

morebits.js
Improve handling of token errors in `morebits.wiki.page`'s `save`, `deletePage` and `undeletePage`. 
I believe the 3rd commit fixes the probably decade-old bug (oh, again!) described [here](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_40#Twinkle_broken?). 
Though I am not sure whether these changes really work, as there's no easy way to test them.
=> morebits: fix handling of invalid token errors

modules/twinkleprod.js, modules/twinklexfd.js, morebits.js
I have tweaked Morebits.wiki.page.prototype.lookupCreation so that an option is now available which if set, the function would return the username/timestamp of the creation of the first non-redirect version of the article. 
I have then put this into use for AFD and PROD notifications, since in these cases we unambiguously want to notify the real article creator rather than the redirect creator. We should perhaps also try to incorporate this somehow to CSD, but I guess that it's a bit trickier. 
I guess this is long-requested feature, and should be very helpful to the project as now people who create articles from redirects would not remain in the dark when their work is sent to the gallows. Also, this should help us crush the upcoming competition from PageCuration!
=> Correctly notify the creator of article, if it began as a redirect

modules/twinklexfd.js
Requested at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=918184797&oldid=prev).  AFAICT it has no effects if the page isn't transcluded, so I don't think there's any harm in putting it in for every RfD tag, but it's non-standard and not (yet) documented at Template:rfd so probably best to leave it off if not necessary.
=> xfd: Add showontransclusion=1 to templatespace rfd noms

modules/friendlytag.js
The same quick filter line is called for each mode, but by putting it before the `switch (Twinkle.tag.mode)`, the quick filter will appear above the article sorting toggle, which should make more sense given its usefulness.  Also move the patrol checkbox to the bottom, near where the MI box would show up; birds of a feather and all that.
----
This occurred to me right after merging @siddharthvp's excellent changes in #724.  There's no need for `Window.setTitle` to be first, and the only other noticeable change is if the `switch` input is entirely broken, wherein the phantom Twinkle window would now have a quickfilter instead of being totally empty; not exactly a deal-breaker.
=> tag: Move quick filter up, move patrol checkbox to bottom

modules/twinklearv.js
Since 2013 (70cc516f), we've attempted to show up to 500 edits made within the last 36 hours.  In actuality, we've been showing up to 500 edits made since 12 noon on two calendar days prior.  `.setHours` changes the hours *digit*, and while it doesn't do math it is smart enough to try to count backward for negative numbers.  `date.setHours(0)` changes the hours digit to 0, so 13:42 on the 17th would become 0:42 on the 17th; doing `date.setHours(-1)` will count back from 0, becoming 23:42 on the *16th*.
What we've really been doing for 6.5 years is showing edits within anything from 36 to 59 hours, depending on the local time when the user loaded the edits.  As such, I've changed the time frame to encompass 48 hours, since that's roughly approximate to actual current practice.
=> arv: Fix bug in hours calculation in AN3 reporting

modules/twinklexfd.js
Adds the ability to start an RM discussion on the talk page, and to list uncontroversial requests at [WP:RM/TR](https://en.wikipedia.org/wiki/WP:RM/TR).
Closes #644.
While this is admittedly not a best fit in XFD module as it is not an XFD board, it is great to have this feature somewhere in Twinkle. This provides an easy interface to access the RM process, as users now no longer need to remember the usage of the templates involved. Also, this would probably help new editors to discover the RM process sooner.
=> xfd: add support for RM

modules/twinklebatchprotect.js
Missed in 1539f511 (cf. f7008119 (batchdelete), 8d4a8e65 (batchundelete), and 2aae77d1 (unlink))
=> twinklebatchprotect: Add support for shift-clicking checkboxes

CONTRIBUTING.md, DEVELOPER.md, README.md, package.json
Hopefully helpful for new users who want to know how to get involved or report bugs, and should lead to some level of continuity.  Most of the content has been moved and expanded from what was originally in the README.md.  Still largely a WIP, especially as concerns developer/maintainer/collaborator instructions.
Some potential references for further expansion:
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/jaywcjlove/awesome-mac/blob/master/contributing.md
- https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md
- https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
- https://github.com/zendframework/maintainers/blob/master/MAINTAINERS.md
Closes #477 
----
cc @azatoth @MusikAnimal @atlight @kevinji @UncleDouggie @ioeth and also …
=> docs: Add CONTRIBUTING.md and DEVELOPER.md

modules/friendlytag.js
Some redirect tags (e.g. {{R from alternative language}}) can take parameters (e.g. "|from=de|to=fr"), which would cause the regex to fail to match the entire pagetext.  Specifically, in:
(?:[^|{}]*|{{[^}]*}})+
the
{{[^}]*}}
portion matches individual redirect templates, and removing the pipe from [^|}] allows the content of that template to contain parameters.
Previously, the tag module would just fail, and the regex might just insert new tags in the middle of already-existing templates.
Not sure what the case theoretically was where not excluding a pipe here would cause an issue.
=> tag: Fix bug in redirect tag matching

modules/friendlytag.js
If there are no available tags (all are already present or none provided) the module would die when trying to untag (like a printer low on cyan).  This is incredibly unlikely on enwiki, but I can theoretically imagine other wikis with fewer maintenance templates might run into an issue where all available templates are already transcluded.  Reported [on my testwiki talk](https://test.wikipedia.org/w/index.php?title=User_talk:Amorymeltzer&oldid=405366).
----
I spent some time delving into other tightenings when the various tag objects were empty or emptied, but it's only partially doable without some major restructuring, and I'm not sure it's even a good idea.
=> tag: fix bug when there are no available tags

modules/twinklexfd.js
Added in 9d6818a along with CfD/S, presumably intended to allow the user to return to their previous state after "visiting" CfD/S.
Current behavior: Changing modes (e.g. AfD->TfD) resets the state of the "Notify page creator" checkbox, so that after loading a new XfD venue, it is always checked, unless switching to CfD/S, where the box is unchecked (and disabled).  If switching *away* from CfD/S, the default state of the checkbox will be set to whatever the checkbox was before moving to CfD/S; that is, if the checkbox was *unchecked* in AfD mode, then the user switched to CfD/S, every subsequent switch would uncheck the box, until of course they return CfD/S.
This commit: Does away with the whole damn thing, just sets the box unchecked (and disabled) for CfD/S and RM, and checked for …
=> xfd: Fix bug in notification checkbox when changing modes

modules/friendlytalkback.js, modules/twinklearv.js, modules/twinkleblock.js, twinkle-pagestyles.css, twinkle.js
Allows users to use Twinkle modules there if desired.  As of now, it loads: arv, warn, welcome, and talkback, as well as block if the user is a sysop.
Also updated/unified headers describing where some modules that use `wgRelevantUserName` that weren't changed (#208).
----
IMO this solves the concern expressed in #699.
=> twinkle.js: Add Special:Block to whitelisted special pages

modules/twinklearv.js
Don't think we should do the same for UAA, as those reports are of a very different nature than the AIV reports.
Closes #542.
=> arv: Check for bot reports at AIV, ask user to confirm report

modules/twinklexfd.js
If a deletion sorting page were moved, Twinkle wouldn't follow the redirect, and would just quietly fail.  As reported [at TW](https://en.wikipedia.org/wiki/Special:Permalink/927686404#Deletion_sort_issue), this [did actually happen](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Deletion_sorting/Science_fiction&diff=prev&oldid=917763420).
----
I'm going to merge this live as a quick fix.
=> xfd: Follow redirects to delsort pages

DEVELOPER.md
The full list of selectors being deprecated is at https://blog.jquery.com/2019/04/10/jquery-3-4-0-released/ but they are `:first`, `:last`, `:eq`, `:even`, `:odd`, `:lt`, `:gt`, and `:nth`.  These were officially deprectated as of jQuery 3.4, and the MediaWiki jQuery 3.3.1 -> 3.4.1 update is slated for MW-1.35-wmf.8 (see [T233027](https://phabricator.wikimedia.org/T233027)).  Twinkle doesn't appear to currently use any of these, but we have in the past (e.g. a4b47de) and probably shouldn't reintroduce them.  Others, like `:first-child` or `:last-child`, remain (for now?), and of course the corresponding methods (e.g. `.first()` or `.eq()`) may be used.
=> docs: Note deprecation of certain jQuery positional selectors

modules/twinkleprod.js
The removed part really isn't needed since it's clear that the edit is being made to the talk page.
=> prod: trim talk page edit summary

modules/twinkleconfig.js, morebits.js, twinkle.js
JavaScript no longer loads in MediaWiki in IE <11, so there's no point in keeping old IE version checks or special cases.
=> twinkle/morebits/config: remove antique IE 9 stuff

modules/twinkleconfig.js
Since legacy-styled preferences are stored in a global TwinkleConfig (or FriendlyConfig) object, we can detect them without having to load and parse the skin.js file. This method also detects such preferences from the common.js file, which weren't being detected till now. Additionally, this also ignores any commented out code in js pages which would have erroneously flagged by the previous method.
<hr>
A rare pull request for the config module, which otherwise has been written so excellently by @atlight that it has barely needed any changes in eons.
=> config: improve detection of legacy-style preferences

modules/twinkleprotect.js
Where available, content returned by the API should always be used rather than mw config data as it is more up-to-date.
Fixes the bug reported on [WT:TW](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Adding_protection_templates_on_redirects_breaks_the_redirect).
=> protect: use API text output to check if page is redirect

modules/twinklewarn.js
The [ancient](https://en.wikipedia.org/w/index.php?title=User%3AAzaToth%2Ftwinklewarn.js&diff=prev&oldid=138028399) check for the latest warning template present has held up pretty well (excepting #676), but if it finds multiple warnings given within the same minute - wikitext signatures don't have second-level specificity - it will choose the first one.  We should instead prefer the last one, as it's more likely to have been placed *after* its higher-up siblings.
=> warn: Prefer bottom warning for latest if dates are the same

.eslintrc.json, morebits-test.js
https://eslint.org/docs/rules/dot-notation
Best practices, fixable
----
Noted at https://github.com/azatoth/twinkle/pull/773#discussion_r352202964 that we legitimately don't use this *anywhere*, so given that we have a clear house style, might as well enforce it, especially since it's automatically fixable.
=> eslint: Enforce dot-notation

modules/twinklespeedy.js
Some of these had their wording changed on-wiki, some could just be more helpfully worded.  Hopefully an improvement.  See also #337.
=> speedy: Tweak descriptions of items to more closely match WP:CSD

modules/friendlytalkback.js
This makes the this part of the module more amenable to localization. Causes no user-facing effects.
+2 other minor commits.
=> talkback: move configurable noticeboard-related data into an object

modules/twinklearv.js
I'd be in favor of reordering the AIV checkboxes so VAO and promoonly are together and spambot is last, but not sure if that'd throw people off their game
=> arv: Disable UAA and promo-only for IPs

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, twinkle.js
- Unify the Twinkle.defaultConfig.twinkle and Twinkle.defaultConfig.friendly to Twinkle.defaultConfig.
- Twinkle.getPref() can now retrieve friendly preferences also. Twinkle.getFriendlyPref() is removed.
- Now onwards, changes to WP:TWPREFS will save the preferences in twinkleoptions.js without separating them between twinkle and friendly. But the old format will still be acceptable.
A single config object is easier to work with, and would be helpful as far as i18n/l10n is concerned. This also simplifies a lot of code in twinkleconfig.
=> Unify twinkleconfig and friendlyconfig

morebits.js
In fnProcessMove, remove the comment `XXX don't know whether this works for non-admins` after logic handling query.movesubpages - if the user cannot move subpages, this is enforced by the mediawiki api (https://gerrit.wikimedia.org/g/mediawiki/core/+/e398253aba0652afcf2a6eeb9fdb67e0a4ef8f0a/includes/api/ApiMove.php#210) and some non-admins (page movers) do indeed have the ability to move subpages.
=> Morebits: Remove old outdated comment

modules/friendlywelcome.js
Tweaked the structure of `Twinkle.welcome.templates` so that it contains all the information regarding what templates are to shown under what headers, and in which modes. This makes i18n/l10n lot easier as now only this object needs to redefined for different wikis (apart from the translation of strings). Also this makes maintenance easier as the only code change needed is in this object while adding/removing templates. This causes no user-facing effects. 
Also, I've removed all uses of `linkedArticle: false`, as the property needs to be specified only if the value is true.
=> welcome: put all template and grouping data in a single object

modules/twinkleblock.js
Changed "famous" to "well-known" per feedback on wiki. 
[Wikipedia talk:Twinkle#minor tweak to block reasons](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=930936807#minor_tweak_to_block_reasons)
=> block: Update {{uw-ublock-famous}} reason label

modules/twinklewarn.js
[Reported at WT:TW](http://en.wikipedia.org/wiki/Special:Permalink/931480269#uw-inline-el)
----
Opened as draft in case it's reverted/further changed.
=> warn: renamed uw-inline-el to uw-elinbody

modules/twinklewarn.js
The tone of [{{uw-wrongsummary}}](https://en.wikipedia.org/wiki/Template:Uw-wrongsummary) is much more of a notice than a warning.  It has been in Twinkle's list since [its inception](https://en.wikipedia.org/w/index.php?title=User%3AAzaToth%2Ftwinklewarn.js&diff=prev&oldid=162345357) but in 2012 was moved on the [WP:SLT lists](https://en.wikipedia.org/w/index.php?title=Wikipedia:Template_messages/User_talk_namespace/Single-level_templates&diff=496637706&oldid=496636956).
----
This should probably be discussed at WT:TW beforehand, as it might annoy folks who expect it to be in one place, although that should be mitigated by #759.  We're not in sync with that list (nor should we be necessarily) but this is the most glaring error AFAICT (another is agf-sock, but I think that belongs as a …
=> warn: Move uw-wrongsummary from warning to notice list

modules/twinkleconfig.js, modules/twinklewarn.js, twinkle.js
Uses a new config option, `combinedSingletMenus`, turned off by default.  The combined menu is sorted alphabetically.
Closes #673.
=> warn: Add option to show the single-notice messages in a single menu

modules/twinkleblock.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
Largely addresses #6. Per https://github.com/azatoth/twinkle/issues/6#issuecomment-1304315, the server time is available to us whenever we are in a `.load()` callback, via the starttimestamp attribute in load API output which is stored in Morebits.wiki.page as `ctx.loadTime`, publicly exposed via `.getLoadTime()`.
In case of RFD, the curtimestamp parameter is added to the API request while finding the target of the redirect, so that the server time is available while determining the log page.
The only remaining usages of client clock is in:
- an3 - not important to fix as it is only used for deciding what revisions to retrieve from which user can select reverts.
- in determining daily log page name for CFD, FFD and TFD. The code that does is sitting outside of any load callback, because …
=> Use server time rather than client time wherever possible 

modules/friendlytalkback.js
1st commit: Template:No_talkback creates a link to `http://userjs.invalid/noTalkback?reason=`; that gets used by the talkback module to provide a custom reason to the user, but by using `.append`, it allows someone to provide and run code via `<script>`.  Changing to `.text` does away with that.  See phab:T241950.
In the future, there are other options here, such as querying `templates` (removes the ability for editors to provide a custom `reason`), querying `revisions` (regex to match page the content), or simple removing the ability to provide custom text.
2nd commit: Always check the talkpage for optout.  Also don't append a . if user provides a custom reason, allow them to pick their punctuation
=> talkback: Don't parse html, always check user talk page for optout

modules/twinkleconfig.js, modules/twinklewarn.js
Mentioned in https://github.com/azatoth/twinkle/issues/673#issuecomment-501858213.  While this makes use of 10 for `defaultWarningGroup`, I considered reusing 8, which was until the addition of the block module in #260 (well, also 430e2258) reserved for sysops to select blocking templates, to cut down on bloat.  There are a handful of users, some still active sysops, with the option set, but while that's a trivial barrier, I think it's better list it below the individual items, reinforcing the "all-of-the-above"-ness of the option.
This also tweaks the process by which `twinklewarn` tries to select the template that corresponds to what was selected in the previous menu.  As it has every item, the new kitchensink menu should always match exactly, but since the process was previously only …
=> warn: Add option to show a list with all template warnings

morebits.js
1st commit: doc fixes.
2nd commit: execute `postFinish()` even when the `pageList` is empty. This situation could occur when the pageList used is variable.
3rd commit: allow individual status lines even if the `worker` function is not using `Morebits.wiki.page` or `Morebits.wiki.api`.
These will not have any effect on Twinkle.
=> morebits: batchOperation: minor improvements

twinkle.js
Don't ignore falsy preference values (eg. '', false, 0).
Closes #799.
=> twinkle: fix bug from #762

morebits.js
Misplaced return statement. The `return` should have been within the `if` per #804. Closes #804.
Also ensure that the username and timestamp given are both of the same edit.
=> morebits: fix two bugs in lookupCreation for redirects (from #710)

CONTRIBUTING.md, modules/twinklefluff.js, twinkle.js
`twinklefluff.js` and `twinkleconfig.js` are the only modules that are loaded via `Twinkle.module.init` rather than `Twinkle.module`.  This was sort of @atlight's work in 2c544c1 but goes all the way back to @UncleDouggie's restructuring in a79b7d9.  These are the only two modules that aren't added to a menu/tab and are instead just run, so something different did make sense.  Still, I don't see a reason for `Twinkle.fluff()` to be different from the other tool-based modules: it may not "add menu button" but it does "enable the module."  I'm fine with config being different since it's clearly very different in scope.
Oh, and we can't use `Object.assign` because IE.
----
Putting this live on testwiki for testing, especially since the diff is annoying.
=> fluff: Restructure fluff to use Twinkle.fluff() instead of Twinkle.fluff.init()

modules/twinkleconfig.js, twinkle.js
Was discussed in #762 but not done there.  The format has been pretty stable before the unification (occasional new options aside) so this is reasonable as a marker.
----
The intent here (see https://github.com/azatoth/twinkle/pull/762#issuecomment-566443649 and https://github.com/azatoth/twinkle/pull/762#issuecomment-566486414) is to just mark current preferences going forward.  Is this all there really is to it?  cc @siddharthvp (also @atlight and @MusikAnimal in case you're curious)
=> config: Add optionsVersion 2 to preferences now that they're unified

modules/twinklespeedy.js
Creation protection can be requested via checkbox. Not available when sysop is in sysop mode (though a future task could allow setting creation protection while deleting)
=> Speedy: Allow users to request salting

morebits.js
This partially reverts commit 28d50ac from #635, restoring the hardcoded values for `Date.monthNames` and `Date.monthNamesAbbrev` while `Date.prototype.getMonthName` and `Date.prototype.getMonthNameAbbrev` remain removed (unused outside of ko.wiki).
Done in advance of [phab:T219340](phabricator.wikimedia.org/T219340); see discussion in #723, including #723 (comment) and #723 (comment).
As noted there, this is not the ideal situation, but it's simple, covers our current needs, and except for the last four months, was the norm for *years*.
cc @MusikAnimal @siddharthvp @Krinkle
=> Partially revert "morebits: internationalize Date, and remove unused functions"

modules/twinklewarn.js
<s>This is something that Huggle already does, with a [limit of 1 day](https://github.com/huggle/huggle3-qt-lx/blob/f44d4f7ea0f7b83fb16e4d14e9bedf3c18b09f15/src/huggle_core/warnings.cpp#L73) for the alert.  24 hours is also the window in which Twinkle warns users that they are attempting to provide an identical warning to one already present, so the parallel "staleness" is nice.
We can do this by adding a `vantimestamp` parameter to the user warning links opened by `twinklefluff` and merely checks that against the current date when issuing a warning to an editor.  I've also added it to the additional parameters we tack onto the user talkpage links on diffs; <s>doing so requires parsing the text of the "revision as of" text, since of the four formats users can select in …
=> warn: Note if user attempting to warn for an old edit 

modules/twinkleblock.js, modules/twinkleconfig.js, twinkle.js
Would close #802, but this is still a WIP, mostly because I've been swamped in RL.  I think/hope most of the work remaining is CSS and language tweaks, so I wanted to get this up for folks (you originally wrote this, @MusikAnimal, so lookin' at you) to test and/or look over.
There are some (as yet) unorganized notes in the commit message, but this makes use of select2.  Like #692, however, that means this is held up by my gadget issues in #812 (see https://github.com/azatoth/twinkle/pull/812#issuecomment-576024668 and https://github.com/azatoth/twinkle/pull/812#issuecomment-576848165).  In the mean time, you can test it by first entering in the console:
>mw.loader.load('https://tools-static.wmflabs.org/cdnjs/ajax/libs/select2/4.0.12/js/select2.min.js'); …
=> block: Add support for partial blocks

modules/twinkleblock.js
Probably should have been included to begin with in #813.
Also link to [[WP:Namespace]], although I'm not sure if that's particularly helpful.
=> block: Link pages in partial block template

modules/twinklespeedy.js
A sysop toggling modes would lose the default unchecked-if-csd-present status
=> speedy: Fix bug affecting checking of warnuser when toggling modes

modules/twinkleblock.js, morebits.js
quickForm `select` elements didn't get a `disabled` option way back in 2007, and clearly we haven't wanted it, but I don't see a good reason why not to allow it?
Second commit applies this to the preset menu for partial blocks, as it currently only has one option, so need not be available/tempting.  Can't do the same for the template menu since `serializeArrays` will skip over anything disabled, and I don't think it's important enough to justify reworking that whole bit (although increasingly, with the multi-select input for PBs, it's now got a few holes).
Minimally tested 'cause sick.
=> Allow quickForm select elements to be disabled in morebits, apply to the partialblock preset menu

modules/twinkleblock.js
edit warring (ewpblock), account creation (acpblock), and emailing (epblock), plus a generic indef option (pblockindef)
Most of these made by or with consultation with @QEDK, but opened as draft since I think it'd be good to get further input on the language, timing, and other options.
=> block: Add additional partial blocking templates

modules/friendlytag.js
Solves bug reported on [TW talk](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Automated_%22merge_from%22) - the talk page section title used in the template's discuss link should match the one actually produced. 
Also, adjusted the edit summary to be a section link to the discussion (kinda fake section=new API action). This seems to be a better alternative that no thought of in #717 where we discussed it earlier, @Amorymeltzer.
The only bug left is that TW unnecessarily adds `\n\n` (visible extra whitespace) if the talk page was empty (also there in some other modules - talkback I think). But I think there's no easy fix short of adding `section=new` support into morebits, or not adding `\n\n` at all (leads to untidy wikicode on non-new pages).
The 2nd commit does away with …
=>  tag: fix broken discussion links in merge tags

modules/twinklewarn.js
[Reported at WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=939908648#Apparent_(rather_minor)_Twinkle_bug).  Basically, when #773 added the kitchensink menu, I didn't account for the fact that the edit summary test was relying on the `main_group` to have a number in it, which fails with kitchensink.  For kitchensink, then, we rely on the `sub_group` via `substr`, as with custom; similarly, it's over-complicated because of 4im levels.  Also worth noting that `uw-3rr` is a non-level1-4im with a digit in it.
=> warn: Fix bug with kitchensink edit summaries

modules/twinklexfd.js
Onwiki comment updated in [1], per discussion at [2]; the current value results in the request being placed in the `Requests to revert undiscussed moves` section instead of the intended `Uncontroversial technical requests` section[3]
[1] Diff: https://w.wiki/GtM
[2] Discussion: https://w.wiki/GtN (permalink to current: https://w.wiki/GtP)
[3] Diff: https://w.wiki/GtQ
=> xfd: Update technical RM hidden comment

modules/twinklespeedy.js
The original model of the CSD module (71267fd) had all the checkboxes on one form, so it would toggle checkboxes checked/unchecked and enabled/disabled when changing modes.  They have slowly been built up over the years (some examples at fc4ac5a, 019ccc7, and #177 (a04f034)), but with #312 (bbed86a, mid-2016), `twinklespeedy` moved to using separate forms for "tag" and "delete" modes.  Since then, changing modes as meant the former mode's checkboxes are no longer visible, and thus should not need their disabled status to be toggled in addition to checked/unchecked.  This should remove a fair bit of confusion when adding/adjusting options.
Minimally tested since sick.
=> speedy: Remove unnecessary checkbox disabling code

modules/friendlytag.js
Inspired by #838, adds a few of the most popular ones (a mostly-subjective smattering based on transclusion count and perceived-utility), using a [script](https://github.com/Amorymeltzer/wiki/blob/master/tagCleanup/redirtagUsage.pl) similar to the one in [#178](https://github.com/azatoth/twinkle/issues/178#issuecomment-474012574).
I'll open an issue/PR to discuss these more broadly, in particular being more inclusive and improving our categorization, especially after #724, but for now this should plug a few holes.
=> tag: Add some common/popular redirect tags

modules/twinklefluff.js, modules/twinklewarn.js
`fluff` is already processing diffs, so this saves `warn` from checking anything on diffs.  Plus, this takes advantage of the already in-place handling of the revision slider hook (#407) so that these `extraParams` are also added to user talk links when the revision slider is updated.
Second commit just consolidates some duplicated code in `fluff`
=> warn/fluff: Move code adding extraparams to user talk from warn to fluff

modules/twinkleconfig.js
`Twinkle.config.commonEnums.watchlist` renamed to `Twinkle.config.watchlistEnums` while `commonEnums.talkPageMode` is just moved to its specific location.  Only `commonEnums.watchlist` was actually "common" in `config`; `commonEnums.talkPageMode` was only used once.  This likely stems from fead344 where it was used twice and consolidated just prior to the `twinkleconfig` system being created in 846b727, and never got used again.
=> config: change commonEnums object to just contain the watchlist object

twinkle.js
wgRelevantUserName is defined on Special:Block, so it's theoretically useful for everyone (warn, tb, etc.)
=> twinkle.js: Only load on sysop-only special pages for sysops

modules/twinklexfd.js, morebits.js
1. Adds the `required` attribute to `input` and `textarea` `quickForm` elements in `Morebits`
1. Uses that to require users to enter an input for TfM, CfM/CfR/CfS/CfC (i.e. WP:CFD but not deletion), and all CfDS.
1. Adds the `action` parameter to the {{cfd-notify}} template, and uses that language a bit more throughout
I opened this as a draft pending a response to my [question at WT:CFD](https://en.wikipedia.org/wiki/Wikipedia_talk:Categories_for_discussion#Should_Twinkle_require_nominators_to_input_new/other_category_names?) about point 2 above: I think it's a good idea, but I could theoretically imagine that some folks at CfD like being able to make nominations without the target specified.
=> xfd: Make target required for tfm/cfd/cfds, and specify action in cfd-notify

modules/twinklexfd.js
1. Since #741 (specifically, 3e21765), RfD was using a returned `curtimestamp` to generate the log page.  That query was only being done if the page wasn't a soft redirect, however, leading to NaN/undefined issues.  Closes #861 by falling back to the previous client clock method.
2. #527 (44c0e42) added the ability to notify a redirect's target, but returns an error if the title is invalid, such as with soft redirects via {{wi}}.  This now skips the notification in such cases.
=> xfd: Fix two bugs when RfDing soft redirects

modules/twinkleblock.js
Per #850, add a new Template:Uw-upeblock, for blocks related to undisclosed paid editing, to the list of available block presets.
=> Add uw-upeblock to block options

modules/twinklefluff.js, twinkle.js
It's not really serving much of a purpose: used only in `twinkle.js` and `twinklefluff.js`.  Consolidated in 6dc2a75 (2013) as part of #151, where the requirement was added to the gadget definition.  It used to be checked in each module (ad5af2f, 2011) but is now left just in `fluff`; there's some sense to that, though, as `fluff` is the only one that doesn't add a menu button (see also #792).
The reality, though, is that `Twinkle.userAuthorized = false` is not much of a "security" check, all the moreso because it came in `Twinkle.load`.  Moving the check higher up, before the Twinkle object is declared, makes things somewhat more tricky.  We could be slightly trickier, forgoing `Morebits` and doing:
`!(mw.config.get('wgUserGroups').indexOf('autoconfirmed')!==-1 || …
=> Remove Twinkle.userAuthorized

modules/twinklespeedy.js
Like G7 (disabled in 7191d4c as part of #300), the rationales here aren't used.  G8 is different from G7, though, in that it uses `rationale` for the tag, but `summary` for the deletion log.  We could instead set `currentParams.summary` to `currentParams.rationale` for G8 (and hide on multiple?), but the reality is that G7 and G8 are two of the CSD areas that a custom summary is least useful for.  Moreover, we only have this for the generic G8 option, and doing so would mean removing the standard G8 text (barring some moderate edits to the template).  T2, on the other hand, is just like G7, in that the summary takes no parameter.
We could, of course, change either template, forcing them to take a `{{{rationale}}}` (and/or `{{{summary}}}`), but not sure that's super helpful here; I can …
=> speedy: disable G8 and T2 rationale when deleting

modules/twinklespeedy.js
A little mixed here, since the templates are a bit all over the place, but, in brief, this adds support for:
- All three `url`s in G12 notifications (required edits to all templates, already done by me)
- G6 copypaste `to` for a single notification
- A2 `source` on multiple nominations
- F9 `url` on multiple nominations
=> speedy: Add additional user talk notification parameters (utparams)

modules/twinkleprotect.js
If PC isn't enabled or available on the given namespace (see, among others, #560 and #738), the check for `item.stabilize` would throw an error, leading most notable to the "unprotection" preset not setting the template option to "none."
=> protect: Fix bug affecting untagging on PC-ineligible namespaces

modules/twinklespeedy.js
This is much delayed.
`HideSubgroupWhenMultiple` was added to G5 in Oct 2013 (https://github.com/azatoth/twinkle/commit/a04f034f33f5165ed784356f541337346308cb4e) and to G4 two years later (Dec 2015) as part of #300 (https://github.com/azatoth/twinkle/commit/7191d4cb24887b58909033ff7b58df3de5e8e616).  At the time, neither was supported by {{db-multiple}}, but both now are: G5 has been supported since [Feb 2017](https://en.wikipedia.org/w/index.php?title=Template%3ADb-multiple&diff=prev&oldid=765075803), with G4 coming later in [May](https://en.wikipedia.org/w/index.php?title=Template:Db-multiple&diff=prev&oldid=781332988).
Additionally, I've added support for an `xfd` parameter in the {{db-[notice|deleted]-multiple}} templates and covered that here as well; …
=> speedy: Allow G4 and G5 when multiple

modules/twinklespeedy.js
A5 (location) and P1 (criterion) parameters added to all four templates, so we might as well include them here
=> speedy: Add utparams for A5 and P1

modules/twinklexfd.js
The hidden message has been changing frequently, leaving us behind (e.g. #791, #842), so by using a short regex rather than an exact string match, we should be able to handle subsequent changes.  This change also only loads section number 2; that's possibly overkill, but could theoretically avoid some off-target effects with the page's other hidden comment.  Would cause issues in the unlikely event of the page being restructured.
=> xfd: Use shorter comment and regex to avoid constantly updating RM/TR comment

modules/twinkleblock.js
Requiring the username to end in 'bot' means we miss out on some major ones (e.g. AnomieBot III, ClueBot NG), but checking for a word boundary should improve things without much collateral (e.g. NinjaRobotPirate).
=> block: Use word boundary regex to match bot usernames

modules/twinklespeedy.js
I only noticed this after looking at things after #849, but we've been giving inaccurate notices for G6's copypaste for ages.  {{db-copypaste-notice}} is just {{uw-c&pmove}} at a different title so Twinkle can handle providing the notice, but that notice uses a different format than the rest of the (standardized) csd notices.  In particular, parameter `1` is *not* the page name, but rather the name of the *original* page.  I *think* it's likely fine to change {{db-copypaste-notice}}, but I'm not sure if anyone else uses it and for now this is simpler.
=> speedy: Fix long-standing bug in G6 copypaste notice

modules/twinkleconfig.js, modules/twinklespeedy.js, twinkle.js
Requested by the community following discussion after an [arb case](https://en.wikipedia.org/wiki/Wikipedia:Arbitration/Requests/Case/RHaworth).  `deleteSysopDefaultToTag` is used by around 50 individuals, and there was some local consensus to have Twinkle default to tagging for sysops if there's no CSD tag already present.  Accordingly:
- `deleteSysopDefaultToTag` (default `false`) is replaced by `deleteSysopDefaultToDelete` (default false), reverting the default behavior for all sysops; sysops will now default to "tag" mode (if there's no CSD present, see below).  Users must manually opt for the previous default behavior, to default to "delete" mode.
- If there is a deletion tag present, Twinkle will now always default to "delete" mode.  This isn't technically required, but makes sense …
=> speedy: Adjust default tag mode for sysops

modules/twinklearv.js
Some feedback is helpful, so the user can see, explicitly, that nothing was found, rather than wondering if something went wrong
=> arv: Add entry to empty AN3 requests

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklefluff.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, morebits.js, twinkle.js
We checking `Morebits.userIsInGroup('sysop')` over 40 times, it's by far the most common check.  Mentioned at https://github.com/azatoth/twinkle/pull/793#issuecomment-575462618
=> Add Morebits.userIsSysop, use everywhere instead of Morebits.userIsInGroup

modules/twinkleblock.js, morebits.js
1st commit: Lets us use `addFooterLink` to prepend if desired.
2nd commit: Does that in block to link to Special:Unblock/User if the user is blocked.
=> morebits: Allow addFooterLink to prepend rather than append

modules/twinklespeedy.js
Since #578, we've been trying to correctly note in the CSD log whether the user notification went successfully.  That was carried over into #563, but the changes in #578 meant that if the user attempted to notify the creator (e.g. `params.usertalk`) but then discovered (in `noteToCreator`) that there was a good reason not to, no CSD log entry was made; it accounted for whether you wanted to notify-then-log or just log, but didn't account for notify-but-notify-not-done-then-log, essentially ignoring the checks from #436.  Specific cases, like R2 ([reported at WT:TW](http://en.wikipedia.org/wiki/Special:Permalink/942392393#CSD_R2_instances_not_being_logged)), were especially prone to being missed in the log.
This uses those `initialContrib = null` checks to recheck whether a notification …
=> speedy: Log nomination even if user notification prevented

modules/twinklewarn.js
As noted in #872 for the CSD module, {{uw-c&pmove}} actually takes the source of the material as the first unnamed parameter, and the target article as the `to` parameter.  As users are likely to be warning an editor for the incorrect behavior, this will be populated with the target of the c&p move, so should take the `to` parameter.
In the future, it would be nice to have an additional box just for {{uw-c&pmove}} to also list the source page, if it's known, but that'd involve a larger restructuring.
=> warn: Fix long-standing bug in cpmove warning

morebits.js
Not entirely sure if this is helpful or not, but if there's a `className` given in a quickForm `type: 'submit'`, we were just dropping it when creating a proxy button, which seems counter-intuitive.  Without a `className`, the proxy button is accessible via `$('.morebits-dialog-buttons button')`, which isn't submit-specific, so absent a provided `className`, adds <s>`submitProxy`</s> `submitButtonProxy` to the button class.
Currently unused in Twinkle, but it would make things like https://github.com/azatoth/twinkle/blob/9a7ecce336dc70a637c02ff4829fb19f861df7fb/modules/friendlytag.js#L270 (from #648) and https://github.com/azatoth/twinkle/pull/844/files#diff-4e20504588e50710cb9f42b74f59993dR309-R313 prettier.  I had initially considered an `id`, but a class seemed appropriate given we …
=> morebits: Proxy submit buttons take the className

modules/twinklearv.js, morebits.js
Swaps `textContent` out for `innerHTML` in the `p` element (the header).  Doing so allows the use of html (go figure), which menas we can link to AIV and UAA to close #590.  Shouldn't have any noticeable effects otherwise?
Alternatively, we could add some selector to either/both `printUserText` elements then work on that directly.
=> morebits: use innerHTML for printUserText message header, not textContent; use in ARV

modules/twinklexfd.js
In doing #862, I undid the intent of #714 to avoid the client clock as much as possible for the specific case of soft redirects being nominated at RfD.  It never worked - thus #861 - but the idea is sound.  This has softredirects go through the same `curtimestamp` query and "typical" redirects, but simply skips processing of target or section.  It's not a free check anymore, but it should be incredibly infrequent and fairly quick.
Also added a note for softredirect failures from the history tab.  If run from history, the `Morebits.wiki.isPageRedirect` check for soft redirects won't work.  The module fails fine, but a note suggesting users retry from the content tab is helpful.
=> xfd: Avoid client clock for soft redirects

modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js
**1st commit: morebits: lookupCreation won't query content and section unless lookupNonRedirectCreator is provided**
PR #710 added the ability for `fnLookupCreationSuccess` to find the creator of the first non-redirect revision via `fnLookupNonRedirectCreator` (see also #805) by adding `content` to the `rvprop`s list as well as `rvsection=0`.  That doesn't work for non-wikitext content models, who will returned a `rvnosuchsection` error in such cases.  Removing `content` would solve the error, as would `rvsection=0`, but the actual redirect check (`/^\s*#redirect/i`) doesn't make sense in those scenarios (e.g. Scribunto, JS, CSS), so there's no really point in even checking.
Instead, only attempt to use `content` and `rvsection` if `lookupNonRedirectCreator` is set.  Currently, only AfD …
=> Slightly improve handling of Scribunto/non-wikitext content models

morebits.js
- `lookupCreator` was deprecated in June 2019 (#610, b753057), renamed and improved as `lookupCreation`
- `Morebits.wikipedia.namespaces` was removed in May 2019 (#600, bd67ad8)
=> morebits: Remove deprecated lookupCreator function

modules/friendlytag.js
Requested at WT:TW.
Sport -> Sports mostly to keep it in line with the other parameters.
Add a missing list parameter.
Places -> Geographic in line with the Notability guideline that is called Geographic and include places (which is a geographic feature).
=> tag: add and update {{notability}} parameters

modules/twinklespeedy.js
lookupCreation will fail if the page has already been deleted.
Fixes bug reported on [WT:TW](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Notifying_creator).
=> speedy: wait till the creator is identified before deleting.

morebits.js
`notoken` error code has been removed from MediaWiki. Write queries without token now return the standard `missingparams` error.
It is anyway not necessary to handle this error since we do specify the token, so this just wouldn't ever occur.
In case of expired tokens, the `badtoken` error continues to be returned, which we do handle.
=> morebits: don't handle notoken error

modules/twinkleconfig.js, twinkle.js
Not everybody uses everything, and even in a menu, a lot of menus you never intend on using is annoying.  This adds two new config options, `Twinkle.config.disabledModules` and `Twinkle.config.disabledSysopModules`, and constructs an array of module names to be turned off.  The loading mechanism in `Twinkle.js` now only loads items not explicitly turned off.  The instances where we link from one to another (deli->spoeedy, speedy->unlink) work fine since they use the `callback`.  `config` cannot be turned off, and the default is, of course, to have everything on.
----
Currently live on testwiki for testing.  Depends on #792, but if that's not committed, it'd be trivial to replace `Twinkle[module]();` with:
```javascript
if (module !== 'fluff') {
Twinkle[module]();
} else { …
```
=> Add new option to disable individual Twinkle modules

modules/twinklespeedy.js
Hopefully clearer to read and maintain.  There shouldn't be any downsides to passing one usertalk template's parameters to the other, but as I've just added `url` to the F9 notices and `source` to the A2 notices, there currently aren't any instances of that here.
=> speedy: Deduplicate utparams processing, pass everything to everybody

modules/twinklexfd.js
Mostly for completion's sake, but this is alrady explicitly set for nearly everything.  The only exceptions were:
- CfD tagging.  Was the only tagging without it, left off when added to all taggings in c97229c, presumably an oversight.
- CfD/S listing and tagging. Not included when added in 9d6818a, presumably unintentional given the other options. CfD/S doesn't have user notifications.
- RMTR listing.  RM was added in #698 and involves no notifications or tagging.  `setFollowRedirect` added to `listAtTalk` per comments there (https://github.com/azatoth/twinkle/pull/698#discussion_r339865891) but hadn't been present for the rmtr options.
----
As above, this is mostly for completion's sake.  We may want to consider revisiting some of these (vis-a-vis #379 and #753 (in particular taggings …
=> xfd: Align setFollowRedirect(true) use aka add to everything missing it

modules/twinklexfd.js
Disabled in c97229c due to bugs in the API returning edit conflicts; temporally, it seems related to #19, and I think 45ce088 may have been trying to fix the same thing.  I'm not sure what the error was but that was nine years ago, and testing seems fine, so I'm hoping this is okay, sort of a test for the rest.
=> xfd: reenable setPageSection for mfd and cfd

modules/twinkleprotect.js
Behavior from 99d8d270.  It's nice to ask, but when you've already opted to have the templates removed (`none`), being asked is annoying.  Also remove duplicate `if` stemming from 13638b8 (2011); seemed to be trying to fit into the structure of what was there present; subsequent edits have moved the `summary` declaration.
=> protect: Don't ask to remove tags if you've chosen to remove them

modules/friendlytag.js
Allow entering a reason to be appended in the edit summary. 
Unlike adding of tags, it is typically expected that a reason be given while removing tags. Truth be told, the untag feature (#485) remains incomplete without this. I don't think I have seen the untag feature being used any more than 1-2 times.
Demo of usecase: [Special:Diff/945510112](https://en.wikipedia.org/w/index.php?title=Via.com&diff=945510112)
Currently the reason field is shown all the time. I'm open to feedback on this. Would it be better to show the reason field only when one or more tags have been de-selected?
=> tag: allow entering a reason

morebits.css, morebits.js
Makes the library slightly more Twinkle-agnostic.  <s>Only proper use is User:SD0001/RFUD-helper.js and even that seems unnecessary given the comment; regardless, @siddharthvp is more than capable of managing any issues ;)</s> No real uses.
=> morebits: Change status class to morebits_status from tw_status

modules/twinkleconfig.js, twinkle.js
They're barely used, but the various "hidden" preferences have been ignored by `twinkleconfig` for ages.  The unification of twinkleconfig and friendlyconfig from #762 (f0ebd3f) didn't actually solve that problem, and the check to catch them has only meant that deprecated options (present in [[twinkleoptions.js]], but different from the default by dint of no longer existing in the default) are retained instead (moved to the bottom).  The problem is that these were getting added to `foundPrefs` (`foundTwinklePrefs` and `foundFriendlyPrefs` prior to #762) without a value (skipped because they are hidden in the form), but since they were "found" the iteration over `Twinkle.prefs` to find missing items would by its very nature skip them.  Instead, since they can't be changed in the form, …
=> config: Don't save deprecated options, properly save hidden options

.eslintrc.json, DEVELOPER.md, modules/twinklearv.js, modules/twinkleblock.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
New class in Morebits for handling of dates per brief discussion in/after https://github.com/azatoth/twinkle/issues/769#issuecomment-566163740. 
This replaces the moment dependency. Some of the functionality here exceeds that in moment - the `format` function can read the user's preferred time zone from the site preferences, which is ideal since dates shown by MediaWiki core and extensions are in that time zone. 
All the various UTC/non-UTC abbrev/full combinations for getting month/day names are provided. I didn't particularly like doing this, but I guess it's good to have them all for the sake of completeness. Some of these get used in `format`.
The `format` function has been reworked. The [gist version](https://gist.github.com/siddharthvp/dcdc51e05aa79a5856e63ecc116dcacf) presented a …
=> Add Morebits.date

morebits.css
See #778.  The stuff in the portlets section was all added in 511bd8f and is just for the Modern skin, but it is all already present in the main Modern CSS: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/skins/Modern/+/master/resources/main.css.  Don't think it was even needed at the time, but regardless, does nothing and can be removed.
=> morebits: Remove twinkle-specific CSS that is 100% redundant

modules/twinkleblock.js, modules/twinklefluff.js, morebits.js
There are a few connected commits here, but the meat of it is in the second commit.  Closes #615.
Using `intoken` was deprecated ages ago.  `curtimestamp` is used in `.load` now that we no longer use `intoken`.  As noted in #741, `starttimestamp` was only available because we were still using the outdated `intoken` method; with that gone, we need to explicitly provide `query.curtimestamp`, thus replicating the loading timestamp that we can feed it into `starttimestamp` and avoid edit conflicts.  Some references to token names in error messages were kept for ease of debugging.
Some token handling is changed in `block` (1st commit) and `fluff` (2nd commit).  The 3rd commit tweaks the querys to update the deprecated `watch`/`watchlist` parameter (excepting for PC).
4th commit: Use …
=> morebits: Use csrftoken obtained via meta=tokens

modules/twinklearv.js
1st commit: Combine the three largely identical AN3 queries, avoid errors
Don't print console errors if is provided: we shouldn't be unnecessarily spitting out console errors, either from null queries or mw.Title.  The warnings check is fine, though.
Has a more helpful API error messages, similar to #866.
2nd commit: Better text for revdel'd comments in AN3 diffs
=> arv: Combine AN3 queries, avoid errors, and handle revdel'd comments

modules/twinkleconfig.js, twinkle.css
Was requested by @Enterprisey a while ago: https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#%22If_you_want_to_set_Twinkle_preferences...%22_box_CSS, see also #778
=> config: Move CSS for box on userjs to twinkle.css

morebits.css
This has its roots at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=947164475#Red_links), which was concerned with not seeing redlinks in the preview box (see #900 and #901).  That was because `morebits.css` was applying a `color` to `.ui-dialog.morebits-dialog a, .ui-dialog.morebits-dialog .ui-widget-content a`.  This obscured any link characteristics in the preview, including some such as `:visited` that #901 would have enabled, but this goes deeper, and indeed we do not even need to specify this CSS anymore.
Initially put in place with the CSS "extraction" in 511bd8f, the "ridiculous nearly-black colour" from jQuery was/were #362b36 and #222222, the default from jquery-ui (`.ui-widget-content`), but that was removed in 2015: see …
=> morebits: Don't overwrite link color CSS

modules/twinklefluff.js
Fixes #913, same basic issue as #627/#628: if a user has "Do not show page content below diffs" selected in Special:Preferences, wgRevisionId is set to 0 on diffs.  While #628 took care of that for the links on diff pages themselves, trying to rollback from a contribs page was left unfixed.  Those links load the diff page then `auto`matically revert, so will run into the same issue.  This essentialy reverts back to the check before 3e5ec5b2 (#561), albeit by using `mw.util.getParamValue` rather than the no-longer-existing `Morebits.queryString.get` (#725).
=> fluff: Fix revert coming from contribs if diffonly is used

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, morebits.js
Morebits.date (#814) can make these much nicer for sysops to read
=> morebits, batch: Use Morebits.date to format protection confirmations/notes

morebits.js
As promised at https://github.com/azatoth/twinkle/pull/814#event-3176003347, opened for discussion.  Commit are separate for review, and ordered from what I consider most to least worthwhile:
1st commit: Use YYYY-MM-DD for Morebits.date in calendar localeData
`moment` on enWiki returns `DD/MM/YYYY` but that's just a locale specification I believe.  Given the US-centric-but-not-exclusive enWiki population, both `DD/MM` and `MM/DD` can lead to confusion (the MOS, for example, suggests avoiding these uses).  Doing `YYYY-MM-DD` should avoid any such confusion.
2nd commit: Allow adding/subtracting seconds
<s>3rd commit: Add `isSame` to Morebits.date to compliment `isAfter` and `isBefore`</s>
=> morebits: Some tweaks to Morebits.date

DEVELOPER.md, Makefile, sync.pl
I'm the only one who really uses this, but I wanted to open a PR to at least document the fact that the way parameters should be given will change.
1. Rather than `--deploy` or `--push`, you now do `--mode=deploy`, etc.
1. The `base` parameter is now a prefix, so if you want to reference user subpage, you should do `--base=User:AzaToth/` (with the trailing `/`)
1. Duplicate parameters are now okay; the last one provided will be used
=> sync.pl: Change how push/pull/deploy parameters are used

morebits.js
Not sure how this was missed in #814, but js date will see the parentheses in `(UTC)` and completely ignore the whole thing, setting the timezone local.  Should cause issues anywhere, but particularly problematic for the warn module.
Vaguely related discussion: https://github.com/azatoth/twinkle/pull/814/files#r374359937
=> morebits.date: Fix bug parsing parens around UTC timestamps

modules/twinklewarn.js
Most templates have a hidden comment of the form `Template:uw-templatename`, but some have `Template:Uw-templatenme`; this adjusts the regex to account for those cases, as well as missing spaces.
=> warn: Ignore case when parsing warning history

modules/twinklespeedy.js
If deletion was canceled (e.g. at the page was protected alert) the notice to the creator should not go through
=> speedy: Don't notify users of deletion until deletion has succeeded

modules/twinklexfd.js
1st commit: Enable CfD for stub templates, disable CfD outside catspace and templatespace
Determination of a stub template made by simply asking if it is a template whose name ends in `-stub`.  Had to make {{sfd-t2}} and {{sfr-t2}} and add support for stubs to {{cfd-notify}}.  With this in place, TfD can now be disabled on such stub templates, and CfD can be disabled outside template or categor space (#753). (Leaving open for the entirety of templatespace allows [Rcat templates](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Redirects_for_discussion&oldid=949051818#What_should_be_the_venue_for_discussing_Rcat_templates?))
I'm not entirely sure how specific the `-stub` ending check is, and whether we should be disabling TfD on such a check.  AFAIK that's the only way to check …
=> xfd: Enable CfD for stub templates, fix cfd(s)/tfd namespace previews

modules/friendlytag.js, modules/twinkleconfig.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js, twinkle.js
A bunch of improvements growing out of the discussion at [Wikipedia talk:New pages patrol/Reviewers#Advice on deletions](http://en.wikipedia.org/wiki/Special:Permalink/950279840#Advice_on_deletions).
1. morebits: Fix `.patrol()` by grabbing/querying for the `revid` if `rcid` is unavailable.  Per @siddharthvp at WT:NPPR, this is a major source of missed patrols.  `revid` wasn't available as an option when this was added in cae9a73 (Apr 2011) and it hasn't been touched since.
1. morebits: `getPageID` getter for `pageid`, matches `wgArticleId`
1. morebits: Add triage/curation action to mark pages as reviewed with PageTriage extension.  Uses above getter, ignores errors like `.patrol`.  Requested at WT:NPPR so as to remove from both Special:NewPages and Special:NewPagesFeed.
1. xfd/csd/tag: …
=> Add pagetriage in place of patrol for NPP

morebits.js
Removed to favor `Morebits.date` (#814) but as correctly pointed out by @siddharthvp (http://en.wikipedia.org/wiki/Special:Permalink/953256906#Technical_changes) there are plenty of scripts that still rely on these.
=> morebits: Reintroduce to deprecate removed Date getUTCMonthNames prototypes

modules/twinklexfd.js
Bug introduced in #814 (c21e4122), where the formatting of date objects left off the 'utc' requirement.  [Noted at WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=953597659#Twinkle_TfD_put_a_misplaced_line_break_after_closing_noinclude,_and_linked_to_the_wrong_date).
=> xfd: Use UTC for log pages, headers

morebits.js
See https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=954707038
As noted in #921, mediawiki on enwiki uses dates formatted like `19:37, 3 May 2020 (UTC)`, which is an invalid date for two reasons. The first is that (UTC±offset) isn't correct for a timezone, and the native Date converts it to a local date; that is, 17:00 (UTC) become 17:00 (local). The second is that the comma after the time is just plain wrong. Twinkle's new date function handles both of those, except that apparently Firefox 75 will actually now accept the comma as valid. Thus, Firefox was short-circuiting our initial check to see if we had a valid date, before we could clean up mediawiki's parenthesis crap, which was leading to local timezone issues.
=> morebits: Fix date parsing for Firefox 75

modules/twinkleconfig.js
Somehow left out of #793 (6b498897)
=> config: Correctly mark disabledSysopModules pref as adminOnly

modules/friendlywelcome.js
Add the option to use the {{Welcome-retro}} instead of {{Welcome}} since the welcome template was changed recently to exclude several links and to use buttons instead of the list of links.
=> friendlywelcome:  Add welcome-retro

modules/twinklefluff.js
- Typo: `statitem` -> `statelem`.  This stems back to 2011 (54347f92/98240d17), although there was another instance present from the initial import that was fixed later that year in be5d8ffe
- Type: `parseInt` `revid`.  Fix potential type issue treating `revid` as a string, missed in 37cd0c68 (2011)
=> fluff: fix two ancient bugs: typo and type

modules/twinklexfd.js
`\\s` in `Morebits.date().format` gets matched to seconds, resulting in the regex never matching the current date.  First reported at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=958390123#Twinkle_keeps_reposting_the_same_date_header_at_MfD)
=> xfd: Fix bug formatting whitespace match in MfD dateheader regex

modules/twinklewarn.js
This reverts commit b81d3958172f9d231811af7d886ed2fcd5fcaec6.
- Deleted at TfD 6 May: https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_April_29#Template:Uw-3rr-alt
- Relisted at DRV 20 May: https://en.wikipedia.org/wiki/Wikipedia:Deletion_review/Log/2020_May_11#Template:Uw-ewsoft
- Kept at TfD: https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_May_20#Template:Uw-ewsoft
Okay, it's not kept *yet*
=> warn: Restore uw-ewsoft after DRV

modules/twinkleconfig.js, modules/twinklewarn.js, twinkle.js
Edit April 2020: Very different, see https://github.com/azatoth/twinkle/pull/777#issuecomment-616898576
----
*Original message*
Full commit messages are below, but this will most certainly conflict with #759 and #773 so <s>opened as a draft</s> should wait on those; still, I wanted to discuss a few things here while testing/etc.:
* How long should elapse before a previous warning is considered stale and we reset the level rather than increment higher?
* AFAICT, the default for Huggle is 30 days ([noted on enwiki](https://en.wikipedia.org/wiki/Wikipedia:Huggle/Feedback/Archive_21#Autowarn_and_stale_warnings), present in code at [1](https://github.com/huggle/huggle3-qt-lx/blob/13df16adf5744825f8a27d70b3bab998ad19f4b0/src/huggle_core/configuration.cpp#L187) and …
=> warn: Add option to autoselect warning level 1-4

modules/twinkleconfig.js, modules/twinklexfd.js, twinkle.js
There's not the same reason to log XfD nominations as there is for CSDs and PRODs, but this is useful/interesting regardless; a few folks have asked for it or though it would be useful.  It is also a lot more complicated.
The basics:
- Adds config options (logXfdNominations and xfdLogPageName)
- Lots of venue-specific log formatting (`toTLACase`, etc.)
- Like PROD/CSD, checks whether user was notified (although see below).  CfDS and RM have no user notification.
- Includes a link to the page log for files
- Stores common parameters and makes use of `.extend`
Nitty-gritty:
There are real complications around several venues, in particular confirmations on whether something actually happened and what information is available.  Most are dealt with, some aren't.  At a very basic level, we're …
=> xfd: Add XfD log, parallel to CSD and PROD

modules/friendlytag.js
Put here for opinions: the quickfilter makes it possible to lose context, but I'm not sure this actually a good idea or if it's just visual clutter.
=> tag: Italicize tags already present in form

modules/twinkleconfig.js
When first created, this lovely creation was a pretty new idea and, as noted in 846b7277, worthy of testing.  That was 2011, and AFAICT I am the only one with this actually page extant (https://en.wikipedia.org/w/index.php?&search=intitle%3A%2FTwinkle+preferences%2F&title=Special%3ASearch&ns2=1).  I don't think we need to maintain this internal testing logic.
=> config: Remove testing invocation on named user subpage

modules/twinklefluff.js
The check was added in 9bf38bc3c and is fine, but using `statelem.warn` means the prior function continues and the `actionCompleted.notice` gets treated as successful, which is misleading.
=> fluff: Don't say reversion completed if there's no change

modules/twinkleblock.js
The `area` box would show on initialization if the user was already blocked, when it should only show iff the user is receiving a partial block template but *not* a block.  Changing the template or preset would kick the checks into action, but they weren't being processed on a reblock.  Original sin is from the initial adding of partial blocks in #813/61b5269.
=> block: Fix bug showing erroneous input box on a reblock form initialization

modules/twinkleconfig.js, modules/twinklefluff.js, twinkle.js
Both off by default; these commits can be squashed, but are separate for perusal.
**1st commit:** Use the provided diff url to get oldid.  Avoids issues with arcane diffs urls, and with urls on recent changes where oldid/curid/diff are each provided, and oddly besides.
(this is just a setup necessary for the next commit, doesn't necessarily stand out in the diff)
**2nd commit:** Add ability to enable rollback links on Recentchanges(linked)
Adds new `recent` option, off by default.  Most of the complexity in the selectors comes from having to handle two preferences: using the new or old (no js) RC system, and the grouped or ungrouped preference.  Uses the `wikipage.content` hook to (re)generate links when new diffs are loaded.
Also expands `openTalkPageOnAutoRevert` to apply at RC/RCL, …
=> fluff: Add rollback links to Special:Recentchanges and history pages

modules/twinklefluff.js
This is a pain to test without #942 and #947 but should preempt issues like #855 when there's an edit conflict detected, which should be more likely after #942.  This kind-of relates to the duplication of behaviors in `morebits`, but these perceived "edit conflicts" are still handled there.
=> fluff: Don't open the talkpage unless/until the reversion is complete

morebits.css, morebits.js
This stretches all the way back to 846b7277 and bc64fc34 (with a lot of intervening history), but it seems like an over-complication, especially if someone wanted to change the CSS.  In place of the data url, the same color as the footer (#BCCADF) is used, rather than previous fallback (cfd6e1).
Also removes some unnecessary `!important`s
=> morebits: Use background-color instead of a dataurl

package-lock.json, package.json
Doesn't seem to require any changes on our part:
- https://eslint.org/blog/2020/05/eslint-v7.0.0-released
- https://eslint.org/docs/user-guide/migrating-to-7.0.0
- https://eslint.org/blog/2020/05/eslint-v7.1.0-released
- https://eslint.org/blog/2020/06/eslint-v7.2.0-released
See also https://eslint.org/blog/2020/05/changes-to-rules-policies
=> Update eslint from 6.8.0 to 7.2.0

modules/twinklespeedy.js, morebits.js
Morebits.wiki.api.prototype.post() now returns a jQuery promise object, on which done/then/fail/catch/always handlers can be attached, as an alternative to giving the success and failure callbacks as arguments in the constructor.
On the output of $.ajax(), `done` and `fail` are changed to `then`. This makes it possible to specify exactly what arguments (and `this` context) should be available to the handlers. We specify these to match the ones used in the callbacks, (`apiobj.parent` as `this` context, and the `apiobj` as the first and only argument). This makes it easy to transition existing code using callbacks to use promises.
Tested, confirmed working!
=> morebits.wiki.api: enable promise support

modules/twinklespeedy.js
CSD A7 "applies to any article about a [list of things omitted] that does not indicate why its subject is important or significant". However, currently Twinkle summarizes A7 as "Unremarkable", which isn't accurate -- there are plenty of unremarkable things that do not satisfy the very low bar of A7 (which "does not apply to any article that makes any credible claim of significance or importance even if the claim is not supported by a reliable source or does not qualify on Wikipedia's notability guidelines.")
I propose changing "Unremarkable" to "No indication of importance or significance of subject".
=> speedy: Align A7 criteria labels with the actual criteria

modules/twinkleconfig.js, modules/twinklefluff.js, twinkle.js
The first three commits are mostly (but not entirely!) structural changes and can be squashed to a degree, but are presented separately for clarity in diffs and testing.
----
**1st commit:** Consolidate and genericize link creation functions
- two links (`rollback vandalism`): Multiple pages present, inline span, makes use of the `twinklerevert` parameter for `Twinkle.fluff.auto()` (contribs, recent)
- three links (`rollback (AGF) || rollback || rollback (VANDAL)`): Only one page present, inline span or div, makes use of `Twinkle.fluff.revert` (diffs, history)
- `restoreThisRevision`: Inline span or div.  Also simplifies `toRevision` in `Twinkle.fluff.callback`, which was unnecessarily nested as the only member of the object (leftover cruft from 98240d1 in 2011).
This commit …
=> fluff: Unify link creation functions, add rollbackInPlace option for Contribs/RC

morebits.js
Fallout from #917, in particular with the `triage` action.
`triage`: When AfD-ing an article that was already reviewed, Twinkle would throw a scary bold error saying that the article wasn't in the queue.  Which, of course, is true, <s>so we should check first.  There's an order-of-operations annoyance here, since `pagetriagelist` and `pagetriageaction` both require `pageid`, so we *have* to query for that first.  Basically, this introduces `triageProcessListApi` as an intermediary to check if the page is uncurated.</s>
We could check the API each time to see if the apge is uncurated (e.g. introduce `triageProcessListApi` as an intermediary), but there's an order-of-operations annoyance there, since `pagetriagelist` and `pagetriageaction` both require `pageid`, so we would *have* to query …
=> morebits: Only triage or patrol if page is available for doing so

modules/twinkleblock.js
Closes #602, adds back the global `api` var from 065b0597.  We have to query `list=logevents` and `list=blocks` since the block id from `list=blocks` isn't rewritten or incremented on a reblock, only on a "new" block.  A more full explanation is in the commit.
=> block: Check if the user was blocked while filling out the form

modules/twinklexfd.js
The tooltip specifically notes two pages that are often misused, see discussion at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=961305268#Deletion_sorting_notice).
=> xfd: Link chosen delsort cats to their pages, expand tooltip

modules/friendlywelcome.js, modules/twinklewarn.js
One use in warn (#773), and two related uses in welcome (#747).
In hindsight, I think this is why I originally wrote https://github.com/azatoth/twinkle/pull/773#discussion_r352202099 so weird (amusingly, referenced in https://github.com/azatoth/twinkle/pull/747#discussion_r359567205), but forgot in the review implementation.  There've been no complaints, although these are fairly under-used aspects of Twinkle, but that could tell us something about the IE user-base.
=> warn/welcome: Remove uses of Object.values, not supported by IE

modules/friendlytalkback.js
Sometimes, I want to give talkback messages to IP users from [WP:EFFP/R](https://en.wikipedia.org/wiki/Wikipedia:Edit_filter/False_positives/Reports). I made [this template](https://en.wikipedia.org/wiki/Template:EFFPReply) for it, and would like to use it from Twinkle. Cheers, Michael (User:Mdaniels5757)
=> talkback: Add Template:EFFPReply

twinkle.js
This is all probably unnecessary, but change to match new Vector: https://phabricator.wikimedia.org/T66477 specifically https://gerrit.wikimedia.org/r/c/mediawiki/skins/Vector/+/594819 (although (temporarily) reverted in https://gerrit.wikimedia.org/r/c/mediawiki/skins/Vector/+/595627 and restored in https://gerrit.wikimedia.org/r/c/mediawiki/skins/Vector/+/596312).  I've just gone and removed the `role`.
Of course, `outerDiv` is now poorly named.  Worth renaming all of this, or just busy work?  See also #962 for changes in the menu classes.
=> twinkle.js: Use HTML5 nav instead of div+role=navigation

modules/twinklexfd.js
Issue: The log numbering at, e.g., [User:Mdaniels5757/XfD log at 963070422](https://en.wikipedia.org/wiki/Special:Permalink/963070422) is wrong (repeating 1s) because there is an extra newline when a reason is provided.
Solution: Removed that newline (line 817, twinklexfd.js).
Cheers,
Michael (User:Mdaniels5757)
=> xfd: Fix xfd log numbering

morebits.css
There's a jQuery UI style sheet that uses `!important`, just for Vector though.  I can't find it, but at any rate, these three are thus required.
=> morebits: Restore some importants removed in 9a71ba2, required for Vector

modules/twinklefluff.js, morebits.js, twinkle.js
- fluff: whiteList -> trustedBots
- twinkle: specialPageWhitelist -> activeSpecialPageList
See [T254646](https://phabricator.wikimedia.org/T254646) for a fine starter; the change in fluff includes text forward-facing for users.  All our uses of blacklist are currently dependent on MW, either directly (API error code, extension name) or indirectly (template named for the extension).
=> Rename whitelist to use clearer terms

DEVELOPER.md, morebits.js
See https://en.wikipedia.org/wiki/MediaWiki_talk:Gadgets-definition#Twinkle_dependencies_are_incomplete; `mw.api` is currently used in block and arv
(cc @Huji)
=> Note dependencies on mediawiki.Title (morebits) and mediawiki.api (Twinkle)

modules/twinklearv.js
If an api object is only used once, no need to store it in a variable
=> [ARV] Cleanup: Don't save single-use api variables

modules/twinklefluff.js
Likely broken since the restructuring of `Twinkle.fluff` away from an object in 55745c98/#792
=> fluff: Fix trustedBots array

morebits.js
Lost in between adding JSON support (19435c4/#493) and removing `queryString` (37d6b67/#725)
=> morebits: fix ability to query in JSON

modules/twinkleblock.js
In IE, fieldset elements are not available as properties on the HTMLFormElement object. The loop was silently being skipped as `$(undefined).find(...).each(...)` doesn't throw. This bug has been here since the block module was added in 465eb53.
=> block: fix IE bug

.eslintrc.json, modules/.eslintrc.json
The values false and true are deprecated, they are equivalent to "readonly" and "writable", respectively.
See https://eslint.org/docs/user-guide/configuring#specifying-globals
=> lint: mark globals as writeable/readonly

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkledeprod.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
New function to efficiently retrieve all data entered in a form (any form, not necessarily a `quickForm`).
This should get rid of the need to:
- write repetitive `var x = form.x.value` like statements.
- manually `.trim()` text/textarea input values
- use the custom-defined `HTMLFormElement.prototype.getChecked` function (though still used in a few places).
=> morebits: Morebits.quickForm.getInputData

.eslintrc.json, DEVELOPER.md, modules/twinklefluff.js, package-lock.json, package.json
I stumbled on https://github.com/nkt/eslint-plugin-es5 about a year ago but it had too many false-positives when used with jQuery.  Most of that (https://github.com/nkt/eslint-plugin-es5/issues/12) appears to have been resolved with v1.5.0, specifically https://github.com/nkt/eslint-plugin-es5/pull/36.  This won't catch everything but I *think* it shouldn't have many false positives, as long as things like jQuery's `.find` are used on the same line as `$`, whether `jQuery` or as a variable name; we're inconsistent on that front, but it's not a bad idea to encourage it.
=> Add ESLint plugin to warn on ES6+

morebits.js
This reverts commit 62aaf522 from #928; all meaningfully-used scripts now updated <s>(once [AFCH](https://github.com/WPAFC/afch-rewrite/pull/118) is synced)</s>.
=> morebits: Revert reintroduction of deprecated Date prototypes

modules/twinklewarn.js
The red notice area was added as `olddiff-messages` in #757 and renamed to `revert-messages` in #855.  The autolevel option in #777 tried to change this to `warning-message` but utterly failed to do so.  Thus, the (non-red) autolevel has not been showing which option was being used.
=> warn: Fix bug where autolevel message wouldn't display

modules/friendlytag.js
`[name=existingTags]` isn't added unless there are existing tags, so this stalls out when there are none.  `form.getChecked('existingTags')` would presumably work as well, thanks to 83c5955.
=> tag: Fix bug in processing existing tags

morebits.js
Introduced in #915, but if the second parameter to `setFollowRedirect` (aka `followCrossNsRedirect`) isn't provided, it is passed as `undefined` aka falsey.  That breaks anything that is was using `setFollowRedirect` without explicitly passing a second parameter (aka everything), given that the default value is `true`.
As elsewhere, this `typeof` style is because IE11 doesn't support default parameters.
=> morebits: Fix bug defaulting followCrossNsRedirect to false

modules/friendlytag.js
The overly-strict requirement of `\n` meant any tags existing on the same line as the redirect would be missed.  This would lead to some unexpected behavior when an existing tag wasn't in an rcat shell, and thus an empty shell was added.  Reported at https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=963773656#Special:Diff/963757536, see https://en.wikipedia.org/w/index.php?diff=963757536.  This has the added benefit of being slightly more tidy around whitespace.
Also fixed the edit summary in cases when no tags are added.
=> tag: Fix issue in whitespace matching preexisting rcats

modules/twinklefluff.js
=> fluff: Don't add restoreThisRevision links to revdel'd history revisions

modules/twinkleprod.js
Most prominently, this moves the check for `{{old prod}}` to after the endorsement check, which allows proper endorsing (on the fritz since #735).  This means that if there's a prod already present, this will allow endorsing a (regular) PROD even if the talk page has been tagged (as should be the case).
Additional fixes:
- <s>Fix case sensitivity bug when endorsing/checking endorsing</s> Done in #975 
- Correctly note prior tag type when endorsing
- Move article age check into new prod check, where it makes the most sense.
Additionally, as written, this changes things so it *won't* add another old prod template to the talk page when BLPPRODing.  I'm on the fence about that, so would welcome feedback.
=> prod: Fix a number of bugs around endorsing

modules/twinklefluff.js, twinkle.js
It seems to have been removed from use in [September 2007](https://en.wikipedia.org/w/index.php?title=User:AzaToth/twinklefluff.js&diff=156141985&oldid=146497464).
I'm not sure we even need this, since it's only *used* once, so I'm open to a discussion on that end.  The value is referenced in an error message, and in theory hardcoding a value in two places is bad, but so is a mostly-unused preference, even if hidden.
=> fluff: Actually use revertMaxRevisions, ignored for 13 years

morebits.js, twinkle.js
First added in c236127 but the 2.0 specification hasn't been updated or considered in nearly a decade and its not something we're using.  These are used for logging purposes, all that really matters is that there's a unique and identifiable string, for which the tool and project suffice.
Also move to `wgWikiID` rather than `wgDBname` per https://phabricator.wikimedia.org/rMWd45baf7f0734a2506c77925064f42bc13e1bff5e
=> Remove useragent 2.0 specification

modules/twinkleblock.js
Let's do #858 a bit systematically. While the hack used there is probably good enough for enwiki, not so for other language wikis.
=> block: better detect bots and turn off autoblock

modules/friendlytag.js
=> tag: rename 'Quick filter' label to 'Filter tag list'

modules/friendlytag.js
Renamed from {{Other hurricaneuses}} to {{Other hurricane uses}} in 2010, and then again to {{Other hurricanes}} in 2011.  The intermediate form has about 200 instances, so the regex allows for it.
=> tag: Fix regex for renamed {{other hurricanes}}

modules/twinkleprotect.js
Stems from #908, specifically 6c38a5d.  The three protection areas (`editmodify`, `movemodify`, and `pcmodify`) should really just return a boolean, so moving the `name` attribute into the list (replacing the `value`) does the trick.  With the `name` above, they returned an empty array when unchecked, which is evaluated as `true`.  `input.movemodify.length`, etc. could have been substituted instead.
cc @siddharthvp, Sorry for not catching this before
=> protect: Fix bug in processing checkboxes

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleconfig.js, modules/twinkledeprod.js, twinkle.js
`batchdeleteChunks`, `batchProtectChunks`, `batchundeleteChunks`, and `proddeleteChunks` have been around since the inception of these modules, and have been kept as hidden prefs, but there's no real need for four separate preferences.  Nobody is using them (oddly, there are three uses of `proddeleteChunks` by inactive users with negligible edits) and there's no real need for such granularity in hidden prefs, especially given that they've been unchanged for over a decade.  This replaces them all with one unified hidden pref, `batchChunks`.
Also makes use of `batchMax` in `deprod`.
=> Merge individual chunk prefs into one: batchChunks

modules/twinklefluff.js, modules/twinklewarn.js
`timestamp` and `comment` have been in fluff's lookup queries since the module began, but they have been entirely unused since nearly the beginning.  I don't think the `comment` was ever used, while `timestamp` was removed just a few days after [inception](https://en.wikipedia.org/w/index.php?title=User:AzaToth/twinklefluff.js&diff=102706684&oldid=102702487).  It was then added to `revertToRevision` a [few days later](https://en.wikipedia.org/w/index.php?title=User:AzaToth/twinklefluff.js&diff=104232943&oldid=103392000) but was likewise not used there.  We can make use of it when rollbacking, though, if only to pass it to the warn module (a la `vanarticlerevid`, etc.), which will allow warn to avoid an API lookup when checking if the diff is stale (#757).
`timestamp` has been removed from …
=> fluff/warn: Pass timestamp from fluff to warn, allow skipping stale API check

modules/friendlytag.js
Missed this with the others, but I guess we don't want to do it here either?
=> tag: Don't follow cross-namespace redirect when posting to user talk page

modules/friendlytag.js
1st commit disallows some conflicting file tags, as requested at [WT:TW](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#Mutually_exclusive_tags).  There are probably more we could do, this covers:
- Only one of {{Bad GIF}}, {{Bad JPEG}}, {{Bad SVG}}, and {{Bad format}} is used
- Only one of {{Should be PNG}}, {{Should be SVG}}, and {{Should be text}} is used
- Only one of {{Bad SVG}} and {{Vector version available}} is used
- Only one of {{Bad JPEG}} and {{Overcompressed JPEG}} is used
- Only one of {{PNG version available}} and {{Vector version available}} is used
- The correct extension is used for Bad GIF/JPEG/SVG and Should be PNG/SVG
- Only allows JPEGs to be tagged with {{Overcompressed JPEG}}
- Only allows SVGs to be tagged with {{Bad trace}} and {{Bad font}}
2nd …
=> tag: Disallow conflicting file tags and use functions to validate

modules/friendlytag.js
Restructures the list of redirects to something like the article category list, and greatly expands the list of redirects available for tagging.
The latter has been requested frequently, and since the introduction of the quickfiler, it's much more feasible.  Using [Template:R template index](https://en.wikipedia.org/wiki/Template:R_template_index) as the model, this categorizes redirects with those headers and adds every missing redirect with >500 transclusions, which is about 60 new items.  If we limited it to those with >1000, it'd be about 40.
In theory, this is one of many steps toward unifying the various tagging mechanisms.  The headers created here are a little wonky, and with #908 the quickfilter should be able to more readily help, making use of `$allCheckboxDivs` and …
=> tag: Restructure redirect list, expand list by ~60

modules/twinklewarn.js
Option added in #915.  This one requires some thinking since we have to deal with autolevel's expectation that a valid page object will be loaded.  We really just need to catch it once the menu has loaded - or tried to - and insert a strong note there.  It's somewhat equivocating, as presumably there could be other issues.  Also closes any preview that was previously opened.
----
It could be more strongly worded, or encourage *not* just picking another template?
=> warn: Don't follow cross-namespace redirects out of usertalk space

DEVELOPER.md, modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, twinkle.js
Initialise the modules from the module files' themselves rather than centrally from twinkle.js. Doing it this way makes testing of twinkle.js and of custom Twinkle installations (like on other wikis) less cumbersome as one no longer needs to comment out or modify the initialisation lines in twinkle.js (as mentioned [here](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#How_to_use_as_a_user_script?) and [here](https://github.com/azatoth/twinkle/pull/462#issuecomment-462495588)). This also fixes the issue https://github.com/azatoth/twinkle/pull/944#issuecomment-627359133 allowing for automated setup for a test file for changes that affect twinkle.js.
To do this, we re-purpose Twinkle.addInitCallback() function ~~(presently unused anywhere within TW or from user scripts), …
=> Decentralise module initialisations

modules/twinklespeedy.js
Per [[Wikipedia talk:Twinkle#Rationale for templatecat]]. Please note that I have made zero contributions to twinkle before and struggled to test the change. I think it should work though.
=> speedy: Add rationale field for templatecat

morebits.js
#1029 seems rather far-fetched for now, so it might still be worth making some improvements to Morebits.wiki.api.
=> morebits: api improvements

modules/twinklewarn.js
- Check the last character of the custom template, excluding any paramters.  If any were given along with the custom template, the simple `substr` would pick up the last character of the parameters.  That is, `uw-mytemplate|reason=vandalx42` would register as `2` not `e`.  This would mean using an incorrect prefix in the edit summary.
- Edit summaries for custom templates chosen from the kitchensink menu were not being properly prepared.  They weren't undergoing the processing above (now folded into a generic function for both) and don't have the `summary` key.  This fixes #1025, and should be slightly more efficient besides (no need to `test`).
=> warn: Fix a couple bugs in custom warning edit summaries

modules/twinklewarn.js
Was using the default selected template rather than the latest warning found
in the page object, meaning the "found" level would be set to 1, so even if a
singlewarn template was found, it wouldn't be elevated.  If you selected a
singlewarn template, then went to the autolevel menu, the default would *be* a
singlewarn, so it would appear to be processed properly.  Fixes #1027.
=> warn: Fix bug in autolevel not elevating level for singlewarn

modules/twinklewarn.js
These were all mentioned at various points; the last one most recently at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=966473523#Feature_request:_make_template_search_easier_to_access).  I think they're all fine QOL improvements.
=> warn: Move autolevel to top of menu, add tooltip re: customizing default, focus on select2 input

modules/friendlytag.js, modules/twinklebatchdelete.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklexfd.js, morebits.js, twinkle.js
As noted [on WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=964243708#Twinkle_violating_MOS:ORDER_-_needs_correction), Twinkle isn't great about [MOS:ORDER](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Layout#Order_of_article_elements) when tagging things.  Accordingly, this:
- 1st commit adds a function to Morebits.wikitext.page to insert a string after a provided template regex.  This is basically copied from the handling in `tag`.  Takes either a string or an array and allows for custom flags.
- 2nd commit uses that in xfd/protect/prod/csd/tag, with tag getting the extra benefit of finally learning about protection tags (`{{pp}}`, `{{pp-move}}`, etc.).  A new hidden preference, `hatnoteRegex`, is added to store the "various hatnotes templates` …
=> Add `insertAfterTemplates` to Morebits.wikitext.page, respect MOS:ORDER when tagging, update hatnotes

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleunlink.js, morebits.js
Integrate checkboxShiftClickSupport into quickForm by providing a new `shiftClickSupport` option for checkbox elements.
Was developing an unrelated script, and what, I have to [write one whole extra line](https://en.wikipedia.org/w/index.php?title=User:SD0001/massMoveRevert.js&diff=prev&oldid=967476421) to get shift click support?? NO way, I am gonna tweak the library instead.
=> morebits: integrate checkboxShiftClickSupport into quickForm

.gitignore, package.json, patch-test.js
Script for automatically generating localhost test file configuration, coz I'm fed up of messing it up while doing it manually...
If you have permanently set up patch-test-loader.js to load up in the wiki (eg. I do that by permanently loading 127.0.0.1:5500/local.js from my common.js. When the server is turned on - using a switch in VS code, local.js in turn loads patch-test-loader.js), then you all you need to do to test the current branch is to run `npm run patchtest`, and switch on the server (root dir: twinkle, host: 127.0.0.1, port: 5500). One way to do that easily is to use `server.js` (`npm run server`) after PR #911 is merged.
=> add script for easily creating localhost test loaders

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js
The gadget files work fine, but to see the benefits from #946 for testing purposes, `Twinkle.addInitCallback` needs to be *below* any function expressions found within the function (`func`) that `addInitCallback` purports to add, such as the callback used by `Twinkle.addPortletLink`; e.g., for XfD, `Twinkle.addInitCallback(Twinkle.xfd, 'xfd')` must be below `Twinkle.xfd.callback`.  These are all function expressions, so are only evaluated when reached.
For visual consistency's sake, I've moved them all to the very end. cc @siddharthvp
=> Fix testing, move addInitCallback below callback definitions

morebits.js
The existing implementations, written at a time when Array.prototype.filter was not supported across all target browsers, are now embarrassingly crufty and also less efficient.
=> morebits: array: use better/more efficient implementations

modules/twinkleprotect.js
Uses `Twinkle.protect.trustedBots`, just two on enwiki (MusikBot II and TFA Protector Bot)
=> protect: Don't suggest asking bots to unprotect

modules/twinklefluff.js
Sometimes we use or reference usernames in fluff, whether the user being reverted or occasionally the user of the revision to which we are reverting.  This would cause issues if the username was hidden; more alarmingly, if the twinkler was a sysop, the username could be inadvertantly revealed (same for oversight although we're pretty careful about clean up).  This basically checks the `userhidden` property on the selected revisions, then uses that to determine whether to display the user name or a placeholder text (present in the new (as of this commit) `Twinkle.fluff.hiddenName`, set to `an unknown user`).  There is some slightly extra infrastructure around `params.user`, given that the selectors mean we're passing a falsey value for the username, but I think it's clearer this way, and …
=> fluff: Fail nicely on and don't reveal revdel'd usernames

Gadget.md, morebits.css, morebits.js
This harkens back to the homegrown tooltips that were replaced by tipsy (a14f46f, 2011), mainly because we've still been defining the CSS!  Some tweaks were made: with a decade of black, I figured blue would be too bright, so mediumblue was used (we could, of course, keep it black).  There should only be minor differences in appearance.  The classes are changed, but there's nobody using them (in fact, there are more instances of old morebits pages with the *old*, pre-tipsy style).
https://api.jqueryui.com/tooltip/
=> morebits: Remove tipsy dependency, use jQuery UI for tooltips

modules/friendlytag.js
- quickfilter: One instance of `Tags` wasn't changed to `tags` in #908/0bfb37d
- subgroups: Accidentally left off in restructing in #1002/97954b8 (noted at https://github.com/azatoth/twinkle/pull/1002#discussion_r456760615)
See also b2c9971
=> tag: fix quickfilter (file/redir) and showing of subgroups (redir)

modules/friendlytag.js
Because of the restructuring in #1003, if a tag was present but *wasn't* included in our tag module, `makeCheckbox` for already existing tags would whine and die.  Reported at [WT:TW](https://en.wikipedia.org/wiki/Special:Permalink/968776641#Error_on_tag).
=> tag: Fix process for present tags not included in the module

morebits.js
Apparently IE iterates over names of HTMLform stuff when doing `for (var i in form.elements)`?  We could also use `$.each`.
----
Reported at WT:TW around welcoming, this was super annoying to run down since there weren't any errors logged.
cc @siddharthvp just FYI this is dumb
=> morebits: getInputData: Fix dumb IE bug

morebits.js
Various protection expirys only take valid time parameters, and even if not needed (removal of protection), they need to be valid.  The API defaults to `infinity` if missing, but they can't be `undefined`.  Better way of solving #1067; see also #1057.
=> morebits: Default protection expirys to infinity

modules/twinklefluff.js
First reported at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=969770397#%22Unknown_user%22_and_rollback_errors), but with the restructuring and unification of rollback link creation done in #947 and the handling of revdel'd names in #993, the username for IP ranges becomes important.  This was blindly passing `null` (from the lack of `wgRelevantUserName`), so all IPs were treated as revdel'd when viewing a range's contributions.
=> fluff: Fix username for IP ranges on Special:Contributions

modules/twinklebatchprotect.js, modules/twinkleblock.js, modules/twinkleprotect.js, morebits.js
Organized within core in 2015 in https://phabricator.wikimedia.org/T68646, stored at https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/25d4b6cd388ba1e35129c9d5ded60b3ef5f4a12a/includes/libs/ParamValidator/TypeDef/ExpiryDef.php#19.  This is used used multiple times in block (see also #576) and could be useful elsewhere, so let's pull it out.  This does away with our (non-standard) allowance for `max` and `*`.  Also replaced some indefinites in the code with infinities, just for the sake of clarity/consistency.
=> Morebits.string: isInfinity to determine whether MW will treat a string as infinite, use in block

modules/twinkleprotect.js
Since move tries to match edit if present, but autoconfirmed is not an option (see discussion in #451), it's possible for someone to attempt a submission without any level (sysop, template, etc.) selected for move protection if they select move protection while the default edit level of "autoconfirmed" is selected, and then uncheck edit protection.  The query would just fail, but better not to reset the form.
Also moved the empty default selection for filing a request to the top, as might be expected.
=> protect: Ensure a valid type of move protection

modules/friendlytag.js
subst:orfurrev and subst:ncd were used as values, and thus treated as appropriate for generating links to.  They are not.
=> tag: Apply subst to appropriate file tags, don't link

modules/friendlywelcome.js
`value` -> `template` in #908 (4490c9ff)
Reported at [WT:TW](http://en.wikipedia.org/wiki/Special:Permalink/970559788#Can't_welcome_with_IE)
=> welcome: Fix key in autowelcome

modules/twinkleconfig.js
When reverting to a revision, by definition there isn't a straightforward way to define who was in error, at least not if there more than one revision is being undone (and even then, it's not straightforward).  This hasn't been a functional option for well over a decade (https://en.wikipedia.org/w/index.php?title=User:AzaToth/twinklefluff.js&diff=104232943&oldid=103392000); I vaguely recall realizing this before I became a sysop.  There are plenty of users who have opted for it in their preferences, but it hasn't worked for anyone since well before the current preferences system was created!
=> config: Remove obsolete torev option from openTalkPage

modules/twinkleprod.js
PROD was missing AfD templates if they weren't the first nomination.  Still used by subsequent nominations via {{Afdx}} despite being moved to {{Article for deletion/dated}} a decade ago.
=> prod: Add AfDM to tag_re

modules/twinklexfd.js
In my opinion, the new system of having some of the invalid options disabled but not the others is just ugly and plain unprofessional. It isn't feasible to disable all invalid options, so I think the better solution is to allow anything to be selected, but use warning texts to tell the user in the interface that the option may not be appropriate.
At the same time, with the warning showed on selecting AfD on redirects takes care of a [recent WT:TW request](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#AfDing_non-Article_page) and alleviates the issue #379. 
Closes #753.
=> xfd: undisable all options, use warning texts instead

morebits.css
Twinkle has been using a font-size of 11.44px (11px on monobook) on all UI dialog texts all these years. I think this is way too small that it causes accessibility issues for at least some users and is generally hard to read. 
I propose bumping the morebits font-size to 12px. This change is subtle enough that it doesn't disturb the relative positioning of any UI elements, and would likely go unnoticed, but at the same time it does make things easier to read.
=> Bump font size to 12px

modules/friendlytag.js
Move the data for the different groups of file tags to `Twinkle.tag.file.groups`. This will make it easier for projects that fork Twinkle to update it to their local tags by separating what is project-dependent (the tag data) from what is project-independent (the handling of adding the form checkboxes)
=> Friendly Tag: Separate file tag data and rendering

modules/twinkleprod.js
Fallout from #908 / b595ac6a as `getInputData` ignores disabled elements; this meant *NO* BLPPRODs were sending notifications.  Oof.
=> prod: Restore notification on PRODBLP

modules/twinklebatchprotect.js, modules/twinkleprotect.js
Split into separate commits for reviewing purposes, but these can be merged.  In short:
1st commit: Filter out FlaggedRevs and templateeditor a little more consistently/less repetitively, plus minor bugfix attempting to set PC on templates.
2nd commit: Consolidate protection lengths into `Twinkle.protect.protectionLengths`.  Slight change to how menus change, so that each expiry now always uses the default (where before the behavior was inconsistent).
3rd commit: Consolidate protection levels into `Twinkle.protect.protectionLevels` then `.filter` out inappropriate options.
=> (batch)protect: Consolidate duplicate lists, filter out improper options

modules/twinkleblock.js
Twinkle doesn't ever default to the option, but this should prevent it outright
=> block: Prevent infinite blocks of IP addresses

modules/twinkleprotect.js
We naively set the protection length (aka expiry) based on the type of protection, but there's no good reason not allow the presets to set their own.  In particular, items that should be indefinite really shouldn't default to 2 days or whatever.  To begin, I've set the following defaults:
- `pp-usertalk`: infinity
- `pp-template`: infinity
- `pp-30-500-arb`: infinity
- `pp-semi-usertalk`: infinity
- `pp-move-indef`: infinity
- <s>`pp-30-500-blp`: 1 week</s>
- <s>`pp-semi-blp`: 1 week</s>
- <s>`pp-pc-blp`: 2 months</s>
What others should be covered?  I'll ask on WT:TW/WP:AN.
----
Will conflict with #1074, whose commits are included here for completion's/diffs sake.
=> protect: Allow presets to override protection length

modules/twinklefluff.js
Assume that two revisions in a row from a revdel'd user are the same user, as it's most likely the case.  This also makes things smarter for sysops, as even if they don't see the name when clicking the link, the query will fetch it for them.
Also defaults `vandal` (the username) in `rollbacklinks` to `null` to match a `rev[i].getAttribute('user')` on a hidden name.
=> fluff: Revert multiple hidden revisions in a row

modules/friendlyshared.js, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js, twinkle.js
See individual commits for details, but basically:
- Defines `Twinkle.changeTags = 'twinkle'` in twinkle.js and applies that across the board
- Applied to `Morebits.wiki.page` via `setChangesTags()`, and manually to `Morebits.wiki.api` via `tags`
- Excludes PageTriage ([T252980](https://phabricator.wikimedia.org/T252980)) and FlaggedRevs ([T247721](https://phabricator.wikimedia.org/T247721)) (and other 
- Remove customization of `summaryAd` preferences (they options remain hidden as backups, including for use in the above)
There's some precedence for at least being polite and asking before creating a tag like this; I'll post at VPT at some point.  cc @MusikAnimal since this would be a notable change.  Closes #265
=> Add support for change tags, remove `summaryAd`

morebits.js
Unhelpful `null` if can't contact the API (no internet) but that's not a big deal.
=> morebits: Output API error code along with the error

morebits.js
Unnecessary for rendering, not used.
=> morebits: Disable parse report in preview output

modules/twinklefluff.js
Closes #1062.
Only really makes sense if multiple consecutive revdel'd users are treated as one (#1073).
=> fluff: Don't add rollback links to the top history revision if there's just one user

modules/twinkleprod.js, modules/twinklexfd.js, morebits.js
Fixes to userspace logging: 
Commit 1: use TLACase in edit summary 
Commit 2: handle lists in reason. 
Numbered or bulleted lists in the reason mangles the formatting of the log and breaks numbering. This can be prevented by including an extra leading # before the hashes or bullets. See for example [this fix](https://en.wikipedia.org/w/index.php?title=User:AleatoryPonderings/XfD_log&diff=prev&oldid=974659849).
Created Morebits.string.formatReasonForLog() to hold the code, as discussed before in #1092.
=> xfd/prod: userspace logging: minor fixes

modules/twinklexfd.js
Quite a lineage here!  When first added in #527 (a5ae221f), that left a `mw.Title` object being passed to `targetNotification`, rather than the string that `Morebits.wiki.page` expects.  This appears not to have actually been problem, however, until the ability to avoid following cross-namespace redirects was added in #915 (95445604).  This meant that the `mw.Title` object was being passed into `new mw.Title`, which would quietly complain.
It turns out that bug was epistatic to another misnaming from the addition of `getInputData` in #908 (df2aa163): a single `params.usertalk` remained, when the other had all been converted to `params.notifycreator`.
=> xfd: Fix bugs in RfD target notifications

modules/twinklexfd.js
Both delsort and pagetriage can lead to errors; the former mainly for nonexistent categories (rare), the latter for pages not in the triage queue (common, see #930).  None of these matter for the sake of losing the nomination reason, so neither needs to get evaluated before `Twinkle.xfd.currentRationale` is `null`ed.  Likely to be fairly common for the `triage` action.
If we handled `triage` the way initially proposed in #930, we wouldn't see these errors, so this is kind of kludgy.  Probably still worth it.
----
The same issue likely exists for RfD's target talkpage notification; tagging issues can/would be dealt with by #1091/#176.
=> xfd: Don't show reason for AfD errors that don't matter

morebits.js
Given the typical case, this was performing an extra check on every item until the last.  That is, for n items, `fnDoneOne` was checking `2n-1` `if`s rather than `n+1`, which approaches twice as many as necessary.  For 5 items, that's 9 V 6; for 50, it's 99 V 51.
=> morebits: batchOperation: Reorder and chain else-if to avoid extra check

modules/friendlytag.js
=> tag: Fix wrong extension check in should be templates

modules/twinklespeedy.js
This stems from over four years ago to #300 (26d974ce0) when the ability to delete under multiple rationales was to mirror tagging.  That being said, the user-facing description only mentioned tagging after 13ebf0e1 (part of (but unrelated to) #563).  Closes #1113.
=> speedy: Obey watchSpeedyPages pref when deleting

modules/twinkleprod.js, modules/twinklexfd.js, twinkle.js
The code doesn't look particularly nice, but this should be useful in practice.
Closes #1047.
=> xfd/prod: show Find sources links in AfD and PROD windows

modules/friendlytag.js
With the changes to `Morebits.quickForm` from #908 (dccdacaee), `getInputData` was treating these as arrays since, which would be `[]` when unchecked and `['undefined']` when checked.  By folding the name into the individual box itself, it obtains the `data-single` attribute, so we can correctly handled them.  Without this, it as impossible to uncheck these boxes, leading pages and individuals to *always* be notified.  [Reported at WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=977629956#merge_helper).
=> tag: Fix one-off checkboxes for notifications

morebits.js
As of 1.36-wmf.8, see [[phab:T247915]] and #888 / 0849fad8
=> morebits: stabilize api properly uses watchlist parameter

morebits.js
Was only used for the tipsy tooltips, removed in cefc232f / #971; unused elsewhere.
----
I don't see a need to adapt this function for the new ui-based tooltips?
=> morebits: remove quickForm.element.autoNWSW, unused

morebits.css
A thorough version of #1034.
Fixes the issue of font size not being scaled for users with uncommon browser font settings. Also makes the sizes consistent across all skins.
The px translation of the % sizes used are: (on the default browser settings)
- 12px in most places
- 12.96px (108% of 12px) for the titlebar and h5 headers
- 11.64px (97% of 12px) for footer links
On timeless, the sizes are very slightly different (12.008px instead of 12px, etc).
This PR touches only morebits.css. Left for the future:
- select2 css tweaks invloves a hardcoded 13px, which won't scale with browser font settings
- The large text option in TWPREFS also uses an absolute 13px
This is live on testwiki.
=> morebits.css: make font sizes consistent across skins, browser settings

modules/friendlytag.js
Stems from #1000 (see also #1108/#1114).  Basically, in #1000 I naively set tag up to check for uses of {{Bad (ext)}} whilst simultaneously forgetting that {{Bad Trace}} and {{Bad font}} were a thing.  This should also improve the message by correctly identifying when an appropriate option is available.
Reported at WT:TW: https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=978523110#Unable_to_add_Template:Bad_trace
This all needs work anyway.
=> tag: Fix bug disallowing Bad trace on SVGs

modules/twinkleconfig.js
Added in 46cd08038, but won't jump if there's no change, so pass a null value first.  See also #1131.
----
Feel like there must be a better way of doing this, but this works and I don't see any false jumping?
=> config: Fix jump-to-section behavior

modules/twinkleconfig.js
The use of `tocnumber` meant that any additional section or other rearrangement would change the location any external links would head.  That's not good!  This adds a `module` attribute, identifying each section with the specific Twinkle module being used, so any incoming section links will be consistent.  Probably overdue.
The reality is that the currently used headers have been consistent for ages, so hasn't been a huge issue; #1133 would make it one.  This doesn't make an attempt to attach the old `id`s to their long-time sections, although given the consistency/longevity of those links, that would probably be a good idea...
=> config: Use consistent heading ids for links

morebits.js
commit 1: fix error handling on no internet 
errorCode is `null` on no internet connectivity, not `undefined` let alone the string `'undefined'` which the code was looking for.
This bug was also preventing any onFailure handler from triggering because of the TypeError on line 3260 (null doesn't have `indexOf` method).
commit 2: wait for 2 seconds after a connection error
Retrying immediately after encountering a network error is pointless, the most likely outcome is that the same error would recur. (Ever since I added a 5-sec wait in SDZeroBot, it has never ever encountered failures due to lack of connectivity. 5 may be excessive for a user-facing script though.)
=> morebits: fix error handling on no connectivity

modules/twinkledeprod.js, morebits.js
Was the only method in `Morebits.wikitext.template`, and the only use is in deprod; nobody else uses it.
Also changed the default index to 0, seemed reasonable.
=> morebits: Rename wikitext.template.parse to wikitext.parseTemplate

modules/twinklefluff.js
MajavahBot can edit directly after an edit to WP:EF/FP/R, a page with frequent vandalism edits.
=> fluff: Add MajavahBot to trustedBots

modules/friendlytalkback.js, modules/twinkleconfig.js, twinkle.js
1: Add BLPN, ELN, FTN, NORN, NPOVN, RSN
2: Remove `adminNoticeHeading`.  It's only used by ANI and AN, but since {{AN-notice}} has a built-in header (as with nearly every other noticeboard notice), we've been using {{ANI-notice}} for AN.  This just hardcodes a relevant header in for ANI, and removes the preference entirely.
cc @siddharthvp
=> talkback: Add more noticeboards and remove adminNoticeHeading preference

morebits.js
Stems from af13dcede/#1038.  Looks like, since `Morebits.wiki.api.getToken` explicitly creates a new construct, `this` in `returnError`'s return ends up going global (`window`).
[Reported at WT:TW](https://en.wikipedia.org/w/index.php?oldid=982033312#%22Getting_token%22_and_what?)
=> morebits: Fix bug in getting new token

modules/twinklexfd.js
Builds on #741 to remove uses from FfD, CfD, and TfD, essentially closing #6.
----
Separate commits for ease of reviewal.
=> xfd: Remove final uses of client clock

modules/twinklexfd.js
Since #1093 (7a450cb56), in an attempt to avoid pointless errors leading to *actual* errors, I moved the `pageobj.triage()` call to after the `Twinkle.xfd.currentRationale = null` limits such errors.  This, however, meant that since then, AfD nominations were always trying to triage the *nomination* page, not the *nominated* page.  This fixes that, although like #1093, in a somewhat kludgy way; anywhere else and we risk the page nomination resolving first (#1036).  Increasingly thinking the original version of #930 would be the cleaner way to handle this.
=> xfd: Fix AfD bug attempting to triage wrong page

modules/twinklexfd.js
Inline tag templates (eg. Template:Dead link, Template:More citations needed) use the class "Inline-Template". The selector `.mw-parser-output > p .Inline-Template` ensures that any inline tags used in the template documentation aren't considered.
=> xfd: tfd: auto-select type=inline for inline templates

morebits.css
Restore the original font size of 13px on the submit buttons. Missed in #1128. This was particularly conspicuous in Tag module where the "Adding x tags" text had also become much smaller.
=> morebits: restore button font size

morebits.js
Stems from #917, specifically 7a413f482 with a [blind copy](https://github.com/azatoth/twinkle/pull/917#discussion_r411278366).  We need to query if we're not on the page in question
=> morebits: Fix bug inverting whether we need to query protection status

morebits.js
When checking if the page being triaged is an appropriate namespace, use the *actual* pagename in question, rather than just assuming we're on the page: Morebits should be agnostic.
=> morebits: triage: Don't assume we're triaging the current page

morebits.js
If the page is in the queue but is already triaged, there'll be a false success.
Real pain, this action is, increasinly seemingly like the more involved #930 would be cleaner.
=> morebits: swallow fake triage success

modules/twinklefluff.js
This has been comparing a revid against a revision's `pageId` for over a decade, but `pageId` isn't part of a revision (or anything) and `pageid` would be the wrong thing to compare anyway!  I *think* it's possible there was a `pageId` parameter being returned back in the day, but there certainly isn't now.
=> fluff: Fix bug in identifying revid

morebits.js
Replaced `getUnchecked` with xor in `getChecked`, no need to be so redundant
=> morebits: remove getChecked/getUnchecked from HTMLFormElement prototype

modules/twinklebatchprotect.js
From #1074 (35ee0a6fe): turns out `result` isn't the same as `form`, and `infinity` isn't `indefinite`.  Was only affecting the initial menu selections.
=> batchprotect: Fix bug in setting defaults

.eslintrc.json, modules/twinkleprod.js, morebits.js
New task manager class (first mentioned in https://github.com/azatoth/twinkle/pull/839#issuecomment-582514117) to automatically determine the execution sequence of asynchronous functions and run them, given the list of tasks (functions returning promises) and their dependencies. 
I'll try to incorporate this into the xfd module at the first opportunity. But how to proceed is a bit unclear at the moment due to conflicts posed by #911 and #1030 (#911 isn't necessary to promisify the code in xfd module, it can also be done just putting `var def = $.Deferred()` at the top of each function and returning it).
=> morebits: add Morebits.taskManager

modules/friendlytag.js
There were two {{Do not move to Commons}} items, they've now been combined into one with a required `reason` parameter (it's not strictly required in the template, but there's a big red warning without one).  Suggested default in the tooltip.
Also added the expiry year option, alongside a bunch of excessive checks to ensure it's a valid, future year.
=> tag: Combine {{Do not move to Commons}} options, add expiry option

dev/patch-test.js
Windows doesn't support the $(...) syntax like unix shells, so we run the shell commands separately.
Also, `git merge-base $(git rev-parse --abbrev-ref HEAD) master` can be written as just `git merge-base HEAD master` so that's one less command to run.
=> Make patch-test.js work on Windows

.github/workflows/lint.yml, .travis.yml, README.md
Travis is [still running requests](https://travis-ci.org/azatoth/twinkle/requests), but the connection to the GitHub web interface recently stopped.  It's not a bad excuse to <s>play around with</s> move to GitHub's actions!  I've been thinking about doing so for a while, so why not now?  (ping @MusikAnimal )
If so, @azatoth I think you'll need to enable some options at https://github.com/azatoth/twinkle/settings/actions
If not, I think you'll have to reauthorize the connection; this is one of those things that only the repository owner can do, since this isn't [an organization](https://github.com/azatoth/twinkle/issues/1140#issuecomment-703013774).
=> Lint via GitHub actions rather than travis-ci

modules/friendlytag.js
1: For tags within {{multiple issues}}, check if the class name begins with "box-", don't just assume that it does.
2: For tags already present on the page (and not unchecked for removal), `Twinkle.tag.article.flatObject[tag]` would be undefined, and when we do `Twinkle.tag.article.flatObject[tag].excludeMI`, the result is `*_*`
=> tag: fix bugs in processing of existing tags

modules/twinkleblock.js
If a partial block with no template has been selected, turning off the partial option was resulting in a busted form, essentially an abortive attempt at creating the template section.  Simplified a few checks, although it should just all be done with `getInputData`.
=> block: Fix bug when toggling form option

modules/twinkleblock.js
The block templates ask for a duration in the `time` parameter, not a date: someone manually set an actual date as the block expiry, which is acceptable to MediaWiki, the block template would say something like `...blocked from editing for a period of April 1, 1984 13:00`.  This simply excludes the duration if the string is a valid date (thus not a duration).
=> block: Don't add expiry to template if it's a date, not a duration

morebits.js
The regex added in #1174 would match the date number, but didn't provide the leading zero needed for ISO-8601 formats.  Reported at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=987793556#Twinkle_auto-select_user_warning_level_not_working_(Again))
=> morebits: zero-pad date in constructor

modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js
It's been long desired to show the redirect CSDs on redirects nominated at RfD.  This adds detection of that box to `Morebits.wiki.isPageRedirect` and uses it in twinklespeedy.  Should also improve things elsewhere that it's used, in particular redirect tagging in the tag module.  XfD will have problems with it, namely finding the redirect target for RfD.
----
As noted in https://github.com/azatoth/twinkle/issues/1065#issuecomment-720045907, this will only work when `view`ing the page.  If we wanted to include editing, we'd have to use the page content, doing something like `document.getElementById('wpTextbox1').value.indexOf('#invoke:RfD') !== -1` or `/#redirect/i.test(document.getElementById('wpTextbox1').value)` or something.
=> Detect RfD nomination in Morebits.wiki.isPageRedirect, use in CSD

modules/twinklexfd.js, morebits.js
Original structure from #930, where we can properly asses and handle cases, rather than just swallowing all errors and avoiding stuff like #1093/#1145 and #1150.  Restore AfD's `triage` to where it (sensibly) was before #1093.
----
Per the previously convo with @siddharthvp, not sure if this is better than the current system, but figured I'd put it up for consideration.  It's an extra query if the page can be triaged, but otherwise avoids running into any errors.
=> morebits: Do triage properly, with extra query to determine if page is in queue

modules/twinklexfd.js
This is exceedingly rare on enwiki, but makes things more portable.  Previously only FfD was being handled as such, but AFAICT, only FfD has a parameter-free template: RfD and CfD have related ones, and TfD had one a decade and a half ago.
----
I've created templates on testwiki if folks wanna play around.  Right now, {{AfD log}} and {{TfD log}} hardcode the format, while {{RfD log}} and {{CfD log}} make use of pre-existing templates already in use (for better or for worse).
=> xfd: create empty log pages if bots fail/don't exist

modules/twinkleprotect.js, morebits.js
These are all incredibly minor.  tl;dr: 
- Morebits: fixes an inconsequential bug, properly detect existing cascading protection, prompt for confirmation if not `sysop` level
- protect: More accurate description of cascading protection
----
1: morebits: Don't overwrite unprovided edit protection with cascading
If someone tried to set just move protection on an unprotected page that was covered by cascading protection, we were picking up that cascading protection and pushing it into the query.  This could lead to some weird results - oddly mismatched edit/move protection, the highest protection level when none was intended - but of course it has literally never mattered since the page was covered by cascading protection anyway.  It *could* theoretically matter if cascading protection was …
=> Various fixes around cascading protection

modules/twinklexfd.js, morebits.js
There are two separate issues here, but the main question is whether adding `intestactions` to the page load query in `Morebits.wiki.page` is a good idea.  I think it adds value being able to confirm early whether an action can take place, and should avoid running into a hard error if handled elegantly.  While this is a simple proof of concept, there's a lot we can think about making use of it.  Right now, I've just added `edit`, but an expansive view could imagine checks for `move` or `delete`, whether in morebits itself or available for modules to use.  Even without additional checks, it'd be a helpful pre-edit early failure check.  I've not tested or thought through the implications for non-load things like `append`.
I've used it here to enable twinklexfd to auto-add edit protected …
=> Add intestactions to loadQuery, auto-add XfD edit request 

modules/twinkleblock.js, modules/twinkleconfig.js
Before 91ccacf, the block form would inconsistently and rarely load the prior options; I know folks were occasionally confused as to what was happening.  That commit made it never do so, as a measure of consistency.  This commit adds the prior block conditions as a new preset, which is the default selection upon form loading or action toggling.  This should restore the behavior but make it more explicit when the information is present, and more importantly allow the sysop to reliably *go back* to the prior block settins.
I've also toggled the initial loading of the form to account for partial status, although the preset itself is dynamically adjusted to account for `{{uw-block}}`, `{{uw-pblockindex}}`, etc. as appropriate.  Additionally, I've explicitly added `bkprops` so we can preload …
=> block: Favor current block information if present

modules/friendlytag.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinklespeedy.js, morebits.js
The more I look at it, the more I realize that `Morebits.wiki.isPageRedirect` fits much better with `Morebits.pageNameNorm` and the like.  Inspired by looking at #1182, which isn't a terrible time to change it.  <s>Should wait until that's resolved as this will obviously conflict.</s>
=> morebits: Rename Morebits.wiki.isPageRedirect to Morebits.isPageRedirect

modules/twinklearv.js
Reworked version of #817, simply inserting some red text if the user being reported is (already) blocked.  Closes #816.
----
@DannyS712: I just reconfigured your work there per my and @siddharthvp's comments, if you have a change to take a look over it that'd be great.  This is noted as cloing #816, but FWIW it's a note not a confirmation, and doesn't take into account a user/IP that's blocked while filing out the form.  That could be added but I didn't want to rewrite you too much.
Much like [previously](https://github.com/azatoth/twinkle/pull/817#issuecomment-584243662), I considered hiding it for SPI reports.  It's still useful information so no reason not to show it, but I would hope it wouldn't discourage folks from filing appropriate SPI reports.
=> arv: Note if reporting blocked users

modules/twinkleblock.js, modules/twinklewarn.js
There's been some discussion on this front recently (see [here](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#Warn_template_bug?_creating_unneeded_new_section_headers) and [here](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_43#Multiple_sections_for_one_month)) and I think it's reasonable to do.  The *correct* way would be to set up an additional query to `action=parse`, then go through `prop=sections`, but that seems overkill if we can just check `/\n(==+).+\1/g`.  This changes the single `pageobj.save` to either `pageobj.append` or `pageobj.newSection` as appropriate.
Note that I'm not proposing the same for the block, as I think it's less obviously useful to place a block notice anywhere but the bottom.  I did, however, restructure the block evaluation …
=> warn: Append warning to an existing section, even if it's not the last

CONTRIBUTING.md, README.md, morebits.js
Not perfect, but largely completes jsdoc documentation for the library, and does so in an exportable way (see first commit).  I've done that in two ways (2nd commit):
- HTML.  Ideally, the docs directory would be hosted via github pages (@azatoth); I've enabled it from my fork at https://amorymeltzer.github.io/twinkle/ if you want to see it.
- Markdown, via `jsdoc-to-markdown`.  I've already uploaded the results to https://github.com/azatoth/twinkle/wiki/morebits for perusal.
There are advantages to both methods, but I've found both to be helpful.  `npm run ghpages` and `npm run wiki`, or both with `npm run docs` (via `./dev/docs.sh` shim).
Another option is to *not* muddy the main branch with the output files, but host them in a separate, gh-pages branch, akin to the old-school style.
cc …
=> Expand and standardize Morebits jsdocs, export to html and markdown

modules/twinklewarn.js
`0` treated as `false`, duh.  Closes #1205 and #1206.
=> warn: Fix duplicate warning if found section is 0

morebits.js
See https://phabricator.wikimedia.org/T268513 and #1209 for more details, but basically:
- PageTriage loads an outdated version of an external library (Date.js)
- It adds *a lot* of methods to the native JS Date prototype, including a few that collide with Morebits.date
- In particular, clobbering of `add` broke `format` which broke XfD listings
This just skips importing the three that collide with us: `add`, `getDayName`, and `getMonthName`
=> morebits.date: Don't import methods that collide with PageTriage (T268513)

dev/patch-test.js, dev/server.js, package.json
The server.js file from #911. No dependencies. While it's possible to set up a server using `php -S` and `python -m SimpleHTTPServer` etc, putting it in package.json means IDEs can provide a one-click button for running it.
=> add dev/server.js

modules/twinklearv.js, modules/twinkleconfig.js, modules/twinklefluff.js, modules/twinkleimage.js, modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js, twinkle.js
This is still pretty rough — I whipped it up some time last month — but wanted to put this up as a starting point, in case there's any discussion.  Watchlist expiries in core can be tested at testWiki, but aren't enabled on enWiki (I'm not sure there's been any discussion about that process).
Basically, this:
- Adds a few default options to `watchlistEnums` in twinkleconfig
- Tweaks a few config options, even adding a few as necessary
- Overhauls how morebits handles watchlists, namely by expanding `setWatchlist` and doing away with `setWatchlistFromPreferences`.
The major sticking points are:
1. Does it work?
42. Is any of this a good idea?
42. Handling bespoke watchlist API actions (AFAICT `action=watch` has no way to default to prefs, so can either easily be *mostly* correct or rather …
=> Support for watchlist expiry

morebits.js
Potentially useful, free; mirrors `mw.config.get('wgPageContentModel')`
=> morebits: Getter for page's content model

morebits.js, tests/morebits.date.js
Allows replicating full ISO format via `.format('YYYY-MM-DDTHH:mm:ss.SSSZ', 'utc')`
=> morebits: date.format: add SSS for milliseconds fragment

morebits.js, tests/mocking/mb_repl_head.js
2nd commit uses/enforces the [newer API error messages](mediawiki.org/wiki/API:Errors_and_warnings) in `Morebits.wiki.api`, defaulting to `html`, but allowing `plaintext` and `wikitext`; `raw`, `none`, and the legacy `bc` will be converted to `html`.  Provides `errorlang: mw.config.get('wgUserLanguage')`.  Errors are limited to the first found, which was the case with the old syntax and is assumed by our uses of `errorCode`/`errorText`, but maybe something to refactor at some point (not a huge gain IMO).
The 1st commit enables the html showing up nicely, by using `$.parseHTML` in `Morebits.status.codify()`.  There's a whole long commit message, but the tl;dr is: it will now automatically parse html, not wikitext; and there's now a `statRaw` for error logging.
=> morebits: Use new error formats (default to html) in api; use $.parseHTML in status messages

morebits.js, tests/morebits.wikitext.js
I discovered this while running #1213, but it looks like the `Morebits.wikitext.parseTemplate` also includes `=` and `}}` around the final parameter in the template.  I find this hard to believe, but this has only ever been used for `deprod`, where we only ever want the `concern` parameter, which is *never* the last, so I suppose it's literally *never* come up.
<s>At any rate, this is only minimally tested (that's what #1213 is for!) and probably not great, but then again this whole thing is nearly entirely inscrutable.</s>
=> morebits.wikitext.parseTemplate: Drop = and }} for final parameter

modules/friendlytag.js
Affects {{Expand language}} only. This tag is weird in that for some reason we want to add the parameter topic= with no value into the wikitext. #1216 has a somewhat hacky way to accommodate this situation. But it had a bug in that undefined was being put into the wikitext instead of the empty string. That is, it was adding `{{Expand language|topic=undefined}}` when `{{Expand language|topic=}}` is desired.
[Example affected edit](https://en.wikipedia.org/w/index.php?title=Byron_Hyland&diff=next&oldid=919634235&diffmode=source)
=> tag: fix minor bug (from #1216)

tests/morebits.batchOperation.js, tests/morebits.date.js, tests/morebits.taskManager.js, tests/morebits.wikitext.js
Expands the `Morebits.date` tests to include some representative methods, notably: getters, `isAfter`/`isBefore`, the month header functions, and a couple non-UTC timezone formatting.  It also fixes the issue where testing the basic constructor (`new Morebits.date()` or `new Date()`) would occasionally (~0.068% of the time on my laptop) fail as the two times would be off by ` in the millisecond portion.  This creates a new assertion that allows values of +1 or -1 to pass, used just there.
The `taskManager` tests don't make use of the `steps`/`verifySteps` assertions mainly because I didn't like the way I had to duplicate function creation.
A few minor cleanups as well.
=> tests: Expand Morebits.date tests, begin basic unit tests for Morebits.taskManager

modules/twinklexfd.js
If the target's talk page is in user talk space, the notification wasn't going through, though it appears to be unintentional from the code.
=> xfd: rfd: unbreak target page notification for userspace

modules/twinklefluff.js
Viewing an oldid of a deleted page would produce an error, since it was likely editable and `wgCurRevisionId` and `wgArticleId` are both defined on `title=&oldid=844151270` urls, whereas `wgRevisionId` isn't.  It was also possible to trigger this when reviewing pending changes, although I haven't been able to replicate that for months.
=> fluff: Only try to show oldid links on pages that actually exist

morebits.js, tests/morebits.date.js
Noted at https://github.com/azatoth/twinkle/pull/1194#discussion_r525931042, basically just copied from @siddharthvp's work at mwn: https://github.com/siddharthvp/mwn/blob/7fa804354e817ae5e1d3faad9fea64e86bc0cf90/src/date.ts#L21-L25
=> morebits: Add YYYYMMDDHHmmss to morebits.date constructor

morebits.js, tests/morebits.date.js
Mediawiki will interpret extra `=`s as literal "="s in the subject, but it ain't what we're looking for.
Depends/builds on #1228
=> morebits.date.monthHeaderRegex: Require matching level markers

morebits.js, tests/morebits.wikitext.js
Okay woof, think I got most cases sorted.  *Vastly* simpler with #1213.
- Use separate var `unnamed` rather than `count` to track unnamed parameters, since templates are 1-based and are only incremented for unnamed parameters
- `.trim()` shouldn't be used on unnamed/unspecified parameters, since whitespace is passed through those
- Ignore unprovided parameters (i.e. `{{template|}}`)
- Require returning to the original `level` so as not to abort early when running into internal templates/parser functions/etc.
Like #1214, this was only ever used by twinkledeprod.js for the `reason` parameter in PROD templates, hence these not being found until now.
I tidied up some duplicate functions and added some inline comments to make it a bit more clear what is happening at each step.
=> morebits.wikitext.parseTemplate: Fixes for unnamed parameters, internal templates

modules/friendlytag.js, modules/friendlytalkback.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
Does what it says on the tin.  `xml` is still the default for `Morebits.wiki.api` for backwards compatibility, but this should convert everyone.
Not live on test.wiki since that's being actively tested, but I had it up for a month or so this fall, everything was smooth.
=> Convert all morebits/twinkle modules to use json, not xml, by default

modules/twinklearv.js
Users are smart enough to enter the page they mean, and people can edit war over a redirect.  The free entry diff is likely especially useful when no talkpage diffs are found.
=> arv: AN3: Don't follow redirects; always show resolution free entry field

modules/twinklefluff.js, modules/twinklexfd.js, morebits.js
Watchlist expiry is ideal for Twinkle since a lot of edits or taggings are transitory.  If, however, you have a page you've watched indefinitely, the API will overwrite that with the expiry settings, which is generally *not* what folks want.  Until https://phabricator.wikimedia.org/T268834, there's no reliable or convenient way to query an individual page's watchlist expiration, so for now we rely simply on whether the page is being watched or not.  It's not ideal*, but especially early on, is probably a fair assumption.  Exposed via `getWatched`.
I had thought I tested this before rollout, but it was being masked by a silly bug: for `action=watch`, it's `expiry` not `watchlistexpiry`.  Regardless, that's now fixed for the ad-hoc watching mechanisms in xfd (`mb.w.page`) and fluff …
=> morebits.wiki.page: Get watched status of page, only apply watchlist expiry if unwatched

modules/twinklexfd.js
This was [briefly discussed on WT:TW](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Move_requests_deeply_hidden), but the portlet tooltip of `Start a deletion discussion` is rarely, if ever, sufficiently accurate, and indeed elides and even hides functionality (namely, RM).  I've put the two ideas up here:
- 1st commit: `Start a discussion`
- 2nd commit: Be more specific for each venue (suggested by @siddharthvp, correct me if I misinterpreted)
I (clearly) favor the former as being simpler and not duplicating checks, but honestly the more detail from the second is probably nicer and likely to be more popular.  It'll be inaccurate if folks choose something else (or in the specific cases of things like userboxes, stubs, etc.) but by the time the module window is open, I don't think …
=> xfd: Adjust portlet tooltip to be more accurate

modules/twinklexfd.js
Put the "notifed {{user|1=USERNAME}}" text at the end – just before the reason text.
This means there's just one area in which the text is different for different modes. The variable text is sandwiched between two pieces of non-variable texts. In such a setup, it's a lot easier to provide the option for localisation.
The only downside I see is that for MfD userspace owner + creator notification, we can't say "; notified X and Y" but only "; notified X; notified Y". Not a big deal.
Also:
- added a colon after the [[page name]] before the [[nominated]] link (otherwise it seems as if "nominated" is part of the page name).
- Removed the colon before the name of the 2nd page name in CfD.
=> xfd: logging: minor tweaks

modules/twinklespeedy.js, modules/twinklexfd.js
Basically, try to deal with most of #745 as far as Twinkle is concerned (basically, not MML), albeit somewhat naïvely.  Imperfect, so wouldn't mind some feedback (cc @DannyS712 and @siddharthvp)
(1st commit: Not strictly a contentmodel issue, but post CSD on talk if can't edit (basically, #1091 but for CSD))
2nd commit: speedy: Place tag in comment block for `javascript`, `css`, and `santized-css` content models, otherwise place on talkpage (as per instructions) (scribunto already handled in #1121)
3rd commit: xfd:
- TfD: use comment block for `sanitized-css` (scribunto goes on /doc per instructions)
- MfD: use comment block for `javascript`, `css`, and `sanitized-css`
As written, depends on #1201 but need not.
=> speedy/xfd: Handle non-wikitext contentmodels

modules/friendlytag.js, modules/twinkleconfig.js, twinkle.js
Update:
Add `watchTaggedVenues` as a setValues option, similar to xfd and csd options.  Makes the most sense given parallelisms there and conversion as part of #1090.
----
There is an [on-wiki request](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#A_separate_preference_to_toggle_adding_redirects_to_watchlist_after_tagging) for this; I think it's reasonable but would welcome other input.
<s>There are two commits because I whipped it up two ways.
- The first simply adds `watchTaggedRedirects` and `watchTaggedFiles` alongside `watchTaggedPages`, and uses those for redirect and file tagging.
- The second changes the preference from a boolean to a setValue, allowing the user to select the specific modes/venues for which they want to use the watchlist, with the options being articles, …
=> tag: Offer separate watchlist options for different tagging venues

modules/twinklexfd.js, morebits.js, tests/morebits.string.js
Morebits.string.formatReasonText:
- Add a `addSig` option which appends a signature to the reason, but not if one already existed. Used in XFD module. This should remove duplicate sigs often seen in XFD nominations.
- Return empty string (or just a signature when addSig=true) if input is undefined (or null), rather than erroring out.
=> morebits/xfd: improve formatReasonText

modules/twinkleconfig.js, modules/twinkleprotect.js, twinkle.js
`watchRequestedPages`, `watchPPTaggedPages`, and `watchProtectedPages`
----
As written, dependent on #1090; it need not be.
=> protect: Add options for watching protected/requested/tagged pages

.eslintrc.json, modules/friendlytag.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinklefluff.js, modules/twinkleprod.js, modules/twinklespeedy.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
Not done in #500 given the cosmetic nature and fairly mixed status of the project, but I've run into it a few times lately and have been mildly annoyed.  Adding `"keywords": true` seems reasonable, but it's not that common and I don't think in the end we really care.  Likewise with `numbers`.
https://eslint.org/docs/rules/quote-props
Separate commit for the actual application is just to make my life easier during the eventual rebasing.
=> lint: Enforce quote-props consistent-as-needed

modules/twinkleprotect.js
#1133 was merged without fully accounting for the fact that providing a watchlist expiry would overwrite indefinite watching, which is nonideal; see #1230.  Like #1230, this is imperfect, as it only provides a boolean for watched or not, and doesn't give any information on an expiry.  We can at least rely on the information being available, though.
=> protect: Don't overwrite indefinite watching with expiry

morebits.js
This makes it possible for a morebits.wiki.page object to use an existing Morebits.status object rather than always creating a new one.
This can be done either using `.setStatusElement()` or by just providing a Morebits.status object to the constructor as second argument rather than a string.
=> morebits: page: allow binding to existing statusElement

modules/twinkleprod.js, morebits.js
Needed for taskManager to know when the logging has finished in promise-based rewrites. Resolves the kludge in twinkleprod.
Of course this would have been much simpler if Morebits.wiki.page methods themselves returned promises (#911).
=> morebits: userspaceLogger: return a promise

morebits.js
Morebits.status.info() creates a green-coloured message, which should ideally be reserved for success messages.
Blue colour is suitable for other info. The "Redirected form X to Y" message being in green, it's easy to miss among the rest.
=> morebits: use blue colour for "Redirected from" message

morebits.js
The 'l' in `ctx.lookupCreationApi` got left off in #1220 / b4a99751
=> morebits: Fix missing letter in fnLookupNonRedirectCreator

morebits.js, tests/morebits.wikitext.js
`removeTemplate` would remove any template that merely *began* with the template string provided, which could clearly cause unanticipated side effects.  Likewise, `addToImageComment` and `commentOutImage` would detect any images that began with the string provided, albeit that's less likely since there are likely fewer filename collisions.  Also added some missing tests for galleries using `commentOutImage`.
=> morebits.wikitext.page: bugfix: Exactly match templates and files

modules/twinkleblock.js, modules/twinkleprotect.js
Shows timestamp for an unblock or unprotection action, and expiry for a block or protection, but only if the user/page is not currently blocked/protected.  For protection it's not particularly smart about finding the last expiry, it just grabs the first level, which defaults to edit.  That means that if the last action was to adjust the edit protection to expire before move protection expired, this would show the wrong one.
Split off from #1183 as protect expiry is held up on https://phabricator.wikimedia.org/T267922, I believe.
=> block/protect: Show expiry/timestamp for last action (if not currently restricted)

morebits.js, tests/morebits.wikitext.js
`string.replace(text, '', 'g')` has been present in `removeTemplate`, `commentOutImage`, and `addToImageComment` for ages, but it's not a valid form of `string.replace`.  The `'g'` was being entirely ignored!  Instead of creating a `new RegExp` relying on the output from `splitWeightedByKeys`, we can just not remove the duplicated items; thus, each item refers to a single element needing action.
In theory I'd be a little wary about changing these given the off chance something was relying on them not working fully - although the initial capitalization changes would have been processed - but it's clear the intent of these was to work, so I think it's fine.  Besides, there aren't many non-Twinkle uses.  `removeTemplate` probably worked just fine if the "template" was in another namespaces, …
=> mb.wikitext.page: Fix ancient bug where multiple occurences were not being processed

modules/friendlytag.js
Reported at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=994564628#Tag_redirect)
=> tag: Fix rcat matching when 1= is explicitly used

modules/friendlytag.js
`watchTaggedPages` erroneously used instead of `watchTaggedVenues`.  Reported on WT:TW: https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=995623858#File_maintenance_tagging_not_working and https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=995623858#Redirect_tagging_getting_stuck
=> tag: Fix bug in file and redirect tagging from #1126

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkledeprod.js, modules/twinkleunlink.js
Noted at [WT:TW](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=995362073#Dbatch) by @Siddharthvp, but apparently json `formatversion=2` preferentially sorts by `pageid`, whereas xml and `formatversion=1` sorts by namespace then title.  This manually reintroduces that sorting.
Technically, it's not identical, as xml/`formatversion=1` sorts preferentially by existence, but that isn't hugely important for our purposes.
=> batch/deprod/unlink: Sort lists of pages by namespace then title

morebits.js, tests/morebits.wikitext.js
Closes #1259.  The detection of ending templates or template parameters was always `}}}` then `}}`, in order not to miss things.  This meant, however, that something like a final parameter that was itself a template (`{{42}}`) would end up at `}}}}` getting preferentially (and incorrectly) parsed as `}}}`.  There's a fair bit of cruft here, but we need to keep track of exactly what level we're in, in order to ensure we properly exit it; that means tracking any previous levels for nested items (technically, everything, since *all* parameters are nested in the actual template).  I've converted the `level` integer to an array to which we can `push` and `pop`, covering all our bases.
=> morebits.wikitext.parseTemplate: Fix bug parsing terminal template parameters

modules/twinkledeprod.js
I'm not sure there's a good reason to exclude files, but until we revamp this, this is wasteful.
=> deprod: Remove pointless searching for files since we're exlcuding them

modules/twinklearv.js
Requested at [[Special:Permalink/996949310#Spacing]] and [[Special:Permalink/997971536#Spacing between reports at WP:UAA]], follows [[WP:LISTGAP]] and [[WP:INDENTGAP]]
=> arv: Add a blank newline after UAA entries

morebits.js
Circular redirects, when followed, don't return a `pages` array.
=> morebits: Fix handling of circular redirect page load

modules/friendlytalkback.js, modules/twinklebatchdelete.js, modules/twinkleimage.js, modules/twinklespeedy.js, modules/twinklexfd.js, morebits.js, tests/morebits.js, tests/morebits.wikitext.js
We were manually checking namespaces, which was largely working fine, but was repetitive and prone to ignoring case (`Morebits.wikitext.page` methods) or alternative aliases (`Project`).  A string is more versatile than an actual regex string/RegExp object, but means that it gets fairly awkward; hence this function.  Used in file-specific regex in `Morebits.wikitext.page` methods, for which it enables `commentOutImage` and `addToImageComment` to parse images regardless of namespace or title capitalization, and in speedy, xfd, image, batchdelete, talkback, where there should be no negative change.
Second commit uses it in `removeLink`, can probably be squashed.
=> Morebits.namespaceRegex for matching all namespace capitalizations and aliases, use in morebits and modules

modules/twinklefluff.js, modules/twinkleprotect.js, modules/twinklexfd.js, morebits.js
This expands on #1230 and #1242, but with [T268834](https://phabricator.wikimedia.org/T268834) going through, we can now get an individual page's watchlist expiry upon query/`Morebits.wiki.page.load`.  As such, we can now confirm if the page is being watched temporarily or permanently, meaning we don't need to shy away from attempting to extend already-temp watched pages.
Accordingly, morebits will now take `watchlistexpiry` from page load and use it to avoid overwriting permanent watching while applying/extending temporary watching if the page is unwatched or temporarily watched.  `ctx.watched` will now either either be a boolean (as before) or, if the page is watched temporarily, a string.
The similar stuff in fluff and the `action=watch` calls in xfd and protect are likewise updated …
=> morebits/fluff/xfd/protect: Update watchlist expiry handling for expiry return after T268834

modules/twinkleblock.js
See [[Special:Permalink/1001488876#Motion: American politics 2 (1992 cutoff) enacted]] and https://en.wikipedia.org/w/index.php?oldid=1001485112#Motion:_American_politics_2_(1992_cutoff)
=> block: AP2 amended to post-1992

morebits.js
Matches others (`Morebits.status.info`, etc.) but was missing.  Largely pointless alias of `Morebits.status` itself, but, again, was missing.  Added docs for 'em all.
=> Morebits.status: Add Morebits.status.status

modules/twinklewarn.js
Inspired by https://en.wikipedia.org/wiki/Wikipedia_talk:Template_index/User_talk_namespace#Possibly_inappropriate_icon_for_Template:Uw-agf-sock (should probably hold if/until that happens); cc @Enterprisey
=> warn: move {{uw-agf-sock}} from singlewarn to singlenotice

modules/friendlytag.js
Extends hiding subheadings to redirect tagging, as they are already hidden on article tagging, and file tagging doesn't include subheadings. Partially per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=1002467677&oldid=1002159993
=> tag: Hide subheadings on quick filter

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkledeprod.js, modules/twinkleunlink.js, twinkle.js
1. batchprotect/batchundelete: Show arrow links for batchprotect and batchundelete.  Pull the `generateArrowLinks` function from batchdelete out to `Twinkle.generateArrowLinks` and use for all three `twinklebatch`- modules.
2. unlink: Link the pages being listed.  Copy what's done for deprod, pulled out into `Twinkle.generateBatchPageLinks` (cf. `Twinkle.generateArrowLinks`).
----
Personally, I'd wanted to link the pages directly (as in deprod/unlink) for all batch modules, but that leads to complications around misleading stylings for nonexistent pages as well as protection status, and I'm not sure most folks would find it overly clarifying.
=> Generate links for batchprotect/batchundelete (arrows) and unlink (title links)

twinkle.js
Remove preferences from the default config that are not used in any of the modules.
=> twinkle: Remove unused preferences from default config

modules/twinklewarn.js
When selecting a template under All warning templates, add optgroups to separate the templates by type. Partially per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk%3ATwinkle&type=revision&diff=1003158637&oldid=1003156974
=> warn: Add optgroups under All warning templates

modules/twinkleconfig.js, twinkle.js
- `watchRevertedExpiry`, `deliWatchPage`, `deliWatchUser`, `watchProdPages`, `watchSpeedyExpiry`, `watchWarnings`, `xfdWatchPage`, `xfdWatchUser`, `xfdWatchRelated`, `watchTaggedPages`, `watchMergeDiscussions` to 1 month
- `watchWelcomes` to 3 months
- `spiWatchReport`, `xfdWatchDiscussion`, `watchRequestedPages`, `watchPPTaggedPages`, and `watchProtectedPages` remain with prior values.
I think utilizing these more often would be welcome, so figured I'd propose some basic/simplistic changes.  Posted on [WT:TW](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Proposed_changes_to_default_watchlist_behavior) to get some feedback.
=> twinkle.js: Set most watchlist defaults to 1 month expiry

morebits.js, tests/morebits.date.js
<s>`localeData` needs work, but</s> Doing this makes the available units for `add` and `subtract` accessible elsewhere; since using wrong units returns an error, we had no way of checking whether we had a correct unit without hardcoding the values.
In a similar vein, also makes `Morebits.date.add` and `Morebits.date.subtract` ignore unit case.
=> morebits.date: Make unitMap available through Morebits.date.unitMap

modules/twinkleblock.js, modules/twinklewarn.js
Reduces potential confusion between "level 2 heading" and "level 2 warning" in the informational messages. Closes #1292.
=> warn & block: Change reference to "level 2 heading" to "talk page section"

twinkle.js
Not sure when this changed (somewhere in 1.36-wmf28 or 29, presumably), but looks like the top-level of the menu gained a `.mw-portlet`, which apaprently means no bullets.  See also #713 and #763.
@MusikAnimal [MoreMenu](https://github.com/wikimedia-gadgets/MoreMenu) will need an update as well, I believe.  The train has been messed up lately, but I *think* things are going forward this week so it might need to be?  29 is on testwiki, where I've just pushed this, so good for testing I guess.
(I should note that in the intervening few hours, the hover state of the vector menus at testwiki have become unrelatedly borked)
=> twinkle: Add mw-portlet class to Vector outerdiv, removes newly-(re)established bullets

tests/morebits.date.js
The existing tests fail in certain parts of the world at certain times of the day.
=> fix tests for morebits.date

modules/twinkleprod.js, modules/twinklespeedy.js, morebits.js
See RM: https://en.wikipedia.org/w/index.php?title=Template_talk:Redirect_for_discussion&oldid=1006311755#Requested_move_4_February_2021
- Module:RfD was renamed, and so was its class; `.box-RfD` thus becomes `.box-Redirect_for_discussion`
- Fix regex check for RfD nomination text in prod and speedy
cc @JJMC89 (PS you made things much smoother by cleaning up all current invocations!)
----
Will put this up now 'cause things be broke.
=> Fixes after renaming of {{Rfd}} and Module:RfD

modules/twinklewarn.js
We were only counting L2 sections, so when there were non-L2 sections present, the section index would be wrong.  Stems from introduction in  #1084, closes #1307.
=> warn: Fix bug in section insertion when non-L2 headings present

modules/twinklexfd.js
RfD nominations wrap the entire page content in a template, but the requesting template was just noting the top bit.  Everything should have worked fine, but it's Wrong.  This makes use of the new `rfd=yes` to do it Right.
----
Placeholder pending #1303
=> xfd: Use new rfd=yes parameter for {{Xfd edit protected}}

tests/morebits.string.js
There are two "infinity" tests. I think it's a typo.
=> tests: Fix typo in morebits.string tests

scripts/server.js
Setting encoding in `response.end` is not enough. I saw mojibake when I visited the script file in browser. Set encoding in Content-Type header to fix it.
=> server.js: Set encoding in content-type header

modules/friendlyshared.js, modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinkleblock.js, modules/twinklefluff.js, modules/twinklewarn.js, morebits.js, tests/morebits.js
Most of this should be straightforward, with the complicated changes mainly found in the block module.  Commits are as follows:
1. <s>fluff: Use `wgRelevantUserName` for IP ranges on contribs (#775) (Ends hacky reliance on `MediaWiki:Sp-contributions-footer-anon-range` from #476)</s> EDIT: moved to #1296
2. warn/welcome/talkback: Don't show for IP ranges (#775)
3. arv: Allow IP ranges but limit to AIV and SPI (`{{rvuser}}` doesn't support ranges) (#775)
* Builds on #817/#1184/#1204 cc @DannyS712
4. block: Enable for IP ranges, improve handling of rangeblocks (#775)
* Enable on ranges
* Leaving a template is disabled, but the "templated reason" {{rangeblock}} is used as the default
* Determine if IP is caught in a range block
* Display the range, whether it's the same block, etc.
* Use …
=> Improve and expand handling of IP ranges

modules/friendlytalkback.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinkleblock.js, modules/twinklefluff.js, modules/twinklewarn.js, morebits.js, tests/morebits.ip.js, tests/morebits.js
1. morebits: Reorganize IP utilities into Morebits.ip object
2. morebits: Add Morebits.ip.isRange to simplify use of mw.util.isIPAddress.  Equivalent to `mw.util.isIPAddress(ip, true) && !mw.util.isIPAddress(ip)` but saves us the trouble of repeating it throughout.  Used in `Morebits.ip.validCIDR` and various modules.
As discussed in #1266; with the addition of `get64` and `validCIDR`, now is the time to do this since they are obviously unused elsewhere.  Obviously a little dependent on how the feature gets implemented, but should stand.  Some interaction with #1296.
=> morebits: Reorganize ip functions into Morebits.ip, add Morebits.ip.isRange to avoid mw.util.isIPAddress

modules/twinkleblock.js
It'd be nice to do this for protect as well, but the protect and stablize logs don't show the duration so naturally, so we'd have to calculate and format it with a `timeBetween` function or something.
=> block: Show the length of the last block if it expired naturally

twinkle.js
This occurs frequently on slow internet connections. Twinkle is very much usable without the preferences so there's no need to show a jarring red message.
=> remove type=error in mw.notify on TWPREF load failures

modules/twinkleprotect.js
Add a checkbox below the "reason" textarea to allow admins to mark page protections that were requested at RfPP. When the checkbox is checked, an input appears to allow them to enter the revision ID of the RfPP page where the request was made, which will then add a permalink to the protection log entry in the format `[[Special:Permalink/{REVISION_ID}#{PAGE_NAME}]]`.
An example log entry made using this feature can be seen at https://en.wikipedia.org/w/index.php?title=Special:Log&page=Mercian+Regiment.
Give a shout if anything needs changing or cleanup; this is my first time working in this project 🙂 
Closes #1247.
=> protect: Allow admins to mark page protections that were requested at RfPP

modules/twinkleblock.js
Following from the conversation beginning at https://github.com/wikimedia-gadgets/twinkle/pull/1266#issuecomment-779498685, this changes the default behavior to leave a block template on the talk page for the IP whose talk page or contribs the block is originating from, even when the block is being applied to the /64.
=> block: Leave block template on the page of the current IP even when blocking a /64

modules/twinkleblock.js
No need to display at all to folks without the groups.  Turns increasingly-tedious `if` statement into a `switch`.
=> block: Hide rather than disable CUOS options

modules/friendlytag.js
CodeQL brought this up (https://github.com/wikimedia-gadgets/twinkle/security/code-scanning/17) and yes, this does have the potential for a catastrophic backtracking reDoS.  In practice, we're unlikely to run into it, but still.
=> tag: Avoid regex inefficiency

morebits.js, tests/morebits.date.js
There was a comment about whether to do this or not when first added (https://github.com/wikimedia-gadgets/twinkle/pull/814#discussion_r379708198), but if users pass a string they'll get some extremely unexpected behavior thanks to coercion.
`new Morebits.date('2021-01-01').add('1', 'day').toDateString()`
>Thu Oct 07 2021
`new Morebits.date('2021-01-02').add('1', 'day').toDateString()`
>Mon Jan 11 2021
=> Morebits.date.add: parseInt number to be nice, throw if NaN

modules/twinkleblock.js
As mentioned in https://github.com/wikimedia-gadgets/twinkle/pull/1266#issuecomment-779521407
----
@Molly @ToBeFree This does what I suggested as a resolution for item 1, namely uses {{rangeblock}} only for non-/64 ranges (I'm heading to bed/The Expanse but figured I could whip it up quickly for your perusal).
=> block: Only select {{rangeblock}} for non-/64 ranges

modules/twinkleprod.js, modules/twinklexfd.js, morebits.js, twinkle.js
Follows up on comments at https://github.com/wikimedia-gadgets/twinkle/issues/1047#issuecomment-671911400 cc @siddharthvp 
<s>Adds a callback option to `Morebits.wiki.preview`, then uses that to fill in xfd and prod.</s>  See below https://github.com/wikimedia-gadgets/twinkle/pull/1280#issuecomment-779032190
----
Could skip the Morebits edit and just use the api directly, but feels like we might as well use what we got.
{{Find sources}} is TE protected, but, uh, html being executed, etc.
=> Return from Morebits.wiki.preview, use to generate {{Find sources}}

modules/friendlytag.js, morebits.js
Suggested at https://github.com/wikimedia-gadgets/twinkle/pull/1293#issuecomment-778195064; the `{{Do not move to Commons}}` expiry is the only current case where we require/validate a number, I believe, although we have been using the number input type in config for a while.
=> morebits: Add number input type to quickform, use in tag

modules/twinkleblock.js
Proposed at https://en.wikipedia.org/wiki/MediaWiki_talk:Ipbreason-dropdown#Deliberately_triggering_the_edit_filter_%282%29
=> block: Reword uw-efblock reason to say 'Repeatedly triggering' rather than 'Deliberately triggering'

modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkledeprod.js, modules/twinkleunlink.js, twinkle.js
Not a big deal I suppose, but used seven times, so probably best to pull into a shared function.  Mentioned at https://github.com/wikimedia-gadgets/twinkle/pull/1251#issuecomment-748678116
=> Pull repetitive namespace-sort into Twinkle function

modules/twinkleconfig.js
Ported most of Twinkle.config.listDialog (this is the code that creates the popup dialog for editing customList type configs - such as the ones for adding custom templates) to use jQuery for UI construction rather than vanilla javascript – which is hellishly inscrutable. The jQuery rewrite is a quite more easily digestible. 
No functional changes.
=> config: partially port to use jQuery

morebits.js, tests/morebits.date.js
We only want to attempt a watchlist expiry if (1) the page isn't watched, or (2) the page is already watched temporarily; in the latter case, we probably only want extend an existing temporary watching, not shrink it.  To do that last bit properly, we needed a function to do some date calculations.  This tries not to be too over-enthusiastic, as there are plenty of valid MW expiry strings that `Morebits.date` doesn't recognize or can't `add` with.  Depends on #1298 rather than doing it itself.
One thing that needed adding, though, was parsing "weeks."  I first started writing a whole `getWeek`/`setWeek` set for ISO weeks, which largely worked, but it was really pointless since we don't really care about them per se, just as a means to an end.  For that, `*= 7` seems fine.
=> morebits: Add/subtract weeks in Morebits.date and create fnApplyWatchlistExpiry to decide whether/when to apply a watchlist expiry

modules/twinkleconfig.js, modules/twinklespeedy.js, twinkle.js
This wasn't asked for - and I don't even recommend it - but it's a hole in our preferences, especially stark since we have `deliWatchUser`.  <s>Unlike others, defaulting to `nochange` since that's the current practice.  That being said, we could default to `1 month` to match the new temporary settings in #1249?  I might lean that way, minimal impact in the end.</s>  I've done this, defaulting to `1 month` to match `deliWatchUser` (and `xfdWatchUser`) after #1249.
=> speedy: Add preference to watchlist user page on notification

morebits.js
`lookupCreation` would often leave a hanging status message when used on a new/separate instance of `Morebits.wiki.page` since we were never actually registering a success.  When using the original page object, things would be fine, since the corresponding method would typically pick up the slack.  Fixes #1049.
=> morebits: Update statusElement on successful lookupCreation

modules/friendlytag.js
Otherwise you get "Tagging article" associated with the lookup message, which doesn't make much sense.  Especially improved along with #1339.
=> tag: Use separate mb.w.page instance for lookup

morebits.css
The label for a checkbox or radio button was abutting just too close to the box/button on Vector/Timeless/Monobook (not Modern?), this should space them out a little more clearly.
=> morebits.css: Add 2px margin-right to checkboxes, clearer spacing between elements

modules/friendlytalkback.js, modules/twinkleconfig.js
Coallesces the three {{talkback}} options into one, with the location defaulting to your own user talk page for {{talkback}} and {{please see}}, aka roughly what was suggested at https://github.com/wikimedia-gadgets/twinkle/pull/929#issuecomment-707630150 by @sidarthvp, less the {{whisperback}}-related stuff.  Ensures only project- and talkspaces will be used.
{{whisperback}} might still be good to add, though I haven't looked much since it was merged and became a wrapper.
=> talkback: Simplify menu a bit, reducing redundant talkback items

modules/twinkleprod.js, modules/twinklespeedy.js, morebits.js
The module rename was reverted due to causing issues with XfDcloser.
This reverts commit 61cace2eb53da954806f75161eccb53842c3a48c.
=> Revert "Fixes after renaming of {{Rfd}} and Module:RfD"

modules/twinkleimage.js, modules/twinklespeedy.js
Incredibly premature, but tracking https://en.wikipedia.org/wiki/Wikipedia_talk:Criteria_for_speedy_deletion#RfC:_Deprecate_criterion_a._from_F7
=> speedy: F7a (immediate deletion of invalid fair-use tag) removed after RfC

modules/friendlytag.js
Since we're using the existing tags directly to create the regex, any tag with a parameter would lead to issues given the unescaped `|`.  Reported at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=1013238981#Redirect_tagging_bug).
=> tag: Escape redirect tags when creating regex

morebits.js
Deprecated six months ago in #1077 in favor of `Morebits.string.escapeRegExp`, see #910
=> morebits: Remove deprecated RegExp.escape

morebits.js
Already allowed in `div`, now done in `select`, `field`, `checkbox`/`radio`, `input`, `textarea`, `header`, and `dyninput`.
`option`, `optgroup`, `_dyninput_element`, `submit`, and `button` don't really make sense; neither does `type=header` in `checkbox`/`radio`.
=> morebits: Allow html in labels for most quickForm element types

morebits.js, tests/mocking/mb_repl_head.js, tests/morebits.createHtml.js
Makes it much easier to include wikilinks in status messages and quickForm labels. Also de-duplicates some code in the two clases.
If literal `[[...]]` are to be included in status for whatever reason, that can still be done using the HTML entities `&#91;&#91;...&#93;&#93;`
$.parseHTML() removes <script> tags in the parsed output, so there should be no security issues.
A `Morebits.createHtml` function is added. This obsoletes `Morebits.status.prototype.codify` which is hence removed.
----
2nd commit: morebits: createHtml: sanitize html attributes 
Removes attributes that are used for executing scripts (onclick, onerror, etc). Also disallows anything that isn't a text node or Element node.
=> morebits: render wikilink syntax and sanitize HTML in status and quickForm labels

morebits.js
Adds `Morebits.i18n` which allows plugging in an i18n library through which localised messages can be provided.
The English fallbacks continue to be part of the source code so for using morebits in English no i18n library is required. That is, the changes here are backward-compatible.
Messages in code now become:
```js
msg('msg-name', ...messageParams, fallbackEnglishMessage)
```
where the `fallbackEnglishMessage` is a string that directly uses the message params. That is, it is
```js
msg('deleting-pages', numPages, 'Deleting ' + numPages + ' page' + (numPages > 1 ? 's ' : ' '))
```
instead of
```js
msg('deleting-pages', numPages, 'Deleting $1 {{plural:$1|page|pages}}'
```
The latter would have been nicer but for that I'd have to rewrite all the messages and also then an i18n library …
=> add i18n support for morebits

morebits.js, tests/morebits.createHtml.js
Since code tags are used for displaying wiki-code (such as in unlink module).
=> morebits: createHtml: don't render wikilinks inside <code> tags

modules/twinkleconfig.js, twinkle.css
There is 1 space after the checkboxes for type=boolean. But no spaces for type=enum.
So remove the space from type=boolean and use css to add margin to all checkboxes.
Similar to #1331
=> twinkle.css: Add 2px margin-right to checkboxes in prefs

modules/twinkleunlink.js, morebits.css
This applies to `<code>` elements within quickform divs, which should be shown in monospace font without italicisation.
=> move some css to morebits.css, rather than embed in js

modules/friendlytag.js
Per https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Redirect_tagging_doesn't_include_{{R_to_subpage}}
=> tag: Add R to subpage

morebits.js
Till now there has been the the quickForm extra attribute which allowed attaching arbitrary data to DOM nodes. But this is discouraged for many reasons (https://stackoverflow.com/questions/7895560/javascript-dom-setting-custom-dom-element-properties, https://stackoverflow.com/questions/3095336/is-it-bad-practice-to-add-properties-to-dom-nodes).
Using JQuery data (https://api.jquery.com/data/) is better.
Support for `extra` attribute is nevertheless retained, though this is unused in Twinkle.
=> morebits: add $data attribute for quickForm elements

morebits.js, tests/morebits.createHtml.js
No longer necessary to do this at runtime since twinkle-core now uses a script (https://github.com/wikimedia-gadgets/twinkle-core/blob/master/scripts/build-i18n.js) to sanitise messages at the build step itself, which is even better at sanitising than this code here. <script> tags are still removed here as that's a built into $.parseHTML().
Some of tests added in that commit are retained.
=> Revert "morebits: createHtml: sanitize html attributes"

modules/friendlytag.js, modules/friendlywelcome.js, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleimage.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkleunlink.js, modules/twinklexfd.js, morebits.js
For almost every input field label, such a margin was being artificially added till now by ending the label with a trailing space.
However, trailing spaces are not allowed on translatewiki.net (technical limitation) and so needs to be written as `&#32;` (https://phabricator.wikimedia.org/T278627#7019324) which unnecessarily obfuscates so many messages.
=> morebits: put 3px margin after input labels

modules/friendlytalkback.js, modules/twinkleconfig.js
This was added in 2010 ([sysop-only link](https://en.wikipedia.org/w/index.php?title=Special:Undelete&target=User:Ioeth/friendlytalkback.js&timestamp=20100623142531&diff=prev)) to fix an issue with the [old Friendly documentation](https://en.wikipedia.org/w/index.php?title=Wikipedia:Friendly&oldid=410035412#Parameter_Descriptions).  In an ideal world, we'd have ways to clean up erroneous entries in preferences, but for this, I think we can remove it.  There are, on enWiki, on [five instances](https://en.wikipedia.org/w/index.php?title=Special:Search&limit=250&offset=0&ns2=1&sort=last_edit_desc&search=insource:/talkbackHeading/+intitle:twinkleoptions&advancedSearc$), with only three of those editors active.  I can ping them or clean those up directly, but I don't think we need to hold on …
=> talkback: Remove cleanup for talkbackHeading prefs with erroneous equals signs

modules/twinkleblock.js, modules/twinkleconfig.js, twinkle.js
Originally suggested at https://github.com/wikimedia-gadgets/twinkle/pull/1266#issue-551310264
=> block: Add option to default to blocking the /64, off by default

morebits.js
Wiki-specific configurations for Morebits.
These are initialised to English/Enwiki defaults, but can be over-written by other wikis' from Twinkle configuration files. That is, Morebits can be used across all wikis with just a few config overrides, without the source code itself needing to be modified. 
----
Currently contains `signatureTimestampFormat` (was formerly Morebits.data.localeData.signatureTimestampFormat) and `redirectTagAliases` (used in lookupCreation).
=> add Morebits.l10n

morebits.js
The Select2 search box no longer gets focused when opened due to a jQuery 3.6.0 regression.
https://github.com/select2/select2/issues/5993
https://github.com/jquery/jquery/pull/4885
First reported here:
https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=1024931585#Warning_template_filter_no_longer_gets_focused
=> Use DOM .focus() instead of jQuery

modules/twinkleprotect.js
Fixes #1432
This change means that subpages of AfD will have the checkbox ticked by default which wraps the page protection icon in a noinclude. See #1432 for why this is needed.
This change does that by checking if both the page namespace number is the project space number as defined by wgNamespaceIds and that wgTitle starts with "Articles for deletion/". I've not used the startsWith as it is not supported by IE 11 (and as far as I am aware Twinkle supports IE 11). Instead I checked to see if the string "Articles for deletion/" is found at index 0 inside wgTitle. If the index is 0, then the page name begins with the string and is a subpage of AfD. If it is not zero (i.e. -1 or above 0) then the check fails, and therefore is not a subpage of AfD.
=> Tick the noinclude box when protecting a subpage of AfD

modules/twinklefluff.js
=> fluff: make rollback links and separators selectable via CSS

CONTRIBUTING.md, scripts/dev-server.js
CONTRIBUTING.md changes:
- mention the new dev-server.js script as the tool for testing. Remove mention of the patch-test.js script which is harder to use and more prone to issues.
- Suggest using testwiki more clearly.
- Omit "a good policy is that every commit should be capable of replacing the live on-wiki Gadget file for all users" -- while that likely is a good policy, that exceeds expectations and IMO unnecessary.
Cc: @TheTVExpert @ToBeFree @Trialpears let's discuss if there's anything else in the way of scripts/documentation that can make twinkle development easier.
=> Changes to CONTRIBUTING.md about testing

modules/twinklespeedy.js
In MediaWiki, `#ca-talk` (talk page tab) now carries `mw-list-item` class which is always present. So, straight className matching won't work.
=> speedy: fix talk page deletion condition

morebits.js
Undefined `data.label` was crashing PROD module before even the window is displayed.
=> morebits: quickform: handle undefined label to fix bug in PROD

twinkle.js
Vector has changed the portlet HTML (again) and now requires
.vector-menu-dropdown-noicon for the portlet to display properly in
Vector and New Vector.
https://phabricator.wikimedia.org/T290994
=> twinkle: add class to vector dropdown

modules/twinklewarn.js
Fixing two issues:
- The uw-paidX templates are about a concern usually based on off-wiki evidence, and about a topic with legal implications. The template language is very carefully crafted not to directly state the apparent TOU violation as a fact, as doing so could be libellous, and as actual evidence of intentional disclosure omission would have to be handled by administrative action instead of a warning. Yet: The edit summary currently doesn't share this caution.
- The conflict of interest guideline is not a policy.
=> twinklewarn: Improve edit summaries for uw-paidX and uw-coi-username

modules/twinkleprod.js
Reported at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#"prod"_doesn't_work_when_{{deleted_on_Commons}}_is_present
=> prod: adjust deletion tag regex to avoid matching {{Deleted on Commons}}

modules/friendlytag.js
Fixes #1401 Merged {{r from former name}} and {{r from historic name}}
{{R from former name}} was kept, {{R from historic name}} was redirected to {{R from former name}}. Therefore it seems like the easiest fix for this is to delete {{R from historic name}}.
=> tag: remove {{r from historic name}}

modules/twinklearv.js
Fixes #1473 arv: remove the SPI notification checkbox
=> arv: remove the SPI notification checkbox

scripts/dev-server.js
As many features are not applicable to non-sysops, this aids testing of those features by non-sysops. This is done by default but can be turned off with `--no-sysop` flag. (Use as `node server.js --no-sysop` or `npm start -- --no-sysop`)
=> dev-server: modify wgUserGroups to add sysop

modules/twinklearv.js
In the AN3 modal, change "User's reverts" to "User's reverts (within last 48 hours)".
This is more intuitive to the user, as they may wonder why there are no reverts showing up in the box if they try to use it after 48 hours.
This happened to me while working on a bug report, and it took me awhile to track this down.
=> arv: improve AN3 explanation text

modules/twinklexfd.js
Fixes #1486 xfd: place new TFDs at bottom of TFD daily log page, not at top
=> xfd: place new TFDs at bottom of TFD daily log page, not at top

modules/friendlytalkback.js
- Renames OTRS to VRT, bringing Twinkle into alignment with the rename that happened onwiki.
- Fixes an issue with [Template:VRTreply](https://en.wikipedia.org/wiki/Template:VRTreply) signatures showing up as ~~~~ instead of the user's signature. I modified the template onwiki and also Twinkle's code to get this working.
=> tb: rename OTRS noticeboard to VRT noticeboard

modules/twinklexfd.js
Twinkle bug. Reported here: https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#2015th_nomination
Steps to reproduce:
- Create article Test (2000)
- Create article Wikipedia:Articles for deletion/Test (2000)
- Use Twinkle->XFD->AFD on article Test (2000). It will create an AFD called Wikipedia:Articles for deletion/Test (2001st nomination)
There's a complex RegEx that accepts (2000) and (2000th nom) and (2000th nomination). I hesitate to change it because if someone bothered to code it that way, these are probably AFD formats that were used in the past.
Instead, I opted to institute a maximum AFD number. I set 100 as the max. This should eliminate most year false positives.
=> xfd: fix "2nd AFD of article ending in number" bug

modules/friendlytalkback.js
Fixes this incorrect description. WP:NORN is not the reliable sources noticeboard. It is the no original research noticeboard.
=> tb: fix WP:NORN description

modules/friendlywelcome.js
Reported at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Welcome_messages_added_above_%22Talk_header%22
If you have the Twinkle preference topWelcomes set, and you try to place a welcome message on a page with {{Talk header}}, the order ends up being `welcomeText + {{Talk header}} + text`.
This patch fixes the order for simple cases.
=> welcome: fix topWelcomes placement bug

modules/friendlywelcome.js
Fixes #1406 Remove welcome-graphical, welcome-menu, and welcome-screen, and add welcoming
I also split "General welcome templates" into two groups: "General welcome templates" and "Specific welcome templates".
=> welcome: remove 3, add 1, split a group into two groups

modules/twinkleblock.js, modules/twinklexfd.js, morebits.js
- Fixes #1477 Read discretionary sanctions information from a wiki page
- I created the function `Morebits.wiki.getCachedWikitext(title, description, parent, callback)`, and I refactored the code to use the function in 3 places.
- I created https://en.wikipedia.org/wiki/Template:Ds/topics.json
- I added COVID-19 and Longevity to the list of discretionary sanctions
=> block: read discretionary sanctions information from a wiki page

modules/twinklearv.js
Causes excess rendered whitespace, and does not appear to be necessary for any formatting reason,
See e.g. https://en.wikipedia.org/w/index.php?oldid=1067910626 for excess whitespace before every section. N.B.: There was previously a template issue that was causing this to be even worse in the first section. I fixed that with https://en.wikipedia.org/w/index.php?diff=prev&oldid=1068308120.
=> Remove one of the two newlines before SPI report

modules/twinkleprod.js
Around New Year's Day every year, I always archive the CSD and PROD logs for the previous year prior to finding the first pages to tag for CSD and PROD respectively in the new year. In the case of the PROD log, I always have to remove an extra newline while transcluding the list of years on top of the log. This is annoying, so I am removing the extra newline in this commit so that there is just one blank line rather than two between "If you no longer wish to keep this log, you can turn it off using the [[Wikipedia:Twinkle/Preferences|preferences panel]], and nominate this page for speedy deletion under [[WP:CSD#U1|CSD U1]]." and "=== Month Year ===" on the PROD log page.
=> Remove unneeded extra newline

twinkle.js
Changes in [T290280](https://phabricator.wikimedia.org/T290280) (ab11cc9adb8124d93659aca6491b36298d5dc27a) broke the
styling for the Vector dropdown menu. Adding vector-menu-heading is
required now for correct styling. The h3 element is still used for
Timeless compatibility.
=> twinkle.js: add vector-menu-heading to vector dropdown label

modules/twinklexfd.js
Reverts wikimedia-gadgets/twinkle#1487
Per outcome of RFC at https://en.wikipedia.org/wiki/Wikipedia_talk:Templates_for_discussion#RfC:_Should_new_nominations_be_placed_at_top_or_bottom_of_daily_subpage?
=> Revert "xfd: place new TFDs at bottom of TFD daily log page, not at top"

morebits.js, tests/morebits.wikitext.js
Fixes #1503 unlink: mainspace pages with colon are parsed incorrectly
=> unlink: fix colon in title bug

modules/friendlywelcome.js
Related #1463. Partial revert.
Tested. Besides the revert, changed code to use welcome templates directly instead of redirects.
Requested onwiki: https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Welcome-menu_template_missing_from_the_latest_iteration_of_the_drop-down_welcome_menu
=> add back 2 welcome templates

.github/labels.yml
I notice we're missing a "Module: diff" label, so I went ahead and created it. This PR teaches the GitHub Actions labeler about this new label.
=> GitHub Actions: tag changes to twinklediff.js

modules/twinklexfd.js
The talk page name is kept the same because it is currently a redirect; it can be changed in a later commit.
=> Rename usage of Ultraviolet to RedWarn

scripts/dev-server.js
There is a SyntaxError in the dev version of Twinkle if you add any apostrophe in morebits.css. For example, if you want to add a comment such as `/* Don't do this. */`
This patch escapes single apostrophes, fixing the issue.
=> dev-server: fix single apostrophes in CSS bug

modules/twinklespeedy.js
Fixes #1427 All CSD tagged articles getting added to watchlist, despite selecting "don't add to watchlist"
Also fixes a bug where all CSD watchlisting was permanent, instead of taking into account the duration set in the user's preferences.
=> speedy: fix bugs involving watchlist preferences

modules/twinklediff.js
Use robuster way to get revision id. And wgDiffNewId is missing on deleted diff, fix #1561
=> diff: Use mw.config to get revision id

modules/friendlytag.js
For increased visibility. I didn't know this feature existed because it was hiding at the bottom. Also it is checked by default... if adding a tag is going to mark a page as reviewed by default, I want to know about it so I can uncheck it, as I may tag some pages without doing a complete notability review.
=> tag: move "Mark the page as patrolled/reviewed" to top

modules/twinkleconfig.js, morebits.css
Requested by Izno at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#ombox_use_in_MediaWiki:Gadget-twinkleconfig.js
There is a message box in Twinkle that uses MediaWiki's ombox CSS class, but this will be deprecated soon. This patch copies the styling for this to Twinkle's morebits CSS stylesheet, eliminating a dependency.
Could potentially add all the ombox styles, but I decided to just add the ones we use.
=> config: handle ombox deprecation

modules/friendlytag.js
Adding support for the suggested `part` and `reason` parameters of `{{update}}`. Tested on [the test wiki](https://test.wikipedia.org/w/index.php?title=Watty62_test&action=history).
=> tag: add part and reason params for {{update}}

modules/twinkleprod.js
Requested by Robert McClenon at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Stupid_Message_on_BLPPROD
Was unable to reproduce this one due to some kind of bug in the code. Even though my test article was older than 3 days, `isMoreThan3DaysOld` was returning false.
Easy enough to delete the offending code though.
=> prod: remove blpprod warning

modules/twinklexfd.js
I originally got "Notify users of the template" confused with "Notify page creator if possible". I have modified the text of the check box ("Notify users of the template") and the tooltip to be a bit clearer.
=> xfd: clearer wording for "Notify users of the template"

twinkle.js
For user warnings, current default "warning group" is "level 1". This patch changes the default warning group to "all warning templates". I feel this is more intuitive, and saves a couple clicks when the user wants to select a non-level 1 warning template.
User can custom configure this in their preferences too, if they don't like the default.
I think `11: 'Auto-select level (1-4)'` would also be a reasonable default warning group, but I slightly prefer "all".
=> twinkle: change default warn from "level 1" to "all"

modules/friendlytag.js
In code like this:
````
form.append({
type: 'input',
label: 'Reason',
name: 'reason',
tooltip: 'Optional reason to be appended in edit summary. Recommended when removing tags.',
size: '60px'
});
````
The px is incorrect. The form item isn't 60 pixels high or wide, it is 60 characters wide. The px can be deleted.
https://www.w3schools.com/tags/att_input_size.asp
=> tag: remove px from form.size

modules/twinklefluff.js
https://en.wikipedia.org/w/index.php?title=Wikipedia&action=history
"First link" now wrapped by `<span>` with `.mw-firstlink` class on the first page of history. Use `a.mw-firstlink` to check clickable firstlink.
With this patch:
=> fluff: Fix rollback links for top rev in history

.github/workflows/unit_tests.yml, jest.config.js, modules/twinklewarn.js, tests/jest.setup.js, tests/twinklewarn.test.js
Fixes #1408
Fixes #1538
Related #1537
When warning a user with `uw-editsummary2`, hides the "linked page" and "reason" text boxes.
I also created infrastructure to easily mark other templates with `hideLinkedPage` and `hideReason`, if we need to in the future.
I also added unit tests. I changed some unit test configuration files so that in the future, if we want to unit test modules, it will be easier.
Also renamed a couple variables.
=> warn: ability to hide linked article and reason

morebits.js
Some additional ResourceLoader modules may be required for parsed wikitext to be rendered correctly. See matmarex's comment in https://phabricator.wikimedia.org/T292345#7399140.
This fixes the stray `[]` appearing at the end of comments (they now get hidden with CSS loaded from DiscussionTools). Reported at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Bug:_preview_of_CfD/S_has_trailing_brackets. 
Also added `preview` and `disableeditsection` flags to preview API.
=> morebits: load RL modules required for previews

morebits.js
In #1179, support for new error formats were added and used by default. However, the error handling code still assumes the legacy errorformat, which passes details of the first `error`, while in the newer ones we have an array `errors`.
Notes for testing:
On testwiki, add text "Trigger abuse filter warn" to any page (it triggers https://test.wikipedia.org/wiki/Special:AbuseFilter/256):
```js
var p = new Morebits.wiki.page('SD0001test', '');
p.setAppendText('trigger abuse filter warn');
p.setEditSummary('edit summary');
p.append();
```
Without this patch, we get:
The TypeError prevents any failure handling callback from running (one of the reasons why the callback approach is sub-optimal and we should be using promises everywhere).
=> morebits: fix handling of hard errors

modules/twinkleprod.js
By my reading, applying a prod to a page tagged with CSD is is allowed per WP:PROD. But Twinkle currently checks for a CSD template on the article page while prodding, and if detected, aborts the prod.
=> prod: should allow prod even if CSD template present

morebits.js
This reverts commit c6f2bd4f3809e3f59124949d31c791923d4a93f1.
The linked phab task has been resolved now - PageTriage is no longer using date.js external which messes up `Date.prototype`.
=> Revert "morebits.date: Don't import methods that collide with PageTriage (T268513)"

modules/twinklexfd.js
Requested by LaundryPizza03 at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#RM/TR
Changing the wikicode comment at https://en.wikipedia.org/wiki/Wikipedia:Requested_moves/Technical_requests#Uncontroversial_technical_requests breaks Twinkle. I've rewritten the RegEx to be a little more forgiving about when this comment is changed.
I used a not-so-pretty `(?:.|\n)` hack to get around ES5's lack of RegEx /s support.
Test case 1 (original, works with old and new code):
Test case 2 (new, works with new code only):
=> xfd: better targeting for RM/TR

modules/twinkleprotect.js
We shouldn't be leaving this newline behind when removing protection templates from sanitized-css:
https://test.wikipedia.org/w/index.php?title=Template:Contains_special_characters/styles.css&diff=538979&oldid=538978
=> protect: sanitized-css: remove newlines when removing protection template

modules/twinklearv.js
Requested by Blaze Wolf and KylieTastic at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#%22Username_implies_shared_use%22
Removes "Username that implies shared use" option from ARV -> UAA, because this is not normally severe enough to report at [[WP:UAA]].
Also refactored a bit.
Also fixed a bug where Twinkle would place two periods sometimes when writing [[WP:UAA]] entries.
=> arv: remove "implies shared use"

modules/twinkleconfig.js, twinkle.js
Requested by Blaze Wolf, MB, and CX Zoom at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Default_preferences
For CSD R3, have "welcome page creator", "notify page creator when tagging", and "notify page creator when deleting" default to true instead of false.
Also refactor one vague variable name.
=> twinkle: notifications for CSD R3 should default to true

modules/friendlytag.js
Requested by Qwerfjkl at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Adding_rcat_shell
Steps to reproduce:
* Create page with wikicode
```
#REDIRECT [[Gator In The Bay]]
{{R from miscapitalisation}}
```
* Twinkle -> Tag -> check "R from miscapitalization" -> submit
Before patch:
After patch:
=> tag: better edit summary for {{rcat shell}}

modules/twinkleblock.js
"WP:Vandalism-only account" is an essay, "WP:DISRUPTONLY" is a policy section.
=> twinkleblock: "Vandalism-only account": Link to policy rather than essay

package-lock.json
I probably should have done this in #1652 but I forgot
This is the result of running `npm install` instead of `npm ci`. This puts package-lock.json in alignment with package.json, without bumping any versions. Should be a no-op.
=> update package-lock.json to be in sync with package.json

twinkle.js
Co-authored-by: @MusikAnimal
Bug report: https://en.wikipedia.org/wiki/Wikipedia:Village_pump_(technical)#Styling_for_the_TW_menu_gone%3F
MusikAnimal's hotfix: https://en.wikipedia.org/w/index.php?diff=1131811156
I also refactored this because I found it unreadable. The hotfix (included in this patch) is adding a "vector-dropdown" class when appropriate. The rest of the code changes (the refactoring) should be a no-op.
=> fix "more" menu's styling in skin vector-2022

twinkle.css
Fix #1674
This has a side effect of also making the "More" menu stay open on hover in vector-2022. Not sure if this is desirable, or if we should change the CSS to target the TW menu only.
=> twinkle: vector-2022: hovering should open menu

modules/twinklexfd.js
Requested by CX Zoom at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Minor_feature_request%3A_Jump_to_section_from_XFD_edit_summary
1) For TFD, include a link to the daily log page section in the edit summary for the daily log page.
2) For TFD, include a link to the daily log page section in the edit summary for the Twinkle user log page.
=> xfd: edit summaries should include log page section links

.eslintrc.json, modules/twinkleblock.js, morebits.js
Suggested in #1693
Have our linter disallow stuff like this, for readability reasons:
```
outerNavClass = navigation === 'mw-panel' ? 'portal' : type === 'menu' ? 'dropdown vector-menu-dropdown-noicon' : 'tabs';
=> eslint: disallow nested ternaries

jest.config.js
The unit test code coverage report was not displaying files that had no tests. I think it's better to include all files, to capture the reality of our testing situation.
Before patch:
After patch:
=> jest: fix missing files in code coverage report

modules/friendlytag.js
Fix #1573
<s>Not working yet. Because of async, form is rendered before the "Mark the page as patrolled/reviewed" checkbox is appended.
Perhaps the pagetriagelist API query needs to run before friendlytagCallback(). Any suggestions on how to set that up? I'm good at async/await, but not so good at promises and callbacks.</s>
=> tag: better detection of "not marked as reviewed"

.gitignore
Will fix /coverage/ files showing up in my VS Code when I search all files in the repo. VS Code not smart enough to read my global .gitignore for this.
/coverage/ is created when you run a jest unit test code coverage report.
=> gitignore: add coverage folder

modules/twinklefluff.js
Rollback links navigated to the URL + `#`, cluttering your browser history.
=> fluff: Add preventDefault to rollback links

modules/twinklewarn.js
Requested by @nardog at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#%22including_unpublished_syntheses_of_sources%22
Deleted text isn't found in the {{Uw-nor}} text. I see no reason not to shorten it.
=> warn: shorten {{Uw-nor}} edit summary

.eslintrc.json
eslint: warn when using .done() or .fail()
Using .done() and .fail() is a bad habit and can introduce extremely subtle bugs. [T238025](https://phabricator.wikimedia.org/T238025) comes to mind. That took years to track down the bug.
This repo doesn't have enough automated tests for me to feel comfortable doing mass refactoring. So setting to "warn" for now instead of "error".
=> eslint: warn when using .done() or .fail()

morebits.js
These allow for deleting/undeleting talk page along with the subject page in a single request, improving performance.
Partially addresses #1705.
=> morebits: support deletetalk/undeletetalk API options

twinkle.js
Applying a maintenance tag does not usually mean that the article has been thoroughly reviewed by the NPP. This assumption that "maintenance tag = NPP wants to mark it as reviewed" seems false to me.
This patch changes the default from true to false.
Users can always go into their preferences and change it back to true.
=> set markTaggedPagesAsPatrolled default to false

modules/twinklearv.js
A few months ago there was a decision at [TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2022_October_17#Template:IPvandal) to merge the Vandal and IPvandal templates used for reporting at AIV. The template itself can now detect if it is an ip or not and serve the links accordingly. This pull request makes it so twinkle always uses vandal. [Tested](https://en.wikipedia.org/w/index.php?title=Wikipedia:Administrator_intervention_against_vandalism&diff=prev&oldid=1140900978) and working.
=> Implement merger of vandal and ipvandal templates

modules/friendlytag.js
PR #1667 that was just merged has a bug in it. I thought of the bug after merging it. The bug is that, in the tag module, "mark as reviewed" shows up for non-patrollers. The fix in this patch is...
```
let isPatroller = mw.config.get('wgUserGroups').some(r => ['patroller', 'sysop'].includes(r));`
if (isPatroller) {
// do stuff
}
=> tag: fix bug where "mark as reviewed" shows up for everyone

modules/twinklexfd.js
Reported by LaundryPizza03 at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Incorrect_link_in_CfDS_edit_summary
Fixes a regression introduced in #1684
=> xfd: fix "undefined" error in userspace log XfD CfDS edit summary

modules/twinkleblock.js
Reported by Mori Calliope fan at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#uw-botuhblock_produces_an_extra_period_in_the_edit_summary
Fix double period in {{uw-botuhblock}} edit summary
Untested since I don't want to hard block myself, but should be a low risk change
=> block: fix extra period in {{uw-botuhblock}} edit summary

modules/twinklewarn.js
If merged, this will change the edit summary for uw-wrongsummary from "Warning: Using inaccurate or inappropriate edit summaries" to "Notice: Using inaccurate or inappropriate edit summaries" for consistency with the rest of the single notices
=> warn: fix edit summary for uw-wrongsummary

.github/workflows/unit_tests.yml
Fix #1778
It is cheap to run these, it would help detect breakage of the unit test suite quicker, and if we ever add integration tests or unit tests of additional modules, it would make sure these run for those.
=> ci: always run unit tests

package-lock.json, package.json, tests/__snapshots__/morebits.quickForm.js.snap
- bump jest from v27 to v29
- bump mock-mediawiki to v1.4.0
- install jest-environment-jsdom, needed for jest v29 to work
- adjust snapshot test syntax a bit, to work with jest v29
=> bump jest from v27 to v29

package-lock.json
Now that we're finally on the latest version of Jest, it should be safe to update all our npm dependencies.
These are all **dev** dependencies and have no chance of breaking the Twinkle build used on-wiki.
Since these are all dev dependencies, the only testing needed should be 1) make sure CI passes and 2) make sure `npm start` works.
Tested, works.
=> `npm update` everything

twinkle.css
Hotfix for https://phabricator.wikimedia.org/T337893. Already deployed by @MusikAnimal
Co-authored-by: MusikAnimal
=> fix twinkle menu background on vector-2022 zebra

modules/friendlywelcome.js, modules/twinkleconfig.js
I had to dig into this code to explore a bug, and I found it confusing. This renames some variables, and changes the wording of some things on the Wikipedia:Twinkle/Preferences screen. Should be no change in functionality.
=> diff/welcome: readability refactor

modules/friendlytag.js
Fixes #1459 Fix redirect category namespace detection
I found 184 {{R to/from X}} style redirect tags that are namespace-specific. This PR codes Twinkle to not display these unless it is the correct namespace.
I copy/pasted a utility function from Stack Overflow, and used a comment with a URL as attribution.
Here's a couple test cases to check:
````
var insideMainspaceOnly = [
'R from acronym',
];
var insideTalkNamespaceOnly = [
'R from remote talk page'
];
var disambiguationPagesOnly = [
'R to disambiguation page'
];
var outsideUserspaceOnly = [
'R to user namespace'
];
````
=> tag: add namespace rules for redirect tags

modules/twinkleprotect.js
Don't tick the "Wrap protection template with `<noinclude>`" check box by default if the content model is css, sanitized-css, or javascript.
=> protect: sanitized-css: don't tick <noinclude> check box

twinkle.js
Requested by DB1729 at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#%22Notify_page_creator_if_possible%22
For CSD C1, have "welcome page creator", "notify page creator when tagging", and "notify page creator when deleting" default to true instead of false.
=> twinkle: notifications for CSD C1 should default to true

modules/friendlytag.js
Added media redirect templates (band name, cover song, journal, lyric, meme, television program, upcoming film, work) and emoji redirect template.
=> Added media related and emoji redirect templates

modules/twinklearv.js
Closes #1714 which is about some aiv reports including ":.". This can be reproduced ([example](https://test.wikipedia.org/w/index.php?title=Wikipedia:Administrator_intervention_against_vandalism&diff=prev&oldid=559081)) by giving a diff and no type. [Here](https://test.wikipedia.org/w/index.php?title=Wikipedia:Administrator_intervention_against_vandalism&oldid=559097) are tests for all three cases, reason needing to be terminated, reason not needing to be terminated and reason being empty until the comment is added.
=> Fix double punctuation issues at AIV

modules/friendlytag.js
=> tag: fix pagetriagelist API undefined error

modules/friendlytag.js
Will add the templates {{r from airport code}] and {{r from airline code}}
=> tag: add {{r from airport code}} and {{r from airline code}}

DEVELOPER.md
=> add documentation for deploying / sync.pl

.github/dependabot.yml
The dependabot patches generate a lot of noise in emails, PR requests, etc. These are just dev dependencies, so I don't think they're worth much time and effort to keep updated. A yearly reminder should be enough.
=> switch dependabot from monthly to yearly

modules/twinklexfd.js, tests/jest.setup.js, tests/twinklexfd.test.js
Closes  #1718. Simply a regex change to place it above the header below. If you change  Tested [here](https://test.wikipedia.org/w/index.php?title=Wikipedia:Requested_moves/Technical_requests&diff=prev&oldid=559331). The regex may seem more complicated than necessary, but it's required to avoid spacing issues if we have extra newlines which were tested in the two edits before the linked one.
=> Rmtr order

modules/friendlytag.js
In [a discussion](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_October_31#Template:Duflu) to which I actually contributed but, I think, without understand the full context, it was agreed a couple of years ago to merge the English Wikipedia templates Duflu and Needtrans. It seems the main issue was that there was some overlap between the Twinkle functionality used for the two main sections of [[WP:PNT]], the [project page on "Pages needing translation to English"](https://en.wikipedia.org/wiki/Wikipedia:Pages_needing_translation_into_English).
Twinkle can be used to add an article not in English to a section at [[WP:PNT]] devoted to listing such pages. When an article is added, the default text under it was supplied by substing {{needtran}}, which generated a …
=> BUG FIX: Use separate templates for two sections of WP:PNT

modules/twinklewarn.js
added {{uw-blar}} and {{uw-articletodraft}}
=> added {{uw-blar}} and {{uw-articletodraft}}

modules/twinklexfd.js
Reported by QuietHere at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#RM%2FTR_error
Hotfix already deployed: https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadget-twinklexfd.js&diff=prev&oldid=1170247859
=> Fix RMTR bug

modules/twinklewarn.js
I just merged #1797, but I realized it needs `hideReason: true` because the {{{2}}} parameter is not a reason. This patch fixes that.
Related #1797
Related #1753
=> hideReason=true for Uw-blar and Uw-articletodraft

twinkle.js
Fixes #1886
Related #1881
Menus are jumping around too much during page load with TW menu on the left. Need to move it back to its spot on the right.
The spot on the right is reserved for it in https://en.wikipedia.org/wiki/MediaWiki:Gadget-Twinkle.css
=> twinkle: Put TW menu back on the right side of the More menu

twinkle.js
Fixes #1895 TW menu becomes unusable in vector-2022 if you dock the tools menu to the right side
=> twinkle: fix vector-2022 TW menu bug

twinkle.css
Removes hotfix for T337893. 
These extra styles for Vector are currently not necessary and cause excess padding.
Bug: T353214
=> Update twinkle.css for Vector Zebra CSS refactor

modules/twinklexfd.js
RFD, CFD, and TFD entries added to daily log pages by Twinkle currently have no line break between the entry being added and the next entry. They touch each other.
This patch fixes that. After this patch, there will be a line break between each entry.
Before: https://test.wikipedia.org/w/index.php?title=Wikipedia:Categories_for_discussion/Log/2023_December_4&diff=prev&oldid=584083
After: https://test.wikipedia.org/w/index.php?title=Wikipedia:Categories_for_discussion/Log/2023_December_4&diff=prev&oldid=584085
=> xfd: in daily log pages, add a line break to the end of some entries

.github/workflows/labeler.yml
Fix #1907
I can't easily figure out how to upgrade the syntax of https://github.com/wikimedia-gadgets/twinkle/blob/master/.github/labels.yml from v4 to v5. As a band aid fix to get our CI working, force the PR labeler to use v4.
=> Fix PR labeler CI

modules/twinklewarn.js, morebits.js, tests/__snapshots__/morebits.quickForm.js.snap
The bug is that the warn dialog is a mix of light and dark elements.
Two strategies come to mind. Either lighten everything, or darken everything. I chose to lighten everything.
Follow-up patches will be needed for other modules. This patch just focuses on the warn module.
- in the warn module, remove dark mode styling from everything but the submit button
- sprinkle the "notheme" class liberally
- most elements can have classes added in the Morebits module, but the select2 element (fancy searchable dropdown list similar to jquery-chosen) is a third party library so needs special code
- add comment to morebits describing how select2 works
Related #1979
=> warn: fix dark mode

modules/friendlywelcome.js, modules/twinkleblock.js
a follow up of https://en.wikipedia.org/wiki/Template_talk:Welcome-unregistered-constructive#Requested_move_29_December_2023
=> Updating welcome anon templates' names.

modules/twinklearv.js
See: https://test.wikipedia.org/wiki/Wikipedia:Usernames_for_administrator_attention for testing
=> arv: censor username if offensive username is ticked

modules/friendlytag.js
Replaced {{subst:duflu}} with {{subst:Dual fluency request}} and {{subst:needtrans}} with {{subst:Translation request}} to enhance clarity.
=> tag: Use longer template names for readability

modules/friendlytag.js
For #1863/#1618
If a maintenance template had been moved but its `|name=` wasn't updated, the code would pick up every version of that template *except* for the current name (since obviously that won't appear in a linkshere for itself and it tries to use the `|name=` for its current name). This fixes that by ensuring that whatever page linkshere resolves to is also included in the templates it attempts to remove
Credit to #1618 for the solution, I just tested it to make sure it worked
(Testing) Fixes #1618
=> tag: Fix removing tags for maintenance templates where |name= points to a redirect

modules/friendlywelcome.js
Fixes #1958 
Fixes #1957
Fixes #1814
=> Add unsourced, and welcomeen-it/hi/id

.github/workflows/codeql-analysis.yml
CodeQL v1 is deprecated per [this GitHub blog](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)
Update to v3 (was going to be v2, but that's [deprecated](https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/) at the end of 2024)
=> Use CodeQL v3 over v1

modules/twinkleconfig.js, modules/twinklespeedy.js
Resolves #1994
Also removes "G8: Redirects to non-existent targets" criterion from category CSD list, since that list doesn't display on redirects. The redirect CSD list does display on category redirects, and includes G8.
=> speedy: replace db-templatecat with C4

modules/friendlytag.js
=> tag: fix multiple issues grouping

scripts/dev-server.js
- Allow using OAuth 2 token for enabling/disabling onwiki gadget
- Speeds up the process of disabling onwiki gadget as OAuth2 doesn't require login. Closes #1883
- Mitigate token errors while re-enabling onwiki gadget
- By preemptively fetching a new CSRF token if more than 15 minutes passed from the user starting the server.
- Parallelize filesystem read calls
- Earlier, each file was being read sequentially from disk. Parallelizing the calls is seen to reduce load times by 25%.
=> Performance optimizations in dev-server

DEVELOPER.md, modules/friendlytag.js, modules/friendlywelcome.js, modules/twinklefluff.js, modules/twinklewarn.js, morebits.js
IE 11 is no longer supported, by Twinkle or by MediaWiki, for a while now.
=> Remove IE 11 compatibility code

modules/friendlytag.js, modules/twinklewarn.js
fixes #1554
fixes #1697
fixes #1698
fixes #1867 and fixes #1879 (these are duplicates)
fixes #1901
fixes #1961
fixes #1971
fixes #1980 
fixes #1990
=> add tags and warnings

modules/friendlytag.js, modules/twinklespeedy.js
=> speedy: update u5, tag: add {{User-generated}}, {{BLP one source}}, {{BLP no footnotes}}

modules/friendlytag.js
Readability refactor
- replace `Array.indexOf(a) !== -1` with `Array.includes(a)`
- add whitespace
- put complex conditionals on multiple lines
- tweak comments
- delete a specific message for "{{Bad GIF|JPEG|SVG}}" and replace it with a more generic message, since the code was too complex there to be worth keeping it
=> tag: refactor file tag form validation code

modules/twinkleconfig.js, twinkle.js
- No longer allow users to set portlet preferences. These hidden preferences were rarely used (6 users found onwiki), and increase technical debt by making the code complex. I think it makes sense to eliminate them.
- Move defaults for these values to the Twinkle.addPortlet() function, a more natural spot for these.
- One of these preferences was used outside the Twinkle.addPortlet() function, so modify Twinkle.addPortlet() to return the preference and place it in a variable.
- Add comments
- Improve docblocks
- Remove unnecessary code
Related #1836
=> no longer allow users to set portlet preferences

modules/friendlywelcome.js
Fixes #2038
Full list of languages added:
{{subst:Welcomeen-fa}} (Persian)
{{subst:Welcomeen-ha}} (Hausa)
{{subst:Welcomeen-ms}} (Malay)
{{subst:Welcomeen-no}} (Norwegian)
{{subst:Welcomeen-pl}} (Polish)
{{subst:Welcomeen-th}} (Thai)
{{subst:Welcomeen-tl}} (Tagalog)
{{subst:welcomeen-tr}} (Turkish)
{{subst:Welcomeen-ur}} (Urdu)
{{subst:Welcomeen-vi}} (Vietnamese)
=> welcome: add some {{Welcomeen-XX}} templates

modules/twinklexfd.js, morebits.js
=> Support batch requested moves

modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinklexfd.js
Fixes #2018. TimedText pages can't display templates, but still use the wikitext content model for some reason, so they weren't caught by that check.
I am not an admin so could not fully test the protection changes – if someone who is could protect a TimedText page and verify that no tag is automatically placed that would be appreciated.
=> prevent placing of protection, XFD, or CSD tags on TimedText pages 

modules/friendlywelcome.js
Foreign language welcomes are odd in that they place a signed message with two level 3 headings, but no level 2 heading.
Talk page messages should always have a level 2 heading, so this adds that, while keeping the level 3 headings as well.
Before:
After:
=> welcome: add level 2 headings for foreign language welcomes

modules/twinklerollback.js
Continue honoring the confirmOnFluff and confirmOnMobileFluff preferences (renamed in #2056) which are in use by 900+ users.
When a user changes any of their Twinkle preferences, these two preferences if in use will get automatically renamed. When this has occurred for most users, support for them can be dropped.
=> rollback: support older fluff preferences

modules/twinklearv.js
This is part of a set of patches to implement the preview functionality described in #671.
No functionality has changed here - the only change is a refactor of the ANI reporting logic to pull out two methods responsible for generating the reports from the code that posts the reports.
=> arv: refactor AIV report generation

modules/twinklerollback.js, twinkle.js
- fixes an issue where if a user still had the old confirmOnFluff or confirmOnRollback preferences, and visited the preferences page and saved, their preferences were ignored and silently deleted
- refactor complicated conditional in twinklerollback.js module
- reverts #2059 because we accomplish the same thing by putting the code in twinkle.js -> twinkleGetPref()
=> config: don't ignore old fluff preferences

.eslintignore, .eslintrc.json, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinklebatchundelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkledeprod.js, modules/twinklediff.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklerollback.js, modules/twinkleshared.js, modules/twinklespeedy.js, modules/twinkletag.js, modules/twinkletalkback.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklewelcome.js, modules/twinklexfd.js, morebits.js, twinkle.js
* move ignorePatterns to .eslintignore, makes bash commands easier
* wrap-iife
* no-var
* prefer-const
* prefer-arrow-callback
* arrow-parens
* arrow-body-style
* manual fixes, to deal with comments that confused the autofix
I made it one autofix per commit, to make the diffs easier to read.
`npx eslint --no-eslintrc --fix --rule '{wrap-iife: error}' --env 'es6' .`
I have found eslint autofixes to be extremely reliable. I have never encountered a bug with them that has broken the program. I have seen them mess with code formatting in unexpected ways though, so for that reason I am still spot checking each diff.
This will probably be the first of several patches. Doing all the autofixes in one patch would make a revert a pain.
=> eslint: apply autofixes 1

twinkle.js
hotfix
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Problems_with_WP%3ATwinkle
=> rollback: fix "cannot read properties of undefined"

.eslintrc.json, modules/twinklearv.js, modules/twinklebatchdelete.js, modules/twinklebatchprotect.js, modules/twinkleblock.js, modules/twinkleimage.js, modules/twinklerollback.js, modules/twinkleshared.js, modules/twinklespeedy.js, modules/twinkletag.js, modules/twinkletalkback.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklewelcome.js, modules/twinklexfd.js, morebits.js, twinkle.js
- apply all remaining autofixes with `npx eslint --fix .`
- turn off jsdoc/require-param because I didn't like the autofix. would just add params without any types or descriptions
- turn off jsdoc/require-returns for now. lots of docblocks that are just being used as comments, which is fine
- note that this messes with the docblocks in morebits.js. If we ever fix the documentation generator for morebits (#1668), if it doesn't use jsdoc, this might break some stuff in there. doesn't matter for the moment though since the morebits documentation website is broken
=> eslint: apply autofixes 3

.eslintrc.json, modules/twinkleblock.js, modules/twinklexfd.js, morebits.js
manual fixes. I tested one fix in the console, worked as expected. All 4 fixes follow the pattern of `var1 = 'x', var2 = 'y'` -> `var1 = 'x'; 'var2 = 'y'`
=> fix linter error no-sequences

.eslintrc.json, modules/twinkleblock.js, morebits.js, twinkle.js
Upstream, they caught a bug in the autofix algorithm. Basically, you should only change $.extend() to Object.assign() if you're sure the first argument isn't null or undefined. Else it will throw.
This patch changes a couple from `Object.assign(variable` to `Object.assign(variable || {}`.
https://github.com/wikimedia/eslint-plugin-no-jquery/commit/35d44891f1f09422211e8e1b02db10db6e27a2a8
Related #2079
=> fix some no-jquery/no-extend autofixes

.eslintrc.json
in preparation for fixing them
keep the camelcase warnings off for object keys. these could be API keys or something. needs further investigation before refactoring them
=> eslint: switch camelcase and underscore dangle from off to warn

.eslintrc.json, modules/twinklebatchprotect.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkleprotect.js, modules/twinklespeedy.js, modules/twinkletag.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js
=> eslint: fix prefer-const

modules/twinklewelcome.js
https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=1260049504#Moving_Template:Welcomeunsourced_to_Template:Welcome-unsourced
=> welcome: change {{welcomeunsourced}} to {{welcome-unsourced}} as result of page move

modules/twinklespeedy.js
This error message can occur when a template is missing onwiki. But it acts like it is because the user intentionally did not type a reason. I replaced it with a more neutral message.
=> speedy: less sassy error message

modules/twinkletag.js
manual fixes using F2 (rename variable) in VS Code. just one module for now. easier to test, and so I can get some confidence in this way of doing fixes before I move on to other modules
=> eslint: fix some `camelcase`

.eslintignore, tests/.eslintrc.json
I had it off. I guess because it needs a different config (wikimedia/server). This patch sets that up.
Will run autofixes in the next patch. Should be able to get rid of a bunch of rule exceptions by running the autofixes.
=> tests: turn on eslint

.eslintrc.json, modules/twinklebatchdelete.js, modules/twinkleblock.js, modules/twinkleconfig.js, modules/twinkleimage.js, modules/twinkleprod.js, modules/twinkleprotect.js, modules/twinklerollback.js, modules/twinklespeedy.js, modules/twinkletag.js, modules/twinkleunlink.js, modules/twinklewarn.js, modules/twinklexfd.js, morebits.js, twinkle.js
after discussion in #2101, removes the prohibition on using .includes()
also, adds a prohibition on using .indexOf !== -1, and applies the autofixes
=> eslint: replace es-x/no-array-prototype-includes with unicorn/prefer-includes

tests/.eslintrc.json, tests/morebits.date.js
manual fixes using F2 rename variable in VS Code
=> eslint: fix camelcase in tests

scripts/dev-server.js
Per https://mwn.toolforge.org/docs/api/interfaces/mwnoptions.html, the name of the config option is "OAuth2AccessToken", not "oauth2Token". This prevented me from using the gadget-disabling functionality using OAuth (I would have needed a bot password).
(Ignore the name of my repo: GitHub only lets me have one fork.)
=> scripts/dev-server: fix misnamed OAuth parameter

modules/twinkleblock.js
Rename the Window variable to blockWindow, since Window is a global function.
Closes #2178
=> block: soft redirect to Special:Block for multi-blocked targets

.gitignore, DEVELOPER.md, package-lock.json, package.json, scripts/deploy.js, scripts/dev-server.js
* Easier to setup and run as Twinkle developers already have node.js and npm installed. (Closes [#1771](https://github.com/wikimedia-gadgets/twinkle/pull/2183))
* Uses npm libraries that are fully compatible with Windows. (Closes [#1909](https://github.com/wikimedia-gadgets/twinkle/pull/1909), [#2065](https://github.com/wikimedia-gadgets/twinkle/pull/2065), [#2066](https://github.com/wikimedia-gadgets/twinkle/pull/2066))
* Fixes existing bugs in the perl script. (Closes [#2067](https://github.com/wikimedia-gadgets/twinkle/pull/2067), [#2068](https://github.com/wikimedia-gadgets/twinkle/pull/2068))
* Removes unused features like the "pull" mode and the edit summary override options.
* Simplifies the cli interface: 
* Defaults to deploying all files (no more passing `--all`) 
* Combines …
=> Port the deployment script from perl to node.js

scripts/deploy.js
Instead of hardcoding 5 as the number of lines of the wiki gadget definition to diff against, check N lines where N = number of (non-empty) lines in the local gadget definition file.
Solves #2189
=> deploy.js: fix gadget definition diffing

DEVELOPER.md, modules/twinklespeedy.js, tests/.eslintrc.json, tests/__snapshots__/twinklespeedy.test.js.snap, tests/jest.setup.js, tests/twinklespeedy.test.js
related #2199 refactor CSD code to make it easy to add CSDs
First of several patches. End goal is to make it so that to add/edit/remove a CSD, you only have to edit one spot in the code, instead of a bunch of different spots. This spot is in JSON format.
- move "lists" (e.g. fileList, redirectList, etc.) into Twinkle.speedy.data
- move normalizeHash into Twinkle.speedy.data
- add snapshot tests (this will ensure we don't break anything with our refactoring. may remove later)
- remove `"unfree": "f5"` from snapshot since Template:Db-unfree is a disambiguation page
- update readme to reflect these changes
- mention `Twinkle.speedy.getParameters()` in readme
- turn off eslint max-len for jest tests
=> speedy: refactor data to be in JSON
