- modules/twinklexfd.js
make sidebar, inline and tiny available in a dropdown
> provide more options for TfD notification template

- modules/twinkleblock.js
A rather **urgent pull request**... a careless mistake with the last pull request caused indefinite presets to have default durations (e.g. vandalism-only preset sets block duration to 31 hours). This is easily solved by not transforming the block presets data until after we've got the current block information, if present.
Also omitting the `anon=yes` parameter for hard blocks of IPs. Despite what the documentation says, the copy that the template generates makes it clear this should be used only for soft blocks.
> Fixes for indefinite duration presets, only set anon=yes for soft blocks

- README.md
Based on my experience today setting up sync with help from AzaToth.
> Modifies the README file to further clarify the steps needed to setup sync

- Makefile
- README.md
> Makefile should accept parameters for deploy.

- modules/twinklexfd.js
- morebits.js
It might work for other venues too but haven't tested.
Issue #168
This is a GCI task.
> Add preview to XfD module for afd, mfd, tfd/tfm, ffd

- modules/friendlytag.js
Implements the simplest suggestion mentioned in #330.
I plan on implementing the others if possible.
Plus, it'll be a nice way to get to know twinkle
> 'Fixes #330: Reword the message for 'New unreviewed article'

- modules/twinkleprotect.js
This is subject to misuse, so including a confirmation popup indicating it is (currently) strictly for Arbitration purposes on qualifying subjects.
> protect: add new 30/500 protection

- README.md
twinkledelimages no longer exists
> Update README.md to reflect current modules

- Makefile
This should have been added as part of d3e0f94cc4ed9f66aafc7db6c34e3dc77d790381
> Add twinkleblock to Makefile

- README.md
- sync.pl
- twinkle-pagestyles.css
- twinkle.css
- twinkle.js
Update sync instructions in README
> twinkle: new hidden CSS peer gadget to prevent jumpiness in Vector skin

- modules/friendlyshared.js
- modules/friendlywelcome.js
- modules/twinklearv.js
- modules/twinklefluff.js
- modules/twinklewarn.js
- morebits.js
- twinkle.js
> Clean up, avoid unnecessary jQuery use

- modules/twinklexfd.js
[Wikipedia talk:Twinkle#Modules at TfD instead of MfD](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=815907267#Modules_at_TfD_instead_of_MfD)
> Modules to TfD

- .eslintrc.json
- .gitignore
- .travis.yml
- modules/.eslintrc.json
- modules/friendlyshared.js
- modules/friendlytag.js
- modules/friendlytalkback.js
- modules/friendlywelcome.js
- modules/twinklearv.js
- modules/twinklebatchdelete.js
- modules/twinklebatchprotect.js
- modules/twinklebatchundelete.js
- modules/twinkleblock.js
- modules/twinkleconfig.js
- modules/twinkledeprod.js
- modules/twinklediff.js
- modules/twinklefluff.js
- modules/twinkleimage.js
- modules/twinkleprod.js
- modules/twinkleprotect.js
- modules/twinklespeedy.js
- modules/twinkleunlink.js
- modules/twinklewarn.js
- modules/twinklexfd.js
- morebits-test.js
- morebits.js
- package-lock.json
- package.json
- twinkle.js
This is the beginning of some lint-based cleanup; we can enable more rules as we go on.
@azatoth: can you enable Travis builds on https://travis-ci.org/azatoth/twinkle?
> Lint JS files with ESLint

- modules/friendlytag.js
I'm no expert in JS but this should work. Please see if so
> tag: add undisclosed paid template

- modules/twinklewarn.js
Add {{uw-paid1}}, {{uw-paid2}}, {{uw-paid3}}, {{uw-paid4}}
For #402
> Add uw-paid series

- modules/twinkleprotect.js
> twinkleprotect: Remove expiry param from tag

- modules/friendlywelcome.js
Add the {{welcome-athletics}} WikiProject-specific welcoming template. I'm of course OK with any changes that need to be made for this to merge.
> Add {{welcome-athletics}}

- modules/twinklewarn.js
Closes #448
uw-attempt was split here in 2015
> warn: Add missing/newly created uw-attempt1

- modules/friendlytag.js
- modules/twinkleconfig.js
- modules/twinklespeedy.js
- modules/twinklewarn.js
- morebits.js
- twinkle.js
All of the standard supported browsers should be fine after this change.
> Remove deprecated functions and unneeded shims

- modules/friendlytag.js
smol fix, template has been deleted
> tag: Remove deleted {{split media}} template

- modules/twinkledeprod.js
Removed in #400, missed in #413
> deprod: Restore nowiki tags

- modules/twinkleprod.js
> prod: add |help=off to template if notification was sent

- modules/friendlywelcome.js
These changes have NOT been tested. I'm just saving you the editing part of the work, not the testing part. 😉 
Maintainers of this project have write access on my patch-5 branch and are welcome to fix any problems before merging.
closes #420
> friendlywelcome: Fix #420

- modules/twinkleblock.js
Deleted at [TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2019_January_7#Template:Uw-memorialblock)
> block: Remove uw-memorialblock

- morebits.js
Continuation of #481. JSDocs for queryString, quickForm and simpleWindow.
There are still a handful of undocumented functions remaining though.
> Morebits: more documentation

- modules/twinkleprod.js
> prod - Add bookprod (fix for #457)

- modules/twinklefluff.js
> fluff: Make summaries uniform, normalize notices, remove period

- modules/twinkleconfig.js
Correct a typo within a comment
> config: minor addition to invocation mode

- modules/twinklespeedy.js
> speedy: List redirect criteria above general

- modules/friendlytag.js
> tag: Don't allow empty mergetargets

- modules/twinklexfd.js
[Requested at WT:TW](https://en.wikipedia.org/wiki/Special:Permalink/887552892#Auto-detecting_the_prefix_Infobox_and_changing_the_Deletion_tag_display_style)
Both the class and category are added by Module:infobox
> xfd: Detect if template is infobox, select style automatically

- modules/twinkleprod.js
Closes #266.  Can't check for prior FfDs, since they don't leave a subpage or a log/category somewhere
> prod: Check for old PROD templates on talkpage or an existing AfD, abort if found

- modules/twinklefluff.js
Closes #131
Checking for wgDiffOldId and wgDiffNewId excludes Special:Undelete (where they
are each 0), and so should be sufficient to avoid problematic diffs.
One advantage of the restructuring is that [restore this revision] will now
appear when viewing the first revision as a diff with diff=prev and will not
appear on the left-hand revision when viewing the latest revision with
diff=cur, as may sometimes happen.  Similarly, revert or restore links should
no longer appear on single-revision pages.  This makes some of the
logic/checks a tad involved, as well as the fact that wgDiffNewId and
wgDiffOldId have unbalanced behavior (see [[phab:T214985]]).
> fluff: Add [restore this revision] link to oldid pages

- modules/twinklebatchdelete.js
> batchdelete: fix bug in image-delinker

- modules/twinklearv.js
> Remove extra blank line for UAA reports

- modules/friendlytag.js
> tag: Restrict PNT posting for "not English" and "rough translation" to mainspace

- modules/twinklebatchundelete.js
Add option to restore talk pages of undeleted pages, if they existed.
> batchundelete: restore talk pages too

- modules/twinklespeedy.js
Commits 1, 2, 4, 8 - tweak what criteria are shown where and how they are implemented
Commit 3 - wording tweak
Commits 5, 9-11 - reduce repeated function calls
Commit 6, 7 - change where the CSD menu is available
> Speedy: Cleanup and simplify code around userList, redirects, and function calls, and add plain G8 to categories

- modules/twinkleprotect.js
Reverts azatoth/twinkle#551: Today's software update (https://www.mediawiki.org/wiki/MediaWiki_1.34/wmf.4) removed `wgFlaggedRevsParams` (see https://phabricator.wikimedia.org/T219342 and https://gerrit.wikimedia.org/r/c/mediawiki/extensions/FlaggedRevs/+/508427) so this is no longer viable.
Will investigate future options.
> Revert "protect: Don't fail if flaggedrevs/pending changes aren't enabled"

- modules/twinkleprotect.js
As noted in #629, the [MediaWiki 1.34-wmf4](https://www.mediawiki.org/wiki/MediaWiki_1.34/wmf.4) unceremoniously removed `wgFlaggedRevsParams` (see https://phabricator.wikimedia.org/T219342#5116724 and https://gerrit.wikimedia.org/r/c/mediawiki/extensions/FlaggedRevs/+/508427), meaning that the changes in #551 meant the pending changes dropdown would *never* be shown.  This re-enables those changes using a check for the gadget extension, since it's what we've got (https://phabricator.wikimedia.org/T218479 would be helpful...).  Or, as git would say:
Revert "Revert "protect: Don't fail if flaggedrevs/pending changes aren't enabled"" (this reverts commit e6fd37bfc0a3b3faa976df84a274881dbba3051d)
> protect: re-enable check for flaggedrevs/pending changes being enabled

- modules/twinklexfd.js
> xfd: simplify conditions in callback.evaluate

- morebits.js
1st commit: morebits: minor corrections to existing documentation
2nd commit: add documentation for Morebits.status
> Morebits: Add documentation for Morebits.status

- modules/twinkleprod.js
Suggested by @siddharthvp.  Old XfD tags are reliably added upon closure of the XfD, whether automatically by XFDCloser or manually (certainly much more so than {{Old PROD}} ever was).  Different content may exist at the same title, so if the movie [[My Cousin Vinny]] is deleted at AfD and then later someone writes [[My Cousin Vinny]] about a family member, the mere existence of an AfD using that title shouldn't prevent the recreation from being PRODed.  It's a rare edge case, but does occur (https://en.wikipedia.org/w/index.php?oldid=896314665#Twinkle_will_now_try_to_detect_Template:Old_prod_and_old_AfDs,_and_will_place_the_talk_page_template_automatically) and is possibly the rare case where the user-managed template is more accurate.
Using the `templates` prop allows us to look for …
> prod: Detect prior XfDs using templates on talk page rather than just existence of AfD discussion

- modules/friendlytag.js
As discussed in #647.
The first commit is a bug fix, which I have included in this PR because the bug affects the working of status text update.
> tag: add status text after Submit button, fix untag bug

- modules/friendlytag.js
> tag: preserve checked status of custom tags over mode change

- README.md
- modules/twinklewarn.js
- modules/twinklexfd.js
See discussion at https://github.com/azatoth/twinkle/pull/580#issuecomment-486772811, also references #641
cc @siddharthvp and @MusikAnimal as part of that convo
> Add jquery.chosen to the gadget file

- modules/twinklewarn.js
Would extend beyond the dialog window for some users
> warn: make chosen width 💯

- modules/twinklewarn.js
Added in #626, fairly universally disliked
> warn: don't bold usertalk links on diffs

- modules/twinkleimage.js
- modules/twinklespeedy.js
Fixes the bug reported at [TW talk page](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_41#CSD_F5_files).
> speedy/image: fix CSD log link for F5 replacement file

- modules/twinkleblock.js
Per https://en.wikipedia.org/wiki/Wikipedia_talk:Template_messages/User_talk_namespace/Archive_16#Requested_move_3_July_2019
> block: uw-myblock renamed to uw-socialmediablock

- modules/twinklexfd.js
C2F: One eponymous article - see https://en.wikipedia.org/wiki/Wikipedia:Categories_for_discussion/Speedy#C2F:_One_eponymous_article
> Add C2F to CFDS criteria

- modules/friendlytag.js
Extend quick filtering (added in #647) to redirects and files too.
> tag: add quick filter for redirects and files too

- modules/twinklewarn.js
Flesh out the uw-own and uw-tpv series, [requested by creator at WT:TW](https://en.wikipedia.org/w/index.php?oldid=921613796#Add_more_user_warnings).
> warn: Add own4 and tpv4im

- morebits.js
Allow API calls in JSON format, but without breaking any existing code. For backwards compatibility,
- API queries that don't specify a format will default to XML
- In `Morebits.wiki.api.prototype`, `responseXML` and its accessor `getXML()` are retained, though new `response` and its accessor `getResponse()` have been added. These can used with both formats.
This kinda solves #180, though mw.Api() hasn't been used here. 
This required very little changes in the existing code so I wonder why this wasn't done before, because people have been moaning the lack of JSON support for ages (#148, #259).
> morebits: allow API calls in JSON format

- twinkle.js
- In vector, remove bullets and margins by changing the structure from `<div class=menu><ul>...</ul></div>` to `<ul class=menu>...</ul>` per https://github.com/azatoth/twinkle/issues/713#issue-499541613. (Closes #713)
- In timeless, group Twinkle options under a "Twinkle" header. (Closes #751)
- Add role=navigation and aria-labelledby attributes to the portlet div, improving accessibility. All portlets in MediaWiki core have them.
The part of the code after the switch should also be more readable now.
> twinkle: fix up menus in vector and timeless

- morebits.js
JSDocs supports single-line comments too. This is better to use for the functions with very short descriptions.
Also improve the JSDoc comments here and there.
> morebits: better JSDocs

- modules/twinkleconfig.js
timeless and minerva(neue)
FWIW: cologne blue is still installed on enwiki despite not being automatically selectable
> config: add two missing skins to 'Looking for Twinkle' notice

- modules/friendlytalkback.js
Closes #797, introduced in 1f52094
> talkback: Don't show 'False' optout always

- modules/twinkleprotect.js
See onwiki request at https://w.wiki/EeR
> Protect: Add section link at rpp

- modules/twinkleblock.js
- modules/twinklewarn.js
- morebits.js
All this ideally should have been part of #813, but @Amorymeltzer was in a hurry :)
BTW, I think the partial block related changes, especially #825 and this, should be merged now and not in March. Don't wait for people to get used to the pathetic interfaces and [complain when we actually improve it](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=prev&oldid=937707395).
> block: improve partial block menus

- modules/friendlytag.js
Requested at [WT:TW](http://en.wikipedia.org/wiki/Special:Permalink/938800759#Tagging_redirects).
> tag: add two highly used redirect templates

- modules/twinklearv.js
Mentioned at https://github.com/azatoth/twinkle/pull/774#issue-347336213
> arv: Reorder so that VAO and promo-only are together, spambot is last

- modules/twinkleprod.js
> prod: Include a link to the log for file nomination logging

- modules/twinkleblock.js
> block: Add uw-aepblock

- modules/twinklexfd.js
> xfd: Disable rm in categoryspace, ffd outside filespace

- modules/twinklespeedy.js
> speedy: return slightly sooner if getParameters doesn't return anything

- modules/friendlytag.js
- modules/twinklespeedy.js
Added in #852, avoids overlapping with any other windows open
> Use unique class on proxy button to change button text

- modules/friendlytag.js
Closes #718, which correctly notes that this made things (even more) overly-complicated, had some errors, and wasn't particularly meaningful.  Generally consolidates article tag generation of summaries.  Also fixes some pluralization issues and oxfordizes removal notes and extends edit summaries, as they now out at 500 not 255 (or 1000): phabricator.wikimedia.org/T188798
> tag: Remove references to MI tag in edit summary

- modules/twinkleblock.js
I generally prefer more information, but I do admit this makes the note rather lengthy.
Draft because I'd rather use #814.
> block: Show expiry in currently blocked message

- modules/friendlytalkback.js
Repeatedly requested.  Restructured `evaluate` alongside a simple `getNoticeWikitext`.  Also makes used of `required: true` for relevant `page` inputs.
<s>2nd commit adds some heavy-handed processing to try to avoid errors.  Basically, any non-wikipedia non-talkpage is converted into its talkpage.  Not sure if this is good or just rude, so welcome feedback!</s> Have other plans where this makes more sense, will do there rather than muddy-up this PR.
> talkback: Add preview

- modules/twinklearv.js
Excessively complicated thanks to how <s>stupidly</s> excessively diverse diff links can be; probably the most time I've spent on something with the least value.  Draft because it'll conflict with #814, but feel free to test and find more edge cases. 🤕
> arv: Correctly handle all diff link formats in free_resolves

- modules/twinklewarn.js
Deleted at [TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_April_16#Template:Uw-bizlist)
> warn: Remove uw-bizlist

- modules/twinklewarn.js
See #841: if a Twinkle user is on a usertalk page after trying to revert or rollback a revision (as opposed to clicking on the usertalk link on a diff, indicated by no `noautowarn` being present), check that the revision following the diff inquestion was made by the Twinkle user, otherwise add a note (building upon the message area added in #757) that they may not have been the person to have actually reverted the edit in question.
> warn: Check if reverting user actually reverted

- modules/friendlytag.js
Merged to {{db-f1}} at [TfD](https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_March_28#Template:Duplicate)
There are now only three items in the file replacementList, FWIW
> tag: Remove {{duplicate}}

- modules/twinkleprod.js
- modules/twinklespeedy.js
- morebits.js
Class for handling the logic to add to a userspace log.
No need to duplicate the code across 2-3 modules. Makes the code more object-oriented.
> morebits/speedy/prod: add Morebits.userspaceLogger

- modules/twinkleblock.js
See [Template talk:Uw-pblock](https://en.wikipedia.org/w/index.php?title=Template_talk:Uw-pblock&oldid=955973873#Duplicate_%22from%22)
> block: Fix partialblock language when block is infinite

- modules/twinkleprod.js
Twinkle has been adding it with a lowercase p but only case-insensitively matching the uppercase P
> prod: Fix caps matching for {{Proposed deletion endorsed}}

- modules/twinkleblock.js
- modules/twinklewarn.js
- modules/twinklexfd.js
Per follow-up in #971 from the addition in #692, these appear unnecessary.
> xfd/warn/block: Remove 10k z-index on select2 dropdowns

- modules/twinkleunlink.js
Draft as it will conflict with #908, want to wait on that.
> unlink: Alert/return if no pages selected, show more accurate interface message

- modules/twinkleprod.js
Suggested at https://github.com/azatoth/twinkle/pull/972#issuecomment-650792064
> prod: Require confirmation if an empty reason is provided

- modules/friendlytag.js
The object still gets run through twice, no matter what.  Previously, it would get run through every time the category sort was chosen.  In all likelihood, this probably means more computation, but given our limited dataset it should always be fairly limited (0.05ms on my decade-plus laptop), especially compared to things like rendering.  In practice, this is a start toward genericizing some of this stuff, so file and redirect tags can do something similar.  FWIW, `Object.keys` was about 30%-40% faster than `$.each`
----
@siddharthvp I'd be curious what you think of this.  It's not particularly pretty, but it's a step toward combining everything and I think it just makes more sense not to maintain two lists, given the size means it won't be too computationally heavy.
> Restructure and combine article tag objects outside of sortorder

- DEVELOPER.md
- Gadget.md
- sync.pl
This should make it easier to track changes to the gadget, as well as confirm when changes are needed.
> docs: Put gadget definition in Gadget.md, enable checking via sync.pl

- .eslintrc.json
- package-lock.json
- package.json
New in 7.3.0; no errors, but seems reasonable https://eslint.org/docs/rules/no-unreachable-loop
> lint: Update eslint to v7.4.0, add no-unreachable-loop

- modules/twinklewarn.js
Shouldn't exist yet!  Fixes #1054
> warn: Don't insert twinkle-warn-warning-message before render

- morebits.js
https://github.com/Xi-Plus/twinkle/commit/f4fd970c48ef275449cdd73175ebec6861745315, Closes #1058
> morebits: insertAfterTemplates: Only throw if undefined aka not provided

- modules/twinklexfd.js
Cleanup of truckloads of messy code in xfd module. As discussed in #908.
> xfd: The Great Cleanup

- modules/twinkleblock.js
Add [Template:Uw-botuhblock](https://en.wikipedia.org/wiki/Template:Uw-botuhblock). Not a big fan of the summary as is w/r/t content and length, but couldn't come up with anything better.
> block: add uw-botuhblock

- modules/friendlytag.js
Requested at WT:TW: https://en.wikipedia.org/wiki/Special:Permalink/963782961#Image_hoax
> tag: Add {{Image hoax}}

- modules/twinklexfd.js
> xfd: Fix CfD/S tagging: cfdstarget !== cfdtarget

- modules/twinklearv.js
- modules/twinkleprotect.js
- modules/twinklexfd.js
- morebits.js
> morebits: Deprecate RegExp.escape in favor of Morebits.string.escapeRegExp

- modules/twinkleimage.js
Stems from #908 / 75ac385, where the check for existence was removed.  Fixes #1107
> image: Fix bug parsing namespace in replacement

- modules/twinklexfd.js
Nothing major, but some minor cleanups initially proposed at https://github.com/azatoth/twinkle/pull/1030#pullrequestreview-446909818
> xfd: various cleanups after #1030 / 81bb669

- modules/twinkleblock.js
> block: Clearer text for partial block summaries

- modules/twinklexfd.js
A number of items have been moved or added.  Notably, Indi now has its own section.
> xfd: Update delsort categories

- morebits.js
Reverts azatoth/twinkle#1137
Good lordy I've no idea what happened there; I could've sworn I'd tested that multiple separate ways.  Thanks for the catch @siddharthvp.
> Revert "morebits: remove getChecked/getUnchecked from HTMLFormElement prototype"

- modules/twinkleblock.js
The restructuring at the end of `change_action` has means `change_preset` is additionally being called whenever blocking is happening, not just if in the context of also applying a template.  This leads to `change_template`, which toggles the visibility of the DS select.
This has the side effect of changing how the form behaves when a user is already blocked.  Right now, the form doesn't display any of the old options by default (block and issue template).  *If* the sysop unchecks the issue template option, the block form will prefill with all the information from the original block (expiry, reason, etc.).  It's ephemeral, though, as if a preset is chosen, that information is then wiped clean, only returning if the issue template checkbox is toggled.
That's pretty misleading/confusing, …
> block: Add DS topic codes for aeblock/aepblock

- modules/twinklespeedy.js
Little black message, red if 3+, max 5.  Implements #1005.
cc @unforgettableid @Dinoguy1000
Right now, it doesn't take into account how old an entry is; that is, if a page was deleted three times in 2006, it'll be noted here.  If we want to add a time limit, we'd add something like:
```javascript
leend: new Morebits.date().subtract(2, 'years').toISOString(),
```
> speedy: Note number of previous deletions

- modules/twinklespeedy.js
Some code cleanup. Quite a lot of crappy code in this module ...
> speedy: code cleanup

- modules/twinklespeedy.js
> speedy: fix bug inverting watchPage parameter

- modules/twinklespeedy.js
> speedy: Fix bug from #1162 (failure to swap index/norm)

- modules/friendlytalkback.js
> talkback: Fix capitalization in edit summaries

- morebits.js
In addition to the comma and paren-wrapped UTC issues from #936, it turns out Safari's imeplementation of `Date.parse` is much more specific about what it accepts than Chrome and Firefox.  It's basically limited to the ECMAScript-262 standard of a simplified ISO-8601 standard, so even the cleaned up format won't work.  This obviously can cause issues, in particular with warn's autolevel selection, as reported at [WT:TW](https://en.wikipedia.org/w/index.php?oldid=986156173#Twinkle_auto-select_user_warning_level_not_working).
This could also be done with `.exec`:
```javascript
var result = /(\d\d:\d\d), (\d{1,2}) (.+) (\d{4}) \(UTC\)/.exec(args[0]);
args[0] = [result[4], mw.config.get('wgMonthNames').indexOf(result[3]), result[2]].join('-')+'T'+result[1]+'Z';
```
But I think the `.replace` …
> morebits date: Refactor MW timestamps to ISO 8601

- .github/labels.yml
- .github/workflows/labeler.yml
https://github.com/marketplace/actions/labeler
> action: Add PR labeler action based on which file they touch

- morebits.js
Similar in concept to `fnCheckPageName`; just useful for move, undelete, delete, protect, stabilize
Not entirely convinced `fnProcessChecks` is worth the complexity.  It's tucked away and greatly reduces repetition, but that `if` is ugly.
> morebits: Use common checks for wiki.page methods

- modules/twinklexfd.js
With all the XfD notices unified (29ae3373), we don't need to handle them individually.  This handles all current notifications, including without double-logging on MfDs, TfMs, and RfD, and handles non-userspace targets in RfD target notifications; the majority of the complexity is due to handling MfD and RfD.  Should also work for #1001.
Also fixes a bug in MfD notifications, where you could only notify the userspace owner if you were also notifying the creator, regardless of whether they were the same or not.
----
I think this is a benefit, as despite the annoying handlings, it's all in one spot rather than disparate.
> xfd: Use a unified user notification function

- modules/friendlyshared.js
- modules/friendlytag.js
- modules/friendlytalkback.js
- modules/friendlywelcome.js
- modules/twinklearv.js
- modules/twinkleblock.js
- modules/twinkleimage.js
- modules/twinkleprod.js
- modules/twinklespeedy.js
- modules/twinkleunlink.js
- modules/twinklewarn.js
- modules/twinklexfd.js
> Add footerlink to each dialog's preference pane

- modules/twinklewarn.js
cc @MattLongCT: I've refactored your work in #526 to fit into the new scheme.
Suddenly desired: https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=986493773
> warn: Add uw-subtle series (1-4)

- modules/twinklewarn.js
Add per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=987082046&oldid=987052409
> warn: Add uw-editsummary2

- morebits.js
Avoid putting in special cases to account for myriad browser differences – that isn't resilient or future-proof. The constructor was only meant to parse the signature timestamp format in addition to whatever Date() parses. Making this explicit by extracting the date parts from the string and passing them in `new Date(year, month, date, hour, minute)` format which is part of the standard (https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.3.1) and thus guaranteed to work everywhere.
> morebits: date: cleanup constructor

- morebits.js
> morebits: Default date.format to ISOString

- modules/friendlywelcome.js
The templates have been merged.
> welcome: Replace welcome-personal with welcome-cookie

- morebits.js
Firefox handles the enWiki timestamp format but incorrectly (#936), in particular by accepting the comma, so the date is treated as local since firefox (and chrome) ignore the trailing `(UTC)`.  Somehow in testing #1187, we missed the fact that the native date will preempty the timestamp check, so Firefox is once again messing things up.
----
cc @siddharthvp No idea how I missed this in #1187, I specifically tested all formats in all browsers!  Curious if you've got a smarter way of thinking about this.
> morebits.date: Rearrange constructor order to fix firefox bug

- modules/friendlytag.js
https://en.wikipedia.org/wiki/Template_talk:Bsr#Requested_move_20_November_2020
----
Premature, but likely.
> tag: {{Bsr}} renamed to {{Better source requested}}

- modules/friendlytag.js
Initial work on localisation of Tag module. See commits for details.
----
I have [imported](https://test.wikipedia.org/wiki/Special:Log?type=import&user=SD0001&page=&wpdate=2020-11-27&tagfilter=&subtype=) all article tag templates to testwiki for ease of testing.
> tag: initial work on l10n

- modules/twinklexfd.js
Also add a note if the edit request fails.  These are unlikely but possible.  `Twinkle.xfd.currentRationale` will still be printed, but we don't want to null it out since there's no guarantee other important actions (namely, listing) have taken place.  Is there a way to deal with it here?
> xfd: Don't try to add edit request if page is already a talk

- modules/twinkleblock.js
Temporary; see [[Wikipedia:Arbitration/Requests/Case/Horn of Africa]] and [[Special:Permalink/993316360#Arbitration motion regarding Horn of Africa]]
> block: Add Horn of Africa DS topic

- modules/twinklearv.js
Not done in #1184 since I was trying for fidelity to the original, but I think the combination of tweaked language + black versus red text makes it palatable; cf the changes to markblocked I made for partial blocks.
cc @DannyS712 @creffett
> arv: Note and soften message if user is already blocked

- modules/twinklewarn.js
Per https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&diff=989209699&oldid=988940845
> warn: Add uw-notenglishedit

- modules/twinkleconfig.js
- modules/twinklespeedy.js
- twinkle.js
Deprecated at https://en.wikipedia.org/wiki/Wikipedia_talk:Criteria_for_speedy_deletion#RFC:_should_WP:T3_be_deprecated?
----
Premature, but winter is coming
> speedy: Remove T3

- modules/friendlytag.js
https://en.wikipedia.org/wiki/Wikipedia:Templates_for_discussion/Log/2020_October_31#Template:Duflu
> tag: duflu merged to needtrans at TfD

- modules/friendlywelcome.js
> welcome: Fix welcome-short parameter syntax

- modules/twinklefluff.js
Stems from some crossed wires in #1230 amid changing how we handle these.
> fluff: Fix parameter for setting watchlist expiry when editing

- modules/twinkleunlink.js
Was showing an incorrect example for files, and was unclear what would happen to a plain link i.e. without a differing display text.  Gets a bit lengthy, especially for files, but I think it's worth it since this can be used for mass changes.
----
Bumping the width of the window could help, dunno that it's worth it though.
> unlink: Properly show what will happen to all links

- morebits.js
Might as well accept all the valid MW API options.
Also expand `setWatchlistExpiry` docs.
> Morebits.wiki.page.setWatchlist: Accept nochange option

- modules/twinklefluff.js
Less similar to the 'Reverted revisions' summary.
> fluff: Change 'Reverted to revision' edit summary to 'Restored revision'

- modules/twinkleprotect.js
I was using the `Morebits.wiki.page` object returned from the RfPP page itself to determine watchlist expiry status of the tagged page, which is clearly wrong.  Since we're not loading the page directly in that case, we can just tack on to the protection fetching and store it for later.  Fixes #1315.
cc @Xi-Plus
> protect: Fetch watched status of the page to properly watch when requesting

- morebits.js
See https://api.jqueryui.com/dialog/#event-resizeStop
> morebits: Correct jquery dialog event name

- morebits.js
This is unlikely to fail much due to API errors being just a read operation, but things like connection drops can always happen.
There ought to be _some_ way in which a failure can be detected.
> morebits: lookupCreation: add failure callback

- modules/friendlytag.js
The templates have been merged.
> tag: R from template shortcut merged with R from shortcut

- modules/friendlytag.js
[Old request](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_42#COI)
----
Presumably others could warrant from this, in particular {{POV}}, but likely most of the "neutrality" section.  Should we be disfavoring both of those or some subset?  Probably better to ask on-wiki.
> tag: COI: Add area for automatically starting a discussion on the talkpage

- morebits.js
1. Enables the value of `this` in the task functions to be set via the constructor. A minor limitation here is that all tasks get the same value for `this`.
2. Enable handling of failures. For each task a failure function can be set. This will be invoked if the task errors out or returns a rejected promise. It will also be invoked if the task was never started due to a failure in any of its dependencies.
---- 
Written for twinkle-core, but at the moment, I'm completely lost on how to manage morebits in twinkle-core. 
The failure handling is used in XfdCore as a replacement for the `Morebits.status.onError` which twinklexfd uses (which has resulted in many issues). A lot cleaner and allows for much better programmatic control.
> morebits: taskManager: enable failure handling and setting context

- morebits.js
`setWatchlist` now takes a second parameter, allowing you to explicitly set the watchlist expiry if so desired.
To break it down, the MediaWiki API allows four watching options:
- `watch`: Explicitly watch the page, using the expiry if provided
- `preferences`: Watch (or not) the page according to preferences, using the expiry if appropriate and provided
- `nochange` (default): Don't change the binary watch status, but if an expiry is provided and appropriate, use it
- `unwatch`: Expiry doesn't matter
We've made two small editorial decisions here:
- If no expiry is provided for a `watch` or `preferences` option, default to indefinite watching.  This mirrors prior (and expected) behavior.
- If `nochange` is provided, explicitly set the expiry to `null`, so `nochange` really means "no …
> morebits: Expand setWatchlist handling of expiry, default to infinity for watch/preferences

- morebits.js
Useful in tests to detect that everything is done.
> morebits: status: add extra class on actionCompleted message

- modules/twinklespeedy.js
The two lines were repeated ten times in short succession, with little variability
> speedy: Consolidate repetitive appends into a single function

- modules/friendlytalkback.js
> talkback: Allow template-space for discussions for DYK

- morebits.js
Fixes #1344.
Reminiscent of f92f0233b, although unrelated.
> morebits: quickform: fix duplication of IDs in select/optgroup

- modules/friendlytag.js
Fixed typo: "grahpics"->"graphics"
> tag: fix typo: "grahpics"->"graphics"

- modules/twinkleprotect.js
> protect: Implement #1429

- modules/friendlytag.js
> tag: add {{Inappropriate person}}

- modules/friendlytag.js
Fixes #1415 Add Template:R from non-neutral name
> tag: add {{Template:R from non-neutral name}}

- modules/twinklewarn.js
Fixes #1350 Update to uw-attempt warning series
> warn: add level4im to {{uw-attempt}} warning series

- modules/friendlytag.js
Fixes #1412 Adding example farm tag
> tag: add {{Excessive examples}} to article maintenance tags

- modules/twinklexfd.js
Fixes #1428 Read delsort topics from wiki page
> xfd: read delsort topics from wiki page

- modules/friendlytag.js
Fixes #1037 tag: Add validations to redirect tags
> tag: add validations to redirect tags

- modules/twinklexfd.js
Fixes #1109 Shouldn't try to file invalid requested moves
> speedy: warn if attempting RM in draft or userspace

- modules/twinklexfd.js
Fixes #1445 Add the option of type=disabled to TfD
> xfd: add the option of type=disabled to TfD

- modules/friendlywelcome.js
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Add_Template:Thanks_to_IP_welcome_messages
> welcome: add {{Thanks}} to IP welcome templates

- modules/twinkleblock.js
Fixes #1525
Untested since I am not an oversighter on TestWiki. Maybe @Primefac can test this one? Details on how to load the dev version are located at https://github.com/wikimedia-gadgets/twinkle/blob/master/CONTRIBUTING.md#testing-your-code
> block: fix {{OversightBlock}} not showing as option

- modules/twinklexfd.js
Have not tested, but should resolve #1519.
> xfd: Use Deletion sorting/multi

- modules/friendlytag.js
> tag: {{Merge to}} combined with an article section has incorrect "Discuss" link

- modules/twinklexfd.js
Fix #1565
This is already hotfixed on wiki, but I'll leave this PR open for feedback and in case we need to fix any other bugs related to #1524
> xfd: fix undefined variable error affecting FFD, TFD, etc.

- modules/friendlytag.js
Requested by IAmChaos at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Template
> tag: add redirect tag {{R from married name}}

- modules/friendlytag.js
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Redirect_format
> tag: increase whitespace in redirects

- modules/twinkleprotect.js
Fixes bug from #1433 when selecting a preset to protect an AfD and fixes #1543.
> protect: Bug fix from #1433 and fixes #1543

- modules/friendlytag.js
Requested by IAmChaos at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Tag_Request
> tag: add {{R to ASCII-only}}

- README.md
> README: remove outdated mention of mediawiki code used in tests

- modules/twinklewarn.js
> warn: Do not add extra section markup for setNewSectionTitle

- modules/twinkleprotect.js
Fixes #1594
Normal behavior: `{{pp|small=y}}`
New behavior when content model sanitized-css, css, or javascript detected: `/* {{pp|small=y}} */`
Adjusted two spots in the existing code: the algorithm to add templates when protecting, and the algorithm to remove them when unprotecting.
> protect: comment out protection template for CSS and JS

- modules/twinklewarn.js
> warn: add {{Uw-paraphrase}}

- twinkle.js
https://en.wikipedia.org/wiki/Special:Permalink/1102644895#Inconsistent_tab_display_in_Vector_2022
> twinkle: fix menu appearance for skin vector-2022

- modules/twinkleconfig.js
Fixes for https://phabricator.wikimedia.org/T300314
Before:
After:
> config: Replace removed successbox classes

- modules/friendlywelcome.js
> remove {{Welcome-menu}} and {{Welcome-graphical}}

- modules/twinkleunlink.js
Requested by Sanglahi86 and UtherSRG at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Improve_confusing_%22Unlink_backlinks%22_dialogue_description
> unlink: clearer wording

- twinkle.js
Fixes #1326
I think myself and Qwerfjkl are in favor (see onwiki discussion at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Add_%22Prefs%22_to_Twinkle_menu%3F), and @Amorymeltzer had some reservations. Open to feedback.
> twinkle: add preferences link to dropdown menu

- modules/twinkleprotect.js
> protect: don't place reason parameter in protection template

- scripts/dev-server.js
> dev-server.js: don't lazy load dependencies

- modules/twinklefluff.js
While I was groking and testing #1642, I refactored the code a bit for readability.
> fluff: refactor history() for readability

- modules/twinklespeedy.js
Requested by ಮಲ್ನಾಡಾಚ್ ಕೊಂಕ್ಣೊ at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#db-error
> speedy: add {{Db-error}} (G6)

- modules/friendlytag.js
Requested by MB at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Rcat_templates
> tag: add {{R from alternative transliteration}} and {{R from film}}

- modules/friendlytag.js
> friendlytag: Remove merged template Over-coverage

- modules/twinkleconfig.js
- modules/twinklespeedy.js
- twinkle.js
Closes #1723. Tested and looks like expected (the portal section isn't displayed in portal spaces but other namespaces are unaffected). All mentions of P1, P2, portal and the namespace IDs 100 and 101 have been checked to make sure there's no residual code.
> Remove speedy deletion criteria P1 and P2

- modules/twinkleprotect.js
Sir, I have rename 'pp-30-500' to 'pp-extended'.
> #1542 protect: rename {{pp-30-500}} to {{pp-extended}}

- modules/twinkleprotect.js
> protect: clearer wording for edit and move protection

- modules/friendlytag.js
> tag: rename {{More footnotes}} to {{More footnotes needed}}

- modules/friendlywelcome.js
This will add the welcome-copyright template to friendlywelcome.js, in line with Issue #1757
> Add welcome-copyright

- modules/twinkleprotect.js
> protect: add generic ECP option to protection module

- modules/friendlywelcome.js
- add comment
- capitalize a template name
- remove dead code (the template W-short does not support the parameter heading=true)
Related #1785
> welcome: minor refactor

- modules/friendlywelcome.js
> welcome: add {{WikiProject Women in Red invite}}

- package-lock.json
`npm start` tested, works. If CI passes, this should be safe to merge. Will likely resolve the 5 pending dependabot PRs.
> `npm update`

- modules/twinklewarn.js
> fix hideReason not working when used without hideLinkedPage

- .github/labels.yml
fix PR labeler is failing CI #1907
- upgrade to version 5 format
- start labeling .github/* files with the "tests" label, because it makes sense, and so I can test this
> fix PR labeler

- .github/labels.yml
Reverts wikimedia-gadgets/twinkle#1908
> Revert "fix PR labeler"

- modules/twinklewarn.js
Resolves #1897. Previous PR #1927 was closed because my editor bunged my branches.
> warn: add uw-longsd

- morebits.js
This pull request pertains to issue #1864(submit button: change "Submit Query" to "Submit").
> changed Submit Query to Submit in morebits.js

- modules/friendlytag.js
* add comments
* convert an else statement to elseif
For readability. Should be a no-op.
> tag: improve readability of WP:PNT code

- modules/twinkleconfig.js
Requested by Graham87 at https://en.wikipedia.org/wiki/MediaWiki_talk:Gadget-Twinkle.js#Interface-protected_edit_request_on_28_July_2024
> config: fix grammar in helptip

- modules/twinklexfd.js
fix #1984
If there's a way to set a text box width to 100% in morebits, that might be better here. Otherwise this is probably good enough.
> xfd: widen cfd/s "new name" text box

- .github/dependabot.yml
- DEVELOPER.md
- turn off dependabot
- remove some dependabot stuff from .md file
- add a sentence to a .md file
fixes #1852
When approving this, also delete the open dependabot PRs.
> build: turn off dependabot

- modules/friendlywelcome.js
Add template as to issue #1905
> Welcome user: Add Mentor welcome template

- modules/twinklewarn.js
Add the template for single issue notice of misusing user talk pages.
> Update twinklewarn.js with {{uw-usertalk}}

- twinkle.js
> twinkle: Move nuisance error to console

- modules/friendlytag.js
> tag: disable tagging of category redirects

- modules/friendlytag.js
> tag: add parenthetical referencing tag

- modules/friendlytag.js
> tag: Adding {{Cleanup colors}} + {{Overcoloured}}

- modules/friendlytalkback.js
> talkback: remove leading whitespace on new pages

- modules/twinkleprotect.js
> protect: stop noincluded tags breaking headers

- twinkle.js
> Change markTalkbackAsMinor to default to off

- modules/twinklewarn.js
> Adding {{uw-pronouns1}}, {{uw-pronouns2}} and {{uw-pronouns3}}

- gadget.txt
no changes except for whitespace
> gadget.txt: sync with what's onwiki

- modules/twinklearv.js
This is part of a set of patches to implement the preview functionality described in #671.
No functionality has changed here - the only change is a refactor of the UAA reporting logic to pull out a method responsible for generating the reports from the code that posts the reports.
> arv: refactor UAA report generation

- modules/twinklexfd.js
> Fix RM summary/log

- modules/twinklearv.js
- modules/twinklebatchdelete.js
- modules/twinklebatchprotect.js
- modules/twinklebatchundelete.js
- modules/twinkleblock.js
- modules/twinkleconfig.js
- modules/twinkledeprod.js
- modules/twinklediff.js
- modules/twinkleimage.js
- modules/twinkleprod.js
- modules/twinkleprotect.js
- modules/twinklerollback.js
- modules/twinkleshared.js
- modules/twinklespeedy.js
- modules/twinkletag.js
- modules/twinkletalkback.js
- modules/twinkleunlink.js
- modules/twinklewarn.js
- modules/twinklewelcome.js
- modules/twinklexfd.js
- morebits.css
- twinkle.js
related #2084
case sensitive, all repo search and replace, excluding test files and the file morebits.js. will handle those in a later patch since messing with the morebits.js file may be risky. In that file, not everything will have the Morebits prefix, making search and replace harder.
```
Morebits.BatchOperation <- Morebits.batchOperation
Morebits.Date <- Morebits.date
Morebits.QuickForm <- Morebits.quickForm
Morebits.QuickForm.Element <- Morebits.quickForm.element
Morebits.SimpleWindow <- Morebits.simpleWindow
Morebits.Status <- Morebits.status
Morebits.TaskManager <- Morebits.taskManager
Morebits.Unbinder <- Morebits.unbinder
Morebits.UserspaceLogger <- Morebits.userspaceLogger
Morebits.wiki.Api <- Morebits.wiki.api
Morebits.wiki.Page <- Morebits.wiki.page
Morebits.wiki.Preview <- …
```
> capitalize Morebits class names

- .eslintrc.json
- modules/twinkleconfig.js
- modules/twinklewarn.js
- morebits.js
I declined a couple of the autofixes because I don't like how it added Math.max(), which is complicated to read. I kept the helpful ones.
> autofix some eslint unicorn/prefer-string-slice

- .eslintrc.json
- modules/twinklebatchdelete.js
- modules/twinklebatchprotect.js
- modules/twinkleblock.js
- modules/twinkleimage.js
- modules/twinklespeedy.js
- modules/twinkleunlink.js
- modules/twinklewarn.js
- modules/twinklexfd.js
- morebits.js
- twinkle.js
Manual revert. Partial revert.
There's an upstream bug in the autofix ( https://github.com/wikimedia/eslint-plugin-no-jquery/issues/343 ). I don't want to take any chances.
Fixes #2106
> eslint: revert $.extend autofixes

- .eslintrc.json
- modules/twinklearv.js
- modules/twinkleblock.js
- modules/twinkleconfig.js
- modules/twinklerollback.js
- modules/twinkletalkback.js
- morebits.js
> eslint: fix no-useless-concat

- .eslintrc.json
- morebits.js
> eslint: fix no-throw-literal

- modules/twinkletag.js
Fixes https://github.com/wikimedia-gadgets/twinkle/issues/2064
> tag: remove {{Now Commons}}

- modules/twinkleblock.js
- tests/jest.setup.js
- tests/twinkleblock.test.js
> block: add regression test

- .eslintrc.json
- modules/twinklebatchdelete.js
- morebits.js
> eslint: fix no-underscore-dangle

- package-lock.json
mainly to fix this warning in my console:
> build: run `npm update`

- modules/twinkleconfig.js
I doubt TTO wants to be contacted directly with questions
> config: delete 14 year old comment

- modules/twinkletag.js
- tests/jest.setup.js
- tests/twinkletag.test.js
Writing automated tests for this gives me more confidence that I didn't make a mistake in PR #2103
> tag: add tests for checkIncompatible()

- .eslintrc.json
- modules/twinkletag.js
- tests/twinkletag.test.js
> eslint: fix no-return-assign

- tests/.eslintrc.json
- tests/morebits.batchOperation.js
- tests/morebits.date.js
- tests/morebits.quickForm.js
- tests/morebits.taskManager.js
- tests/morebits.unbinder.js
- tests/morebits.wikitext.js
manual fixes
related #2084
- capitalize newable morebits classes in code
- capitalize newable morebits classes in test file names
> eslint: fix new-cap in tests

- tests/.eslintrc.json
- tests/morebits.js
> eslint: fix no-useless-escape in tests

- modules/twinkletag.js
> tag: delete {{Incomprehensible}}

- modules/twinkletag.js
> tag: replace {{manual}} with {{how-to}}
